-- =============================================================
-- MIGRATION 14: Missing tables referenced by FastAPI routers
-- =============================================================

-- Fix: Ensure quiz_domain exists on quiz_attempt_answers for analytics
DO $$ 
BEGIN 
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_schema = 'public' 
      AND table_name = 'quiz_attempt_answers' 
      AND column_name = 'quiz_domain'
  ) THEN 
    ALTER TABLE public.quiz_attempt_answers 
    ADD COLUMN quiz_domain TEXT CHECK (quiz_domain IN ('gk', 'maths', 'passage', 'mains'));
    
    CREATE INDEX IF NOT EXISTS idx_qaa_quiz_domain ON public.quiz_attempt_answers(quiz_domain);
  END IF;
END $$;

-- ---------------------------------------------------------------
-- AI ARTICLE STYLE GUIDES (admin-configurable editorial style)
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.ai_article_style_guides (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title       TEXT NOT NULL,
  style_guide TEXT NOT NULL,   -- Full instruction text injected into article generation prompt
  is_active   BOOLEAN NOT NULL DEFAULT TRUE,
  created_by  BIGINT REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

DROP TRIGGER IF EXISTS trg_ai_article_style_guides_updated_at ON public.ai_article_style_guides;
CREATE TRIGGER trg_ai_article_style_guides_updated_at
  BEFORE UPDATE ON public.ai_article_style_guides
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.ai_article_style_guides ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "style_guides_admin_all" ON public.ai_article_style_guides;
CREATE POLICY "style_guides_admin_all" ON public.ai_article_style_guides
  FOR ALL TO authenticated
  USING (public.is_admin_or_moderator()) WITH CHECK (public.is_admin_or_moderator());

-- ---------------------------------------------------------------
-- AI ARTICLE DRAFTS (generated drafts awaiting admin review)
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.ai_article_drafts (
  id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  raw_input_url           TEXT,
  raw_input_text          TEXT,
  ai_generated_title      TEXT,
  ai_generated_excerpt    TEXT,
  ai_generated_content    TEXT,
  ai_suggested_tags       TEXT[]   NOT NULL DEFAULT '{}',
  ai_suggested_subject_id BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
  ai_suggested_topic_id   BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
  ai_suggested_subtopic_id BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
  status                  TEXT NOT NULL DEFAULT 'pending_review'
    CHECK (status IN ('pending_review', 'published', 'rejected')),
  published_article_id    BIGINT REFERENCES public.articles(id) ON DELETE SET NULL,
  created_by              BIGINT REFERENCES public.profiles(id) ON DELETE SET NULL,
  reviewed_by             BIGINT REFERENCES public.profiles(id) ON DELETE SET NULL,
  reviewed_at             TIMESTAMPTZ,
  created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ai_article_drafts_status ON public.ai_article_drafts(status);
CREATE INDEX IF NOT EXISTS idx_ai_article_drafts_created ON public.ai_article_drafts(created_at DESC);

DROP TRIGGER IF EXISTS trg_ai_article_drafts_updated_at ON public.ai_article_drafts;
CREATE TRIGGER trg_ai_article_drafts_updated_at
  BEFORE UPDATE ON public.ai_article_drafts
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.ai_article_drafts ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "article_drafts_admin_all" ON public.ai_article_drafts;
CREATE POLICY "article_drafts_admin_all" ON public.ai_article_drafts
  FOR ALL TO authenticated
  USING (public.is_admin_or_moderator()) WITH CHECK (public.is_admin_or_moderator());

-- ---------------------------------------------------------------
-- AI MAINS QUESTIONS (AI-generated practice questions saved by users)
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.ai_mains_questions (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id          BIGINT NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  question_text    TEXT NOT NULL,
  answer_approach  TEXT,
  model_answer     TEXT,
  word_limit       INTEGER NOT NULL DEFAULT 250,
  category_id      BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
  language         TEXT NOT NULL DEFAULT 'en',
  is_saved         BOOLEAN NOT NULL DEFAULT TRUE,
  is_active        BOOLEAN NOT NULL DEFAULT TRUE,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ai_mains_questions_user   ON public.ai_mains_questions(user_id);
CREATE INDEX IF NOT EXISTS idx_ai_mains_questions_cat    ON public.ai_mains_questions(category_id);

DROP TRIGGER IF EXISTS trg_ai_mains_questions_updated_at ON public.ai_mains_questions;
CREATE TRIGGER trg_ai_mains_questions_updated_at
  BEFORE UPDATE ON public.ai_mains_questions
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.ai_mains_questions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "ai_mains_questions_own" ON public.ai_mains_questions;
CREATE POLICY "ai_mains_questions_own" ON public.ai_mains_questions
  FOR ALL TO authenticated
  USING (
    public.is_admin_or_moderator()
    OR EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = ai_mains_questions.user_id AND p.auth_user_id = auth.uid())
  )
  WITH CHECK (
    EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = ai_mains_questions.user_id AND p.auth_user_id = auth.uid())
  );

-- ---------------------------------------------------------------
-- USER MAINS EVALUATIONS (saved AI evaluation results)
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.user_mains_evaluations (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id             BIGINT NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  question_id         BIGINT REFERENCES public.ai_mains_questions(id) ON DELETE SET NULL,
  question_text       TEXT NOT NULL,
  answer_text         TEXT NOT NULL,
  word_count          INTEGER,
  ai_score            NUMERIC(5,2),
  ai_max_score        NUMERIC(5,2) DEFAULT 10,
  ai_feedback         TEXT,
  ai_strengths        TEXT[] DEFAULT '{}',
  ai_weaknesses       TEXT[] DEFAULT '{}',
  ai_structure_score  NUMERIC(5,2),
  ai_content_score    NUMERIC(5,2),
  improved_answer     TEXT,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_user_mains_eval_user ON public.user_mains_evaluations(user_id);
CREATE INDEX IF NOT EXISTS idx_user_mains_eval_created ON public.user_mains_evaluations(created_at DESC);

ALTER TABLE public.user_mains_evaluations ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "user_mains_eval_own" ON public.user_mains_evaluations;
CREATE POLICY "user_mains_eval_own" ON public.user_mains_evaluations
  FOR ALL TO authenticated
  USING (
    public.is_admin_or_moderator()
    OR EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = user_mains_evaluations.user_id AND p.auth_user_id = auth.uid())
  )
  WITH CHECK (
    EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = user_mains_evaluations.user_id AND p.auth_user_id = auth.uid())
  );

-- ---------------------------------------------------------------
-- RPC: get_user_answers_for_snapshot
-- Used by analytics.py to compute performance snapshots.
-- ---------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.get_user_answers_for_snapshot(
  p_user_id   BIGINT,
  p_domain    TEXT,
  p_category_id BIGINT DEFAULT NULL
)
RETURNS TABLE (
  is_correct      BOOLEAN,
  is_skipped      BOOLEAN,
  time_spent_secs INTEGER,
  category_id     BIGINT
)
LANGUAGE SQL STABLE AS $$
  SELECT
    qaa.is_correct,
    qaa.is_skipped,
    qaa.time_spent_secs,
    qaa.category_id
  FROM public.quiz_attempt_answers qaa
  JOIN public.test_attempts ta ON ta.id = qaa.attempt_id
  WHERE
    ta.user_id = p_user_id
    AND qaa.quiz_domain = p_domain
    AND (p_category_id IS NULL OR qaa.category_id = p_category_id);
$$;
