-- =============================================================
-- MIGRATION 3: Study Content — Articles, Blogs, Study Pages
-- =============================================================

-- ---------------------------------------------------------------
-- ARTICLES
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.articles (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title               TEXT        NOT NULL,
  slug                TEXT        UNIQUE,
  summary             TEXT,
  excerpt             TEXT,
  main_article        TEXT,
  linked_summary      TEXT,
  linked_main_article TEXT,
  image_url           TEXT,
  featured_image      TEXT,
  -- Taxonomy
  subject_id          BIGINT REFERENCES public.subjects(id) ON DELETE SET NULL,
  topic_id            BIGINT REFERENCES public.topics(id) ON DELETE SET NULL,
  subtopic_id         BIGINT REFERENCES public.subtopics(id) ON DELETE SET NULL,
  source_id           BIGINT REFERENCES public.sources(id) ON DELETE SET NULL,
  source_url          TEXT,
  news_date           DATE,
  -- SEO
  meta_description    TEXT,
  meta_keywords       TEXT,
  seo_title           TEXT,
  seo_description     TEXT,
  -- State
  status              TEXT NOT NULL DEFAULT 'draft'
    CHECK (status IN ('draft', 'published', 'archived')),
  published_at        TIMESTAMPTZ,
  views_count         INTEGER NOT NULL DEFAULT 0,
  -- Authorship
  author_id           BIGINT NOT NULL REFERENCES public.profiles(id) ON DELETE RESTRICT,
  posted_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  keywords            JSONB NOT NULL DEFAULT '[]'::JSONB,
  sources             JSONB NOT NULL DEFAULT '[]'::JSONB,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_articles_author_id     ON public.articles(author_id);
CREATE INDEX IF NOT EXISTS idx_articles_topic_id      ON public.articles(topic_id);
CREATE INDEX IF NOT EXISTS idx_articles_source_id     ON public.articles(source_id);
CREATE INDEX IF NOT EXISTS idx_articles_status_pub    ON public.articles(status, published_at DESC);
CREATE INDEX IF NOT EXISTS idx_articles_news_date     ON public.articles(news_date DESC);
CREATE INDEX IF NOT EXISTS idx_articles_posted_at     ON public.articles(posted_at DESC);

DROP TRIGGER IF EXISTS trg_articles_set_updated_at ON public.articles;
CREATE TRIGGER trg_articles_set_updated_at
  BEFORE UPDATE ON public.articles
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- Article → Category (using unified categories, domain='article')
CREATE TABLE IF NOT EXISTS public.article_categories (
  article_id  BIGINT NOT NULL REFERENCES public.articles(id) ON DELETE CASCADE,
  category_id BIGINT NOT NULL REFERENCES public.categories(id) ON DELETE CASCADE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (article_id, category_id)
);
CREATE INDEX IF NOT EXISTS idx_article_categories_category ON public.article_categories(category_id);

-- Article Tags
CREATE TABLE IF NOT EXISTS public.article_tags (
  article_id BIGINT NOT NULL REFERENCES public.articles(id) ON DELETE CASCADE,
  tag_id     BIGINT NOT NULL REFERENCES public.tags(id) ON DELETE CASCADE,
  PRIMARY KEY (article_id, tag_id)
);

-- Article Sections (structured sub-content within an article)
CREATE TABLE IF NOT EXISTS public.article_sections (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  article_id        BIGINT NOT NULL REFERENCES public.articles(id) ON DELETE CASCADE,
  parent_section_id BIGINT REFERENCES public.article_sections(id) ON DELETE CASCADE,
  section_title     TEXT   NOT NULL,
  section_slug      TEXT   NOT NULL,
  content           TEXT   NOT NULL,
  display_order     INTEGER NOT NULL,
  heading_level     TEXT NOT NULL DEFAULT 'h2'
    CHECK (heading_level IN ('h2', 'h3', 'h4', 'h5', 'h6')),
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (article_id, section_slug)
);
CREATE INDEX IF NOT EXISTS idx_article_sections_article ON public.article_sections(article_id);

DROP TRIGGER IF EXISTS trg_article_sections_set_updated_at ON public.article_sections;
CREATE TRIGGER trg_article_sections_set_updated_at
  BEFORE UPDATE ON public.article_sections
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- Article Relations (embed / link between articles)
CREATE TABLE IF NOT EXISTS public.article_relations (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_article_id BIGINT NOT NULL REFERENCES public.articles(id) ON DELETE CASCADE,
  target_article_id BIGINT NOT NULL REFERENCES public.articles(id) ON DELETE CASCADE,
  relation_type     TEXT   NOT NULL CHECK (relation_type IN ('embed', 'link')),
  display_label     TEXT,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (source_article_id, target_article_id, relation_type)
);
CREATE INDEX IF NOT EXISTS idx_article_relations_source ON public.article_relations(source_article_id);
CREATE INDEX IF NOT EXISTS idx_article_relations_target ON public.article_relations(target_article_id);

-- Linkable Resources (laws, schemes, bodies that can be embedded)
CREATE TABLE IF NOT EXISTS public.linkable_resources (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resource_type TEXT NOT NULL CHECK (resource_type IN ('law','scheme','body','article','other')),
  title         TEXT NOT NULL,
  slug          TEXT NOT NULL UNIQUE,
  description   TEXT,
  url           TEXT,
  content       TEXT,
  subject_id    BIGINT REFERENCES public.subjects(id) ON DELETE SET NULL,
  tags          JSONB NOT NULL DEFAULT '[]'::JSONB,
  is_active     BOOLEAN NOT NULL DEFAULT TRUE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

DROP TRIGGER IF EXISTS trg_linkable_resources_set_updated_at ON public.linkable_resources;
CREATE TRIGGER trg_linkable_resources_set_updated_at
  BEFORE UPDATE ON public.linkable_resources
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE IF NOT EXISTS public.article_resource_links (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  article_id  BIGINT NOT NULL REFERENCES public.articles(id) ON DELETE CASCADE,
  section_id  BIGINT REFERENCES public.article_sections(id) ON DELETE CASCADE,
  resource_id BIGINT NOT NULL REFERENCES public.linkable_resources(id) ON DELETE CASCADE,
  link_type   TEXT NOT NULL DEFAULT 'inline'
    CHECK (link_type IN ('inline', 'embedded', 'reference')),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Article Likes & Comments
CREATE TABLE IF NOT EXISTS public.article_likes (
  article_id BIGINT NOT NULL REFERENCES public.articles(id) ON DELETE CASCADE,
  user_id    BIGINT NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (article_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.article_comments (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  article_id        BIGINT NOT NULL REFERENCES public.articles(id) ON DELETE CASCADE,
  author_id         BIGINT NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  parent_comment_id BIGINT REFERENCES public.article_comments(id) ON DELETE SET NULL,
  text              TEXT   NOT NULL,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

DROP TRIGGER IF EXISTS trg_article_comments_set_updated_at ON public.article_comments;
CREATE TRIGGER trg_article_comments_set_updated_at
  BEFORE UPDATE ON public.article_comments
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ---------------------------------------------------------------
-- BLOGS (content hubs / CMS)
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.blogs (
  id                           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                         TEXT NOT NULL,
  slug                         TEXT NOT NULL UNIQUE,
  description                  TEXT,
  content                      TEXT,
  seo_title                    TEXT,
  seo_description              TEXT,
  seo_image_url                TEXT,
  keywords                     JSONB NOT NULL DEFAULT '[]'::JSONB,
  current_affairs_category_id  BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
  current_affairs_limit        INTEGER,
  is_study_material            BOOLEAN NOT NULL DEFAULT FALSE,
  created_at                   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at                   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

DROP TRIGGER IF EXISTS trg_blogs_set_updated_at ON public.blogs;
CREATE TRIGGER trg_blogs_set_updated_at
  BEFORE UPDATE ON public.blogs
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE IF NOT EXISTS public.blog_posts (
  id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  blog_id                     BIGINT NOT NULL REFERENCES public.blogs(id) ON DELETE CASCADE,
  title                       TEXT   NOT NULL,
  slug                        TEXT   NOT NULL,
  full_slug                   TEXT   UNIQUE,
  content                     TEXT   NOT NULL,
  summary                     TEXT,
  seo_title                   TEXT,
  seo_description             TEXT,
  seo_image_url               TEXT,
  keywords                    JSONB  NOT NULL DEFAULT '[]'::JSONB,
  order_index                 INTEGER,
  parent_id                   BIGINT REFERENCES public.blog_posts(id) ON DELETE SET NULL,
  secondary_parent_ids        BIGINT[] NOT NULL DEFAULT '{}',
  current_affairs_category_id BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
  current_affairs_limit       INTEGER,
  author_id                   BIGINT REFERENCES public.profiles(id) ON DELETE SET NULL,
  is_active                   BOOLEAN NOT NULL DEFAULT TRUE,
  posted_at                   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (blog_id, slug)
);

CREATE INDEX IF NOT EXISTS idx_blog_posts_blog_id   ON public.blog_posts(blog_id);
CREATE INDEX IF NOT EXISTS idx_blog_posts_parent_id ON public.blog_posts(parent_id);
CREATE INDEX IF NOT EXISTS idx_blog_posts_full_slug ON public.blog_posts(full_slug);

DROP TRIGGER IF EXISTS trg_blog_posts_set_updated_at ON public.blog_posts;
CREATE TRIGGER trg_blog_posts_set_updated_at
  BEFORE UPDATE ON public.blog_posts
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ---------------------------------------------------------------
-- STUDY PAGES (navigation / syllabus tree pages)
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.study_pages (
  id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title                   TEXT   NOT NULL,
  slug                    TEXT   NOT NULL UNIQUE,
  content                 TEXT   NOT NULL DEFAULT '',
  image_url               TEXT,
  parent_id               BIGINT REFERENCES public.study_pages(id) ON DELETE SET NULL,
  order_index             INTEGER,
  rank                    INTEGER,
  navigation_bar_parent_id BIGINT REFERENCES public.study_pages(id) ON DELETE SET NULL,
  show_in_navbar          BOOLEAN NOT NULL DEFAULT FALSE,
  place_in_nav_root       BOOLEAN NOT NULL DEFAULT FALSE,
  navigation_label        TEXT,
  navigation_menu_bucket  TEXT,
  use_base_slug           BOOLEAN NOT NULL DEFAULT TRUE,
  keywords                JSONB NOT NULL DEFAULT '[]'::JSONB,
  seo_title               TEXT,
  seo_description         TEXT,
  author_id               BIGINT NOT NULL REFERENCES public.profiles(id) ON DELETE RESTRICT,
  posted_at               TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_study_pages_parent_id ON public.study_pages(parent_id);
CREATE INDEX IF NOT EXISTS idx_study_pages_nav_parent ON public.study_pages(navigation_bar_parent_id);

DROP TRIGGER IF EXISTS trg_study_pages_set_updated_at ON public.study_pages;
CREATE TRIGGER trg_study_pages_set_updated_at
  BEFORE UPDATE ON public.study_pages
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE IF NOT EXISTS public.study_page_alpha_categories (
  study_page_id     BIGINT NOT NULL REFERENCES public.study_pages(id) ON DELETE CASCADE,
  alpha_category_id BIGINT NOT NULL REFERENCES public.alpha_categories(id) ON DELETE CASCADE,
  PRIMARY KEY (study_page_id, alpha_category_id)
);

-- Study Page Lists (content lists embedded in study pages)
CREATE TABLE IF NOT EXISTS public.study_page_lists (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  study_page_id  BIGINT REFERENCES public.study_pages(id) ON DELETE CASCADE,
  blog_post_id   BIGINT REFERENCES public.blog_posts(id) ON DELETE CASCADE,
  content_type   TEXT NOT NULL DEFAULT 'study_page',
  title          TEXT NOT NULL,
  slug           TEXT NOT NULL,
  description    TEXT,
  order_index    INTEGER,
  display_config JSONB NOT NULL DEFAULT '{}'::JSONB,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK ((study_page_id IS NOT NULL) <> (blog_post_id IS NOT NULL)),
  UNIQUE (study_page_id, slug),
  UNIQUE (blog_post_id, slug)
);

DROP TRIGGER IF EXISTS trg_study_page_lists_set_updated_at ON public.study_page_lists;
CREATE TRIGGER trg_study_page_lists_set_updated_at
  BEFORE UPDATE ON public.study_page_lists
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE IF NOT EXISTS public.study_page_list_tag_fields (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  list_id      BIGINT NOT NULL REFERENCES public.study_page_lists(id) ON DELETE CASCADE,
  name         TEXT   NOT NULL,
  slug         TEXT   NOT NULL,
  multi_select BOOLEAN NOT NULL DEFAULT TRUE,
  order_index  INTEGER,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (list_id, slug)
);

DROP TRIGGER IF EXISTS trg_study_page_list_tag_fields_set_updated_at ON public.study_page_list_tag_fields;
CREATE TRIGGER trg_study_page_list_tag_fields_set_updated_at
  BEFORE UPDATE ON public.study_page_list_tag_fields
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE IF NOT EXISTS public.study_page_list_tag_values (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tag_field_id BIGINT NOT NULL REFERENCES public.study_page_list_tag_fields(id) ON DELETE CASCADE,
  label        TEXT   NOT NULL,
  slug         TEXT   NOT NULL,
  order_index  INTEGER,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (tag_field_id, slug)
);

DROP TRIGGER IF EXISTS trg_study_page_list_tag_values_set_updated_at ON public.study_page_list_tag_values;
CREATE TRIGGER trg_study_page_list_tag_values_set_updated_at
  BEFORE UPDATE ON public.study_page_list_tag_values
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE IF NOT EXISTS public.study_page_list_items (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  list_id       BIGINT NOT NULL REFERENCES public.study_page_lists(id) ON DELETE CASCADE,
  title         TEXT   NOT NULL,
  slug          TEXT   NOT NULL,
  brief         TEXT,
  detail_url    TEXT,
  image_url     TEXT,
  custom_fields JSONB NOT NULL DEFAULT '{}'::JSONB,
  order_index   INTEGER,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (list_id, slug)
);

DROP TRIGGER IF EXISTS trg_study_page_list_items_set_updated_at ON public.study_page_list_items;
CREATE TRIGGER trg_study_page_list_items_set_updated_at
  BEFORE UPDATE ON public.study_page_list_items
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE IF NOT EXISTS public.study_page_list_item_tag_values (
  item_id      BIGINT NOT NULL REFERENCES public.study_page_list_items(id) ON DELETE CASCADE,
  tag_value_id BIGINT NOT NULL REFERENCES public.study_page_list_tag_values(id) ON DELETE CASCADE,
  PRIMARY KEY (item_id, tag_value_id)
);

-- ---------------------------------------------------------------
-- TIMELINES (historical events)
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.timelines (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shortcode_id     TEXT NOT NULL UNIQUE,
  title            TEXT NOT NULL,
  description      TEXT,
  default_from_year INTEGER,
  default_to_year   INTEGER,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

DROP TRIGGER IF EXISTS trg_timelines_set_updated_at ON public.timelines;
CREATE TRIGGER trg_timelines_set_updated_at
  BEFORE UPDATE ON public.timelines
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE IF NOT EXISTS public.timeline_events (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  timeline_id BIGINT NOT NULL REFERENCES public.timelines(id) ON DELETE CASCADE,
  event_key   TEXT   NOT NULL,
  data        JSONB  NOT NULL DEFAULT '{}'::JSONB,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (timeline_id, event_key)
);

DROP TRIGGER IF EXISTS trg_timeline_events_set_updated_at ON public.timeline_events;
CREATE TRIGGER trg_timeline_events_set_updated_at
  BEFORE UPDATE ON public.timeline_events
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ---------------------------------------------------------------
-- ROW LEVEL SECURITY
-- ---------------------------------------------------------------

ALTER TABLE public.articles                           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.article_categories                 ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.article_tags                       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.article_sections                   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.article_relations                  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.article_likes                      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.article_comments                   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.linkable_resources                 ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.article_resource_links             ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.blogs                              ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.blog_posts                         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.study_pages                        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.study_page_alpha_categories        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.study_page_lists                   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.study_page_list_tag_fields         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.study_page_list_tag_values         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.study_page_list_items              ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.study_page_list_item_tag_values    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.timelines                          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.timeline_events                    ENABLE ROW LEVEL SECURITY;

-- Public-read / admin-write for all content tables
DO $$
DECLARE
  tbls TEXT[] := ARRAY[
    'articles','article_categories','article_tags','article_sections',
    'article_relations','linkable_resources','article_resource_links',
    'blogs','blog_posts','study_pages','study_page_alpha_categories',
    'study_page_lists','study_page_list_tag_fields','study_page_list_tag_values',
    'study_page_list_items','study_page_list_item_tag_values',
    'timelines','timeline_events'
  ];
  t TEXT;
BEGIN
  FOREACH t IN ARRAY tbls LOOP
    EXECUTE FORMAT('DROP POLICY IF EXISTS "%s_public_read" ON public.%I', t, t);
    EXECUTE FORMAT(
      'CREATE POLICY "%s_public_read" ON public.%I FOR SELECT TO anon, authenticated USING (TRUE)', t, t
    );
    EXECUTE FORMAT('DROP POLICY IF EXISTS "%s_admin_write" ON public.%I', t, t);
    EXECUTE FORMAT(
      'CREATE POLICY "%s_admin_write" ON public.%I FOR ALL TO authenticated
       USING (public.is_admin_or_moderator()) WITH CHECK (public.is_admin_or_moderator())',
      t, t
    );
  END LOOP;
END;
$$;

-- Article likes — users manage their own
DROP POLICY IF EXISTS "article_likes_insert_own" ON public.article_likes;
CREATE POLICY "article_likes_insert_own" ON public.article_likes
  FOR INSERT TO authenticated
  WITH CHECK (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = article_likes.user_id AND p.auth_user_id = auth.uid()));

DROP POLICY IF EXISTS "article_likes_delete_own" ON public.article_likes;
CREATE POLICY "article_likes_delete_own" ON public.article_likes
  FOR DELETE TO authenticated
  USING (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = article_likes.user_id AND p.auth_user_id = auth.uid()));

-- Article comments — users manage their own
DROP POLICY IF EXISTS "article_comments_insert_own" ON public.article_comments;
CREATE POLICY "article_comments_insert_own" ON public.article_comments
  FOR INSERT TO authenticated
  WITH CHECK (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = article_comments.author_id AND p.auth_user_id = auth.uid()));

DROP POLICY IF EXISTS "article_comments_update_own" ON public.article_comments;
CREATE POLICY "article_comments_update_own" ON public.article_comments
  FOR UPDATE TO authenticated
  USING (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = article_comments.author_id AND p.auth_user_id = auth.uid()))
  WITH CHECK (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = article_comments.author_id AND p.auth_user_id = auth.uid()));

DROP POLICY IF EXISTS "article_comments_delete_own_or_admin" ON public.article_comments;
CREATE POLICY "article_comments_delete_own_or_admin" ON public.article_comments
  FOR DELETE TO authenticated
  USING (
    public.is_admin_or_moderator()
    OR EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = article_comments.author_id AND p.auth_user_id = auth.uid())
  );
