-- =============================================================
-- MIGRATION 4: Quiz Content — GK/Maths, Passage, Mains Questions
-- =============================================================

-- ---------------------------------------------------------------
-- GK / MATHS QUIZZES
-- Full question structure with all UPSC-specific fields
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.quizzes (
  id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quiz_type                TEXT NOT NULL CHECK (quiz_type IN ('gk', 'maths')),
  title                    TEXT,
  slug                     TEXT UNIQUE,

  -- Question content
  question_statement       TEXT NOT NULL,
  supp_question_statement  TEXT,
  statements_facts         JSONB NOT NULL DEFAULT '[]'::JSONB,
  -- e.g. [{ "number": 1, "text": "India shares border with 7 nations" }, ...]
  question_prompt          TEXT,
  -- e.g. "Which of the following statements is/are correct?"
  options                  JSONB NOT NULL DEFAULT '[]'::JSONB,
  -- e.g. [{ "label": "A", "text": "1 only" }, { "label": "B", "text": "1 and 2 only" }]
  correct_answer           TEXT NOT NULL,
  explanation              TEXT,
  linked_explanation       TEXT,   -- URL to article / study page

  -- Contextual enrichment
  why_this_quiz            JSONB NOT NULL DEFAULT '[]'::JSONB,
  -- e.g. ["Current Affairs", "Environment"]
  why_this_quiz_text       TEXT,
  keywords                 JSONB NOT NULL DEFAULT '[]'::JSONB,
  sources                  JSONB NOT NULL DEFAULT '[]'::JSONB,
  -- e.g. [{ "title": "The Hindu", "url": "...", "date": "2026-04-10" }]

  -- Image support (with hotspot overlay for diagram questions)
  image_url                TEXT,
  image_hotspot_overlay    JSONB,

  -- Test settings
  difficulty               TEXT CHECK (difficulty IN ('easy', 'medium', 'hard')),
  time_limit_minutes       INTEGER,
  negative_marking_factor  NUMERIC(4,2) NOT NULL DEFAULT 0.33,

  -- Visibility
  is_pinned                BOOLEAN NOT NULL DEFAULT FALSE,
  visible_on_pages         TEXT[]  NOT NULL DEFAULT '{}',
  is_admin_only            BOOLEAN NOT NULL DEFAULT FALSE,

  -- Authorship & timestamps
  author_id                BIGINT NOT NULL REFERENCES public.profiles(id) ON DELETE RESTRICT,
  posted_at                TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at               TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at               TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_quizzes_quiz_type  ON public.quizzes(quiz_type);
CREATE INDEX IF NOT EXISTS idx_quizzes_posted_at  ON public.quizzes(posted_at DESC);
CREATE INDEX IF NOT EXISTS idx_quizzes_author_id  ON public.quizzes(author_id);
CREATE INDEX IF NOT EXISTS idx_quizzes_difficulty ON public.quizzes(difficulty);

DROP TRIGGER IF EXISTS trg_quizzes_set_updated_at ON public.quizzes;
CREATE TRIGGER trg_quizzes_set_updated_at
  BEFORE UPDATE ON public.quizzes
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- Quiz → Unified Category
CREATE TABLE IF NOT EXISTS public.quiz_categories (
  quiz_id     BIGINT NOT NULL REFERENCES public.quizzes(id) ON DELETE CASCADE,
  category_id BIGINT NOT NULL REFERENCES public.categories(id) ON DELETE CASCADE,
  PRIMARY KEY (quiz_id, category_id)
);
CREATE INDEX IF NOT EXISTS idx_quiz_categories_category ON public.quiz_categories(category_id);

-- Quiz → Free Exam
CREATE TABLE IF NOT EXISTS public.quiz_free_exams (
  quiz_id      BIGINT NOT NULL REFERENCES public.quizzes(id) ON DELETE CASCADE,
  free_exam_id BIGINT NOT NULL REFERENCES public.free_exams(id) ON DELETE CASCADE,
  PRIMARY KEY (quiz_id, free_exam_id)
);

-- Quiz → Alpha Category
CREATE TABLE IF NOT EXISTS public.quiz_alpha_categories (
  quiz_id           BIGINT NOT NULL REFERENCES public.quizzes(id) ON DELETE CASCADE,
  alpha_category_id BIGINT NOT NULL REFERENCES public.alpha_categories(id) ON DELETE CASCADE,
  PRIMARY KEY (quiz_id, alpha_category_id)
);

-- Quiz Likes
CREATE TABLE IF NOT EXISTS public.quiz_likes (
  quiz_id    BIGINT NOT NULL REFERENCES public.quizzes(id) ON DELETE CASCADE,
  user_id    BIGINT NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (quiz_id, user_id)
);

-- Quiz Comments
CREATE TABLE IF NOT EXISTS public.quiz_comments (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quiz_id           BIGINT NOT NULL REFERENCES public.quizzes(id) ON DELETE CASCADE,
  author_id         BIGINT NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  parent_comment_id BIGINT REFERENCES public.quiz_comments(id) ON DELETE SET NULL,
  text              TEXT   NOT NULL,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

DROP TRIGGER IF EXISTS trg_quiz_comments_set_updated_at ON public.quiz_comments;
CREATE TRIGGER trg_quiz_comments_set_updated_at
  BEFORE UPDATE ON public.quiz_comments
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ---------------------------------------------------------------
-- PASSAGE QUIZZES
-- The passage (reading comprehension) with sub-questions as a proper join table
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.passage_quizzes (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  passage_title    TEXT,
  slug             TEXT UNIQUE,
  passage_text     TEXT NOT NULL,
  source_reference TEXT,
  image_url        TEXT,

  -- Settings
  is_pinned        BOOLEAN NOT NULL DEFAULT FALSE,
  visible_on_pages TEXT[]  NOT NULL DEFAULT '{}',
  is_admin_only    BOOLEAN NOT NULL DEFAULT FALSE,

  author_id        BIGINT NOT NULL REFERENCES public.profiles(id) ON DELETE RESTRICT,
  posted_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_passage_quizzes_posted_at  ON public.passage_quizzes(posted_at DESC);
CREATE INDEX IF NOT EXISTS idx_passage_quizzes_author_id  ON public.passage_quizzes(author_id);

DROP TRIGGER IF EXISTS trg_passage_quizzes_set_updated_at ON public.passage_quizzes;
CREATE TRIGGER trg_passage_quizzes_set_updated_at
  BEFORE UPDATE ON public.passage_quizzes
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- *** KEY DECISION: passage sub-questions as JOIN TABLE ***
-- Each question belongs to one passage, enforced via CASCADE DELETE
-- Enables per-question analytics without losing tight coupling
CREATE TABLE IF NOT EXISTS public.passage_questions (
  id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  passage_quiz_id         BIGINT NOT NULL REFERENCES public.passage_quizzes(id) ON DELETE CASCADE,
  question_statement      TEXT   NOT NULL,
  supp_question_statement TEXT,
  question_prompt         TEXT,
  statements_facts        JSONB  NOT NULL DEFAULT '[]'::JSONB,
  options                 JSONB  NOT NULL DEFAULT '[]'::JSONB,
  -- [{ "label": "A", "text": "..." }, ...]
  correct_answer          TEXT   NOT NULL,
  explanation             TEXT,
  -- Category for analytics depth
  category_id             BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
  display_order           INTEGER NOT NULL DEFAULT 0,
  created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_passage_questions_passage  ON public.passage_questions(passage_quiz_id);
CREATE INDEX IF NOT EXISTS idx_passage_questions_category ON public.passage_questions(category_id);

DROP TRIGGER IF EXISTS trg_passage_questions_set_updated_at ON public.passage_questions;
CREATE TRIGGER trg_passage_questions_set_updated_at
  BEFORE UPDATE ON public.passage_questions
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- Passage → Unified Category
CREATE TABLE IF NOT EXISTS public.passage_quiz_categories (
  passage_quiz_id BIGINT NOT NULL REFERENCES public.passage_quizzes(id) ON DELETE CASCADE,
  category_id     BIGINT NOT NULL REFERENCES public.categories(id) ON DELETE CASCADE,
  PRIMARY KEY (passage_quiz_id, category_id)
);

-- Passage → Free Exam / Alpha Category
CREATE TABLE IF NOT EXISTS public.passage_quiz_free_exams (
  passage_quiz_id BIGINT NOT NULL REFERENCES public.passage_quizzes(id) ON DELETE CASCADE,
  free_exam_id    BIGINT NOT NULL REFERENCES public.free_exams(id) ON DELETE CASCADE,
  PRIMARY KEY (passage_quiz_id, free_exam_id)
);

CREATE TABLE IF NOT EXISTS public.passage_quiz_alpha_categories (
  passage_quiz_id   BIGINT NOT NULL REFERENCES public.passage_quizzes(id) ON DELETE CASCADE,
  alpha_category_id BIGINT NOT NULL REFERENCES public.alpha_categories(id) ON DELETE CASCADE,
  PRIMARY KEY (passage_quiz_id, alpha_category_id)
);

-- Passage Likes & Comments
CREATE TABLE IF NOT EXISTS public.passage_quiz_likes (
  passage_quiz_id BIGINT NOT NULL REFERENCES public.passage_quizzes(id) ON DELETE CASCADE,
  user_id         BIGINT NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (passage_quiz_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.passage_quiz_comments (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  passage_quiz_id   BIGINT NOT NULL REFERENCES public.passage_quizzes(id) ON DELETE CASCADE,
  author_id         BIGINT NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  parent_comment_id BIGINT REFERENCES public.passage_quiz_comments(id) ON DELETE SET NULL,
  text              TEXT   NOT NULL,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

DROP TRIGGER IF EXISTS trg_passage_quiz_comments_set_updated_at ON public.passage_quiz_comments;
CREATE TRIGGER trg_passage_quiz_comments_set_updated_at
  BEFORE UPDATE ON public.passage_quiz_comments
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ---------------------------------------------------------------
-- MAINS QUESTIONS (Subjective — used in Mains Programs)
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.mains_questions (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_text   TEXT        NOT NULL,
  word_limit      INTEGER     NOT NULL DEFAULT 250,
  marks           INTEGER     NOT NULL DEFAULT 10,
  question_year   INTEGER,
  model_answer    TEXT,
  approach        TEXT,        -- How to structure the answer
  key_points      JSONB        NOT NULL DEFAULT '[]'::JSONB,
  -- e.g. ["Intro with context", "Constitutional provisions", "Landmark cases"]
  source_reference TEXT,
  -- Category for analytics
  category_id     BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
  display_order   INTEGER,
  author_id       BIGINT REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_mains_questions_category ON public.mains_questions(category_id);
CREATE INDEX IF NOT EXISTS idx_mains_questions_author   ON public.mains_questions(author_id);

DROP TRIGGER IF EXISTS trg_mains_questions_set_updated_at ON public.mains_questions;
CREATE TRIGGER trg_mains_questions_set_updated_at
  BEFORE UPDATE ON public.mains_questions
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ---------------------------------------------------------------
-- KNOWLEDGE TESTS (Hotspot / Matching / Drag-Drop interactive items)
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.knowledge_tests (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_type           TEXT NOT NULL CHECK (item_type IN ('hotspot','matching','dragdrop')),
  title               TEXT NOT NULL,
  slug                TEXT NOT NULL UNIQUE,
  description         TEXT,
  image_url           TEXT,
  overlay             JSONB,
  options             JSONB,
  pairs               JSONB,
  explanation_name    TEXT,
  explanation_details TEXT,
  is_active           BOOLEAN NOT NULL DEFAULT TRUE,
  author_id           BIGINT REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

DROP TRIGGER IF EXISTS trg_knowledge_tests_set_updated_at ON public.knowledge_tests;
CREATE TRIGGER trg_knowledge_tests_set_updated_at
  BEFORE UPDATE ON public.knowledge_tests
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ---------------------------------------------------------------
-- ROW LEVEL SECURITY
-- ---------------------------------------------------------------

ALTER TABLE public.quizzes                    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quiz_categories            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quiz_free_exams            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quiz_alpha_categories      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quiz_likes                 ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quiz_comments              ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.passage_quizzes            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.passage_questions          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.passage_quiz_categories    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.passage_quiz_free_exams    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.passage_quiz_alpha_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.passage_quiz_likes         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.passage_quiz_comments      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mains_questions            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.knowledge_tests            ENABLE ROW LEVEL SECURITY;

-- Public read for all quiz content
DO $$
DECLARE
  tbls TEXT[] := ARRAY[
    'quizzes','quiz_categories','quiz_free_exams','quiz_alpha_categories',
    'quiz_likes','quiz_comments','passage_quizzes','passage_questions',
    'passage_quiz_categories','passage_quiz_free_exams','passage_quiz_alpha_categories',
    'passage_quiz_likes','passage_quiz_comments',
    'mains_questions','knowledge_tests'
  ];
  t TEXT;
BEGIN
  FOREACH t IN ARRAY tbls LOOP
    EXECUTE FORMAT('DROP POLICY IF EXISTS "%s_public_read" ON public.%I', t, t);
    EXECUTE FORMAT(
      'CREATE POLICY "%s_public_read" ON public.%I FOR SELECT TO anon, authenticated USING (TRUE)', t, t
    );
    EXECUTE FORMAT('DROP POLICY IF EXISTS "%s_admin_write" ON public.%I', t, t);
    EXECUTE FORMAT(
      'CREATE POLICY "%s_admin_write" ON public.%I FOR ALL TO authenticated
       USING (public.is_admin_or_moderator()) WITH CHECK (public.is_admin_or_moderator())',
      t, t
    );
  END LOOP;
END;
$$;

-- Quiz likes — owned by users
DROP POLICY IF EXISTS "quiz_likes_insert_own" ON public.quiz_likes;
CREATE POLICY "quiz_likes_insert_own" ON public.quiz_likes
  FOR INSERT TO authenticated
  WITH CHECK (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = quiz_likes.user_id AND p.auth_user_id = auth.uid()));

DROP POLICY IF EXISTS "quiz_likes_delete_own" ON public.quiz_likes;
CREATE POLICY "quiz_likes_delete_own" ON public.quiz_likes
  FOR DELETE TO authenticated
  USING (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = quiz_likes.user_id AND p.auth_user_id = auth.uid()));

-- Quiz comments — users manage own
DROP POLICY IF EXISTS "quiz_comments_insert_own" ON public.quiz_comments;
CREATE POLICY "quiz_comments_insert_own" ON public.quiz_comments
  FOR INSERT TO authenticated
  WITH CHECK (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = quiz_comments.author_id AND p.auth_user_id = auth.uid()));

DROP POLICY IF EXISTS "quiz_comments_update_own" ON public.quiz_comments;
CREATE POLICY "quiz_comments_update_own" ON public.quiz_comments
  FOR UPDATE TO authenticated
  USING (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = quiz_comments.author_id AND p.auth_user_id = auth.uid()))
  WITH CHECK (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = quiz_comments.author_id AND p.auth_user_id = auth.uid()));

DROP POLICY IF EXISTS "quiz_comments_delete_own_or_admin" ON public.quiz_comments;
CREATE POLICY "quiz_comments_delete_own_or_admin" ON public.quiz_comments
  FOR DELETE TO authenticated
  USING (
    public.is_admin_or_moderator()
    OR EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = quiz_comments.author_id AND p.auth_user_id = auth.uid())
  );

-- Passage likes / comments — same pattern
DROP POLICY IF EXISTS "passage_quiz_likes_insert_own" ON public.passage_quiz_likes;
CREATE POLICY "passage_quiz_likes_insert_own" ON public.passage_quiz_likes
  FOR INSERT TO authenticated
  WITH CHECK (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = passage_quiz_likes.user_id AND p.auth_user_id = auth.uid()));

DROP POLICY IF EXISTS "passage_quiz_likes_delete_own" ON public.passage_quiz_likes;
CREATE POLICY "passage_quiz_likes_delete_own" ON public.passage_quiz_likes
  FOR DELETE TO authenticated
  USING (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = passage_quiz_likes.user_id AND p.auth_user_id = auth.uid()));

DROP POLICY IF EXISTS "passage_quiz_comments_insert_own" ON public.passage_quiz_comments;
CREATE POLICY "passage_quiz_comments_insert_own" ON public.passage_quiz_comments
  FOR INSERT TO authenticated
  WITH CHECK (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = passage_quiz_comments.author_id AND p.auth_user_id = auth.uid()));

DROP POLICY IF EXISTS "passage_quiz_comments_update_own" ON public.passage_quiz_comments;
CREATE POLICY "passage_quiz_comments_update_own" ON public.passage_quiz_comments
  FOR UPDATE TO authenticated
  USING (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = passage_quiz_comments.author_id AND p.auth_user_id = auth.uid()))
  WITH CHECK (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = passage_quiz_comments.author_id AND p.auth_user_id = auth.uid()));

DROP POLICY IF EXISTS "passage_quiz_comments_delete_own_or_admin" ON public.passage_quiz_comments;
CREATE POLICY "passage_quiz_comments_delete_own_or_admin" ON public.passage_quiz_comments
  FOR DELETE TO authenticated
  USING (
    public.is_admin_or_moderator()
    OR EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = passage_quiz_comments.author_id AND p.auth_user_id = auth.uid())
  );
