-- =============================================================
-- MIGRATION 9: Mains Program Submissions & Mentorship
-- =============================================================

-- ---------------------------------------------------------------
-- MAINS TEST COPY SUBMISSIONS
-- Students submit answers; AI evaluates fully and automatically
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.mains_test_copy_submissions (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  series_id             BIGINT NOT NULL REFERENCES public.test_series(id) ON DELETE CASCADE,
  unit_step_id          BIGINT REFERENCES public.program_unit_steps(id) ON DELETE SET NULL,
  mains_question_id     BIGINT REFERENCES public.mains_questions(id) ON DELETE SET NULL,
  user_id               BIGINT NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,

  -- Student's answer
  answer_text           TEXT,
  answer_pdf_url        TEXT,
  learner_note          TEXT,
  word_count            INTEGER,

  -- Workflow status
  status                TEXT NOT NULL DEFAULT 'submitted'
    CHECK (status IN ('submitted', 'under_review', 'evaluated', 'returned')),

  -- AI Evaluation (auto-generated — evaluator_type = 'ai')
  evaluator_type        TEXT NOT NULL DEFAULT 'ai'
    CHECK (evaluator_type IN ('ai', 'human')),
  evaluator_id          BIGINT REFERENCES public.profiles(id) ON DELETE SET NULL,  -- NULL for AI
  evaluator_note        TEXT,

  -- AI-generated evaluation fields
  ai_score              NUMERIC(6,2),
  ai_max_score          NUMERIC(6,2),
  ai_feedback           TEXT,       -- Full evaluative paragraph
  ai_strengths          JSONB NOT NULL DEFAULT '[]'::JSONB,
  -- e.g. ["Good use of constitutional provisions", "Clear structure"]
  ai_weaknesses         JSONB NOT NULL DEFAULT '[]'::JSONB,
  -- e.g. ["Missed economic dimension", "No contemporary examples"]
  ai_structure_score    NUMERIC(4,2),   -- Presentation sub-score
  ai_content_score      NUMERIC(4,2),   -- Content/facts sub-score
  ai_evaluated_at       TIMESTAMPTZ,

  -- Legacy human evaluation support (for future hybrid mode)
  evaluation_text       TEXT,
  checked_copy_pdf_url  TEXT,
  total_marks           NUMERIC(8,2),
  max_marks             NUMERIC(8,2),

  submitted_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  evaluated_at          TIMESTAMPTZ,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CHECK (answer_text IS NOT NULL OR answer_pdf_url IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS idx_mains_subs_series   ON public.mains_test_copy_submissions(series_id);
CREATE INDEX IF NOT EXISTS idx_mains_subs_user     ON public.mains_test_copy_submissions(user_id);
CREATE INDEX IF NOT EXISTS idx_mains_subs_status   ON public.mains_test_copy_submissions(status);
CREATE INDEX IF NOT EXISTS idx_mains_subs_question ON public.mains_test_copy_submissions(mains_question_id);

DROP TRIGGER IF EXISTS trg_mains_subs_set_updated_at ON public.mains_test_copy_submissions;
CREATE TRIGGER trg_mains_subs_set_updated_at
  BEFORE UPDATE ON public.mains_test_copy_submissions
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ---------------------------------------------------------------
-- MAINS PROGRAM MENTORSHIP REQUESTS
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.mains_program_mentorship_requests (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  series_id      BIGINT NOT NULL REFERENCES public.test_series(id) ON DELETE CASCADE,
  submission_id  BIGINT REFERENCES public.mains_test_copy_submissions(id) ON DELETE SET NULL,
  user_id        BIGINT NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  mentor_id      BIGINT REFERENCES public.profiles(id) ON DELETE SET NULL,
  preferred_mode TEXT NOT NULL DEFAULT 'video'
    CHECK (preferred_mode IN ('video', 'chat', 'call')),
  learner_note   TEXT,
  status         TEXT NOT NULL DEFAULT 'requested'
    CHECK (status IN ('requested', 'scheduled', 'completed', 'cancelled')),
  scheduled_for  TIMESTAMPTZ,
  meeting_link   TEXT,
  mentor_note    TEXT,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_mains_mentor_req_series ON public.mains_program_mentorship_requests(series_id);
CREATE INDEX IF NOT EXISTS idx_mains_mentor_req_user   ON public.mains_program_mentorship_requests(user_id);
CREATE INDEX IF NOT EXISTS idx_mains_mentor_req_status ON public.mains_program_mentorship_requests(status);

DROP TRIGGER IF EXISTS trg_mains_mentorship_set_updated_at ON public.mains_program_mentorship_requests;
CREATE TRIGGER trg_mains_mentorship_set_updated_at
  BEFORE UPDATE ON public.mains_program_mentorship_requests
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ---------------------------------------------------------------
-- ROW LEVEL SECURITY
-- ---------------------------------------------------------------

ALTER TABLE public.mains_test_copy_submissions       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mains_program_mentorship_requests ENABLE ROW LEVEL SECURITY;

-- Submissions: own user + series creator + admin
DROP POLICY IF EXISTS "mains_subs_read" ON public.mains_test_copy_submissions;
CREATE POLICY "mains_subs_read" ON public.mains_test_copy_submissions
  FOR SELECT TO authenticated
  USING (
    public.is_admin_or_moderator()
    OR EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = mains_test_copy_submissions.user_id AND p.auth_user_id = auth.uid())
    OR EXISTS (SELECT 1 FROM public.test_series ts JOIN public.profiles p ON p.id = ts.creator_id WHERE ts.id = mains_test_copy_submissions.series_id AND p.auth_user_id = auth.uid())
  );

DROP POLICY IF EXISTS "mains_subs_user_insert" ON public.mains_test_copy_submissions;
CREATE POLICY "mains_subs_user_insert" ON public.mains_test_copy_submissions
  FOR INSERT TO authenticated
  WITH CHECK (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = mains_test_copy_submissions.user_id AND p.auth_user_id = auth.uid()));

DROP POLICY IF EXISTS "mains_subs_admin_update" ON public.mains_test_copy_submissions;
CREATE POLICY "mains_subs_admin_update" ON public.mains_test_copy_submissions
  FOR UPDATE TO authenticated
  USING (
    public.is_admin_or_moderator()
    OR EXISTS (SELECT 1 FROM public.test_series ts JOIN public.profiles p ON p.id = ts.creator_id WHERE ts.id = mains_test_copy_submissions.series_id AND p.auth_user_id = auth.uid())
  )
  WITH CHECK (
    public.is_admin_or_moderator()
    OR EXISTS (SELECT 1 FROM public.test_series ts JOIN public.profiles p ON p.id = ts.creator_id WHERE ts.id = mains_test_copy_submissions.series_id AND p.auth_user_id = auth.uid())
  );

-- Mentorship: own user + assigned mentor + admin
DROP POLICY IF EXISTS "mains_mentorship_read" ON public.mains_program_mentorship_requests;
CREATE POLICY "mains_mentorship_read" ON public.mains_program_mentorship_requests
  FOR SELECT TO authenticated
  USING (
    public.is_admin_or_moderator()
    OR EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = mains_program_mentorship_requests.user_id AND p.auth_user_id = auth.uid())
    OR EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = mains_program_mentorship_requests.mentor_id AND p.auth_user_id = auth.uid())
  );

DROP POLICY IF EXISTS "mains_mentorship_user_insert" ON public.mains_program_mentorship_requests;
CREATE POLICY "mains_mentorship_user_insert" ON public.mains_program_mentorship_requests
  FOR INSERT TO authenticated
  WITH CHECK (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = mains_program_mentorship_requests.user_id AND p.auth_user_id = auth.uid()));

DROP POLICY IF EXISTS "mains_mentorship_mentor_or_admin_update" ON public.mains_program_mentorship_requests;
CREATE POLICY "mains_mentorship_mentor_or_admin_update" ON public.mains_program_mentorship_requests
  FOR UPDATE TO authenticated
  USING (
    public.is_admin_or_moderator()
    OR EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = mains_program_mentorship_requests.mentor_id AND p.auth_user_id = auth.uid())
  )
  WITH CHECK (
    public.is_admin_or_moderator()
    OR EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = mains_program_mentorship_requests.mentor_id AND p.auth_user_id = auth.uid())
  );
