-- =============================================================
-- MIGRATION 2: Taxonomy — Exams, Categories, Sources, Subjects
-- =============================================================

-- ---------------------------------------------------------------
-- EXAMS (top-level filter for Test Series and Mentors only)
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.exams (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT NOT NULL UNIQUE,
  slug        TEXT NOT NULL UNIQUE,
  exam_type   TEXT NOT NULL DEFAULT 'combined'
    CHECK (exam_type IN ('combined', 'prelims_only', 'mains_only', 'other')),
  description TEXT,
  logo_url    TEXT,
  is_active   BOOLEAN     NOT NULL DEFAULT TRUE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

DROP TRIGGER IF EXISTS trg_exams_set_updated_at ON public.exams;
CREATE TRIGGER trg_exams_set_updated_at
  BEFORE UPDATE ON public.exams
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ---------------------------------------------------------------
-- UNIFIED CATEGORIES
-- domain = which content system this tree belongs to
-- No exam references here — exams filter at the series level only
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.categories (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          TEXT NOT NULL,
  slug          TEXT UNIQUE,
  parent_id     BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
  domain        TEXT NOT NULL
    CHECK (domain IN ('gk', 'maths', 'passage', 'mains', 'article')),
  description   TEXT,
  is_active     BOOLEAN     NOT NULL DEFAULT TRUE,
  display_order INTEGER     NOT NULL DEFAULT 0,
  -- Denormalized counters (updated by triggers or background jobs)
  question_count        INTEGER NOT NULL DEFAULT 0,
  total_question_count  INTEGER NOT NULL DEFAULT 0,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_categories_parent_id   ON public.categories(parent_id);
CREATE INDEX IF NOT EXISTS idx_categories_domain       ON public.categories(domain);
CREATE INDEX IF NOT EXISTS idx_categories_parent_domain ON public.categories(parent_id, domain);

DROP TRIGGER IF EXISTS trg_categories_set_updated_at ON public.categories;
CREATE TRIGGER trg_categories_set_updated_at
  BEFORE UPDATE ON public.categories
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ---------------------------------------------------------------
-- ALPHA CATEGORIES (batch/cohort-level tagging — not content taxonomy)
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.alpha_categories (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT        NOT NULL,
  slug        TEXT        NOT NULL UNIQUE,
  description TEXT,
  is_active   BOOLEAN     NOT NULL DEFAULT TRUE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

DROP TRIGGER IF EXISTS trg_alpha_categories_set_updated_at ON public.alpha_categories;
CREATE TRIGGER trg_alpha_categories_set_updated_at
  BEFORE UPDATE ON public.alpha_categories
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ---------------------------------------------------------------
-- FREE EXAMS (public-facing entry pages — not the main exam system)
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.free_exams (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT        NOT NULL,
  slug        TEXT        NOT NULL UNIQUE,
  description TEXT,
  image_url   TEXT,
  scope       TEXT        NOT NULL DEFAULT 'gk'
    CHECK (scope IN ('gk', 'maths', 'passage')),
  is_active   BOOLEAN     NOT NULL DEFAULT TRUE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

DROP TRIGGER IF EXISTS trg_free_exams_set_updated_at ON public.free_exams;
CREATE TRIGGER trg_free_exams_set_updated_at
  BEFORE UPDATE ON public.free_exams
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ---------------------------------------------------------------
-- SOURCES (newspapers, govt portals, magazines — for article metadata)
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.sources (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          TEXT NOT NULL UNIQUE,
  slug          TEXT NOT NULL UNIQUE,
  abbreviation  TEXT,
  website_url   TEXT,
  logo_url      TEXT,
  source_type   TEXT NOT NULL DEFAULT 'newspaper'
    CHECK (source_type IN ('newspaper', 'government', 'magazine', 'website', 'other')),
  is_active     BOOLEAN     NOT NULL DEFAULT TRUE,
  display_order INTEGER,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO public.sources (name, slug, abbreviation, source_type) VALUES
  ('The Hindu',           'the-hindu',        'TH',  'newspaper'),
  ('Press Information Bureau', 'pib',         'PIB', 'government'),
  ('Indian Express',      'indian-express',    'IE',  'newspaper'),
  ('Livemint',            'livemint',          'LM',  'newspaper'),
  ('Business Standard',   'business-standard', 'BS',  'newspaper'),
  ('Down to Earth',       'down-to-earth',     'DTE', 'magazine'),
  ('Economic Times',      'economic-times',    'ET',  'newspaper'),
  ('Hindustan Times',     'hindustan-times',   'HT',  'newspaper')
ON CONFLICT (slug) DO NOTHING;

-- ---------------------------------------------------------------
-- SUBJECTS → TOPICS → SUBTOPICS
-- Three-level hierarchy used by the study material system
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.subjects (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          TEXT        NOT NULL,
  slug          TEXT        NOT NULL UNIQUE,
  description   TEXT,
  display_order INTEGER,
  is_active     BOOLEAN NOT NULL DEFAULT TRUE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

DROP TRIGGER IF EXISTS trg_subjects_set_updated_at ON public.subjects;
CREATE TRIGGER trg_subjects_set_updated_at
  BEFORE UPDATE ON public.subjects
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE IF NOT EXISTS public.topics (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject_id    BIGINT      NOT NULL REFERENCES public.subjects(id) ON DELETE CASCADE,
  name          TEXT        NOT NULL,
  slug          TEXT        NOT NULL,
  description   TEXT,
  has_prelims   BOOLEAN NOT NULL DEFAULT FALSE,
  has_mains     BOOLEAN NOT NULL DEFAULT FALSE,
  display_order INTEGER,
  is_active     BOOLEAN NOT NULL DEFAULT TRUE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (subject_id, slug)
);

CREATE INDEX IF NOT EXISTS idx_topics_subject_id ON public.topics(subject_id);

DROP TRIGGER IF EXISTS trg_topics_set_updated_at ON public.topics;
CREATE TRIGGER trg_topics_set_updated_at
  BEFORE UPDATE ON public.topics
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE IF NOT EXISTS public.subtopics (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  topic_id      BIGINT      NOT NULL REFERENCES public.topics(id) ON DELETE CASCADE,
  name          TEXT        NOT NULL,
  slug          TEXT        NOT NULL,
  description   TEXT,
  has_prelims   BOOLEAN NOT NULL DEFAULT FALSE,
  has_mains     BOOLEAN NOT NULL DEFAULT FALSE,
  display_order INTEGER,
  is_active     BOOLEAN NOT NULL DEFAULT TRUE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (topic_id, slug)
);

CREATE INDEX IF NOT EXISTS idx_subtopics_topic_id ON public.subtopics(topic_id);

DROP TRIGGER IF EXISTS trg_subtopics_set_updated_at ON public.subtopics;
CREATE TRIGGER trg_subtopics_set_updated_at
  BEFORE UPDATE ON public.subtopics
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ---------------------------------------------------------------
-- TAGS (general-purpose content tags)
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.tags (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       TEXT NOT NULL UNIQUE,
  slug       TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------
-- ROW LEVEL SECURITY — All taxonomy tables are public-read, admin-write
-- ---------------------------------------------------------------

ALTER TABLE public.exams           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.alpha_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.free_exams      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sources         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subjects        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.topics          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subtopics       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tags            ENABLE ROW LEVEL SECURITY;

DO $$
DECLARE
  tbls TEXT[] := ARRAY['exams','categories','alpha_categories','free_exams',
                        'sources','subjects','topics','subtopics','tags'];
  t TEXT;
BEGIN
  FOREACH t IN ARRAY tbls LOOP
    EXECUTE FORMAT('DROP POLICY IF EXISTS "%s_public_read" ON public.%I', t, t);
    EXECUTE FORMAT(
      'CREATE POLICY "%s_public_read" ON public.%I FOR SELECT TO anon, authenticated USING (TRUE)',
      t, t
    );
    EXECUTE FORMAT('DROP POLICY IF EXISTS "%s_admin_write" ON public.%I', t, t);
    EXECUTE FORMAT(
      'CREATE POLICY "%s_admin_write" ON public.%I FOR ALL TO authenticated
       USING (public.is_admin_or_moderator()) WITH CHECK (public.is_admin_or_moderator())',
      t, t
    );
  END LOOP;
END;
$$;
