-- =============================================================
-- MIGRATION 1: Extensions, Utility Functions & Profiles
-- =============================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS ltree;

-- ---------------------------------------------------------------
-- UTILITY FUNCTIONS
-- ---------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER LANGUAGE PLPGSQL AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.generate_profile_username(
  input_email         TEXT,
  input_auth_user_id  UUID
)
RETURNS TEXT LANGUAGE SQL STABLE AS $$
  SELECT LEFT(
    REGEXP_REPLACE(
      SPLIT_PART(COALESCE(input_email, 'user@example.com'), '@', 1),
      '[^a-zA-Z0-9_]+', '_', 'g'
    ) || '_' || REPLACE(LEFT(input_auth_user_id::TEXT, 8), '-', ''),
    50
  );
$$;

-- ---------------------------------------------------------------
-- PROFILES
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.profiles (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  auth_user_id          UUID   NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  email                 TEXT   NOT NULL UNIQUE,
  username              TEXT   NOT NULL UNIQUE,
  display_name          TEXT,
  avatar_url            TEXT,
  bio                   TEXT,
  is_active             BOOLEAN     NOT NULL DEFAULT TRUE,
  role                  TEXT        NOT NULL DEFAULT 'user'
    CHECK (role IN ('admin', 'moderator', 'prelims_expert', 'mains_expert', 'user')),
  is_verified           BOOLEAN     NOT NULL DEFAULT FALSE,
  leaderboard_username  TEXT UNIQUE,
  -- Creator-specific
  creator_exam_ids      BIGINT[]    NOT NULL DEFAULT '{}',
  highlights            JSONB       NOT NULL DEFAULT '{}'::JSONB,
  payout_details        JSONB       NOT NULL DEFAULT '{}'::JSONB,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_profiles_auth_user_id ON public.profiles(auth_user_id);
CREATE INDEX IF NOT EXISTS idx_profiles_role        ON public.profiles(role);

DROP TRIGGER IF EXISTS trg_profiles_set_updated_at ON public.profiles;
CREATE TRIGGER trg_profiles_set_updated_at
  BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ---------------------------------------------------------------
-- AUTH TRIGGER — auto-create profile on new user signup
-- ---------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.handle_new_auth_user()
RETURNS TRIGGER LANGUAGE PLPGSQL SECURITY DEFINER SET search_path = public AS $$
BEGIN
  INSERT INTO public.profiles (auth_user_id, email, username, is_active, role, is_verified)
  VALUES (
    NEW.id,
    COALESCE(NEW.email, NEW.id::TEXT || '@example.local'),
    COALESCE(
      NULLIF(NEW.raw_user_meta_data->>'username', ''),
      public.generate_profile_username(
        COALESCE(NEW.email, NEW.id::TEXT || '@example.local'), NEW.id
      )
    ),
    TRUE,
    CASE
      WHEN NEW.raw_app_meta_data->>'role' IN ('admin','moderator','prelims_expert','mains_expert','user')
        THEN NEW.raw_app_meta_data->>'role'
      ELSE 'user'
    END,
    NEW.email_confirmed_at IS NOT NULL
  )
  ON CONFLICT (auth_user_id) DO NOTHING;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_auth_user();

-- ---------------------------------------------------------------
-- ROLE HELPER FUNCTIONS (used in RLS policies throughout)
-- ---------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.is_admin_or_moderator()
RETURNS BOOLEAN LANGUAGE SQL STABLE AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles p
    WHERE p.auth_user_id = auth.uid()
      AND p.role IN ('admin', 'moderator')
  );
$$;

CREATE OR REPLACE FUNCTION public.is_creator()
RETURNS BOOLEAN LANGUAGE SQL STABLE AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles p
    WHERE p.auth_user_id = auth.uid()
      AND p.role IN ('admin', 'moderator', 'prelims_expert', 'mains_expert')
  );
$$;

CREATE OR REPLACE FUNCTION public.is_prelims_expert()
RETURNS BOOLEAN LANGUAGE SQL STABLE AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles p
    WHERE p.auth_user_id = auth.uid()
      AND p.role IN ('admin', 'prelims_expert')
  );
$$;

CREATE OR REPLACE FUNCTION public.is_mains_expert()
RETURNS BOOLEAN LANGUAGE SQL STABLE AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles p
    WHERE p.auth_user_id = auth.uid()
      AND p.role IN ('admin', 'mains_expert')
  );
$$;

-- ---------------------------------------------------------------
-- ROW LEVEL SECURITY — Profiles
-- ---------------------------------------------------------------

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "profiles_public_read"  ON public.profiles;
CREATE POLICY "profiles_public_read" ON public.profiles
  FOR SELECT TO anon, authenticated USING (TRUE);

DROP POLICY IF EXISTS "profiles_update_own" ON public.profiles;
CREATE POLICY "profiles_update_own" ON public.profiles
  FOR UPDATE TO authenticated
  USING (auth.uid() = auth_user_id)
  WITH CHECK (auth.uid() = auth_user_id);

DROP POLICY IF EXISTS "profiles_admin_all" ON public.profiles;
CREATE POLICY "profiles_admin_all" ON public.profiles
  FOR ALL TO authenticated
  USING (public.is_admin_or_moderator())
  WITH CHECK (public.is_admin_or_moderator());
