-- =============================================================
-- MIGRATION 8: Live Rooms (Agora)
-- =============================================================

CREATE TABLE IF NOT EXISTS public.live_rooms (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  series_id           BIGINT REFERENCES public.test_series(id) ON DELETE CASCADE,
  unit_step_id        BIGINT REFERENCES public.program_unit_steps(id) ON DELETE SET NULL,
  title               TEXT   NOT NULL,
  description         TEXT,
  agora_channel_name  TEXT   NOT NULL UNIQUE,
  host_uid            TEXT,  -- Agora UID for the host (creator)
  status              TEXT   NOT NULL DEFAULT 'scheduled'
    CHECK (status IN ('scheduled', 'live', 'ended', 'cancelled')),
  scheduled_for       TIMESTAMPTZ,
  started_at          TIMESTAMPTZ,
  ended_at            TIMESTAMPTZ,
  recording_url       TEXT,
  max_participants    INTEGER DEFAULT 500,
  created_by          BIGINT NOT NULL REFERENCES public.profiles(id) ON DELETE RESTRICT,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_live_rooms_series    ON public.live_rooms(series_id);
CREATE INDEX IF NOT EXISTS idx_live_rooms_status    ON public.live_rooms(status);
CREATE INDEX IF NOT EXISTS idx_live_rooms_scheduled ON public.live_rooms(scheduled_for);

DROP TRIGGER IF EXISTS trg_live_rooms_set_updated_at ON public.live_rooms;
CREATE TRIGGER trg_live_rooms_set_updated_at
  BEFORE UPDATE ON public.live_rooms
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- Back-fill the FK from program_unit_steps to live_rooms
-- (Added here rather than migration 7 to respect dependency order)
ALTER TABLE public.program_unit_steps
  ADD CONSTRAINT fk_unit_steps_live_room
  FOREIGN KEY (live_room_id) REFERENCES public.live_rooms(id) ON DELETE SET NULL;

-- ---------------------------------------------------------------
-- LIVE ROOM INTERACTIONS (chat, raise hand, reactions)
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.live_room_interactions (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id     BIGINT NOT NULL REFERENCES public.live_rooms(id) ON DELETE CASCADE,
  user_id     BIGINT REFERENCES public.profiles(id) ON DELETE SET NULL,
  event_type  TEXT   NOT NULL
    CHECK (event_type IN ('chat', 'raise_hand', 'speaker_request', 'reaction', 'system')),
  payload     JSONB  NOT NULL DEFAULT '{}'::JSONB,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_live_interactions_room    ON public.live_room_interactions(room_id);
CREATE INDEX IF NOT EXISTS idx_live_interactions_user    ON public.live_room_interactions(user_id);
CREATE INDEX IF NOT EXISTS idx_live_interactions_created ON public.live_room_interactions(created_at DESC);

-- ---------------------------------------------------------------
-- ROW LEVEL SECURITY
-- ---------------------------------------------------------------

ALTER TABLE public.live_rooms             ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.live_room_interactions ENABLE ROW LEVEL SECURITY;

-- Live rooms: enrolled/access-eligible users can view
DROP POLICY IF EXISTS "live_rooms_access_read" ON public.live_rooms;
CREATE POLICY "live_rooms_access_read" ON public.live_rooms
  FOR SELECT TO anon, authenticated
  USING (
    public.is_admin_or_moderator()
    OR status = 'live'
    OR (series_id IS NOT NULL AND public.can_access_test_series(series_id))
    OR EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = live_rooms.created_by AND p.auth_user_id = auth.uid())
  );

-- Only host (creator) or admin can update room
DROP POLICY IF EXISTS "live_rooms_creator_or_admin_write" ON public.live_rooms;
CREATE POLICY "live_rooms_creator_or_admin_write" ON public.live_rooms FOR ALL TO authenticated
  USING (
    public.is_admin_or_moderator()
    OR EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = live_rooms.created_by AND p.auth_user_id = auth.uid())
  )
  WITH CHECK (
    public.is_admin_or_moderator()
    OR EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = live_rooms.created_by AND p.auth_user_id = auth.uid())
  );

-- Interactions: all authenticated can read in accessible rooms, insert own
DROP POLICY IF EXISTS "live_interactions_read" ON public.live_room_interactions;
CREATE POLICY "live_interactions_read" ON public.live_room_interactions
  FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1 FROM public.live_rooms r WHERE r.id = live_room_interactions.room_id AND public.can_access_test_series(r.series_id)));

DROP POLICY IF EXISTS "live_interactions_insert" ON public.live_room_interactions;
CREATE POLICY "live_interactions_insert" ON public.live_room_interactions
  FOR INSERT TO authenticated
  WITH CHECK (auth.uid() IS NOT NULL);
