-- =============================================================
-- MIGRATION 13: Missing Components from Old supa_back
-- Covers: Creator profiles, mentorship system, challenge links,
--         AI sources per category, user mains evaluations,
--         AI quiz hints, quiz question complaints, per-question marks,
--         discussion speaker requests, mentorship messages,
--         Realtime publication setup
-- =============================================================

-- ---------------------------------------------------------------
-- CREATOR / MENTOR PROFILES
-- Extended public profile for users with creator roles.
-- Separate from auth profiles — stores professional details.
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.creator_profiles (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id             BIGINT NOT NULL UNIQUE REFERENCES public.profiles(id) ON DELETE CASCADE,
  display_name        TEXT   NOT NULL,
  headline            TEXT,
  bio                 TEXT,
  years_experience    INTEGER,
  city                TEXT,
  profile_image_url   TEXT,
  is_verified         BOOLEAN NOT NULL DEFAULT FALSE,
  is_public           BOOLEAN NOT NULL DEFAULT TRUE,
  is_active           BOOLEAN NOT NULL DEFAULT TRUE,
  -- Professional credentials / highlights
  highlights          JSONB NOT NULL DEFAULT '[]'::JSONB,
  -- e.g. [{"label": "IAS 2021 Topper", "icon": "trophy"}]
  credentials         JSONB NOT NULL DEFAULT '[]'::JSONB,
  specialization_tags JSONB NOT NULL DEFAULT '[]'::JSONB,
  languages           JSONB NOT NULL DEFAULT '[]'::JSONB,
  social_links        JSONB NOT NULL DEFAULT '{}'::JSONB,
  contact_url         TEXT,
  public_email        TEXT,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_creator_profiles_user     ON public.creator_profiles(user_id);
CREATE INDEX IF NOT EXISTS idx_creator_profiles_public   ON public.creator_profiles(is_public, is_active);
CREATE INDEX IF NOT EXISTS idx_creator_profiles_verified ON public.creator_profiles(is_verified);

DROP TRIGGER IF EXISTS trg_creator_profiles_set_updated_at ON public.creator_profiles;
CREATE TRIGGER trg_creator_profiles_set_updated_at
  BEFORE UPDATE ON public.creator_profiles
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- Creator Profile → Exam filter (which exams this mentor covers)
CREATE TABLE IF NOT EXISTS public.creator_profile_exams (
  creator_profile_id BIGINT NOT NULL REFERENCES public.creator_profiles(id) ON DELETE CASCADE,
  exam_id            BIGINT NOT NULL REFERENCES public.exams(id) ON DELETE CASCADE,
  PRIMARY KEY (creator_profile_id, exam_id)
);

-- Professional profile reviews (by users)
CREATE TABLE IF NOT EXISTS public.creator_profile_reviews (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  creator_profile_id BIGINT NOT NULL REFERENCES public.creator_profiles(id) ON DELETE CASCADE,
  reviewer_id        BIGINT NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  rating             INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
  comment            TEXT,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (creator_profile_id, reviewer_id)
);

DROP TRIGGER IF EXISTS trg_creator_profile_reviews_updated_at ON public.creator_profile_reviews;
CREATE TRIGGER trg_creator_profile_reviews_updated_at
  BEFORE UPDATE ON public.creator_profile_reviews
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ---------------------------------------------------------------
-- MENTORSHIP SYSTEM (Standalone mentorship — not tied to a program)
-- ---------------------------------------------------------------

-- Entitlements: how many sessions a user is allowed
CREATE TABLE IF NOT EXISTS public.mentorship_entitlements (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id           BIGINT NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  sessions_remaining INTEGER NOT NULL DEFAULT 0,
  valid_until       TIMESTAMPTZ,
  source            TEXT NOT NULL DEFAULT 'payment'
    CHECK (source IN ('payment', 'subscription', 'admin_grant')),
  note              TEXT,
  is_active         BOOLEAN NOT NULL DEFAULT TRUE,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_mentorship_entitlements_user    ON public.mentorship_entitlements(user_id);
CREATE INDEX IF NOT EXISTS idx_mentorship_entitlements_active  ON public.mentorship_entitlements(user_id, is_active);

DROP TRIGGER IF EXISTS trg_mentorship_entitlements_updated_at ON public.mentorship_entitlements;
CREATE TRIGGER trg_mentorship_entitlements_updated_at
  BEFORE UPDATE ON public.mentorship_entitlements
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- Slots: time windows a mentor makes available
CREATE TABLE IF NOT EXISTS public.mentorship_slots (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mentor_id       BIGINT NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  starts_at       TIMESTAMPTZ NOT NULL,
  ends_at         TIMESTAMPTZ NOT NULL,
  mode            TEXT NOT NULL DEFAULT 'video' CHECK (mode IN ('video', 'chat', 'call')),
  max_bookings    INTEGER NOT NULL DEFAULT 1,
  booked_count    INTEGER NOT NULL DEFAULT 0,
  is_active       BOOLEAN NOT NULL DEFAULT TRUE,
  meeting_link    TEXT,
  title           TEXT,
  description     TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_mentorship_slots_mentor ON public.mentorship_slots(mentor_id);
CREATE INDEX IF NOT EXISTS idx_mentorship_slots_time   ON public.mentorship_slots(starts_at, ends_at);
CREATE INDEX IF NOT EXISTS idx_mentorship_slots_active ON public.mentorship_slots(is_active);

DROP TRIGGER IF EXISTS trg_mentorship_slots_updated_at ON public.mentorship_slots;
CREATE TRIGGER trg_mentorship_slots_updated_at
  BEFORE UPDATE ON public.mentorship_slots
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- Requests: a user books a mentorship session
CREATE TABLE IF NOT EXISTS public.mentorship_requests (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         BIGINT NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  mentor_id       BIGINT NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  series_id       BIGINT REFERENCES public.test_series(id) ON DELETE SET NULL,
  preferred_mode  TEXT NOT NULL DEFAULT 'video' CHECK (preferred_mode IN ('video', 'chat', 'call')),
  note            TEXT,
  status          TEXT NOT NULL DEFAULT 'requested'
    CHECK (status IN ('requested', 'scheduled', 'completed', 'cancelled', 'rejected')),
  scheduled_slot_id BIGINT REFERENCES public.mentorship_slots(id) ON DELETE SET NULL,
  requested_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_mentorship_requests_user   ON public.mentorship_requests(user_id);
CREATE INDEX IF NOT EXISTS idx_mentorship_requests_mentor ON public.mentorship_requests(mentor_id);
CREATE INDEX IF NOT EXISTS idx_mentorship_requests_status ON public.mentorship_requests(status);

DROP TRIGGER IF EXISTS trg_mentorship_requests_updated_at ON public.mentorship_requests;
CREATE TRIGGER trg_mentorship_requests_updated_at
  BEFORE UPDATE ON public.mentorship_requests
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- Sessions: confirmed and scheduled
CREATE TABLE IF NOT EXISTS public.mentorship_sessions (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id  BIGINT NOT NULL UNIQUE REFERENCES public.mentorship_requests(id) ON DELETE CASCADE,
  slot_id     BIGINT REFERENCES public.mentorship_slots(id) ON DELETE SET NULL,
  mentor_id   BIGINT NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  user_id     BIGINT NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  mode        TEXT NOT NULL DEFAULT 'video',
  starts_at   TIMESTAMPTZ NOT NULL,
  ends_at     TIMESTAMPTZ NOT NULL,
  meeting_link TEXT,
  copy_attachment_url TEXT,
  summary     TEXT,
  status      TEXT NOT NULL DEFAULT 'scheduled'
    CHECK (status IN ('scheduled', 'completed', 'cancelled', 'no_show')),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_mentorship_sessions_mentor ON public.mentorship_sessions(mentor_id);
CREATE INDEX IF NOT EXISTS idx_mentorship_sessions_user   ON public.mentorship_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_mentorship_sessions_status ON public.mentorship_sessions(status);

DROP TRIGGER IF EXISTS trg_mentorship_sessions_updated_at ON public.mentorship_sessions;
CREATE TRIGGER trg_mentorship_sessions_updated_at
  BEFORE UPDATE ON public.mentorship_sessions
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- Messages within a mentorship request
CREATE TABLE IF NOT EXISTS public.mentorship_messages (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id      BIGINT NOT NULL REFERENCES public.mentorship_requests(id) ON DELETE CASCADE,
  sender_id       BIGINT NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  body            TEXT   NOT NULL,
  is_read         BOOLEAN NOT NULL DEFAULT FALSE,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_mentorship_messages_request ON public.mentorship_messages(request_id);
CREATE INDEX IF NOT EXISTS idx_mentorship_messages_sender  ON public.mentorship_messages(sender_id);

-- ---------------------------------------------------------------
-- MAINS TEST COPY MARKS (per-question marks on submissions)
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.mains_test_copy_marks (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  submission_id   BIGINT NOT NULL REFERENCES public.mains_test_copy_submissions(id) ON DELETE CASCADE,
  mains_question_id BIGINT REFERENCES public.mains_questions(id) ON DELETE SET NULL,
  question_number INTEGER,
  question_text   TEXT,
  marks_awarded   NUMERIC(8,2) NOT NULL,
  max_marks       NUMERIC(8,2) NOT NULL DEFAULT 10.0,
  remark          TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_mains_copy_marks_submission ON public.mains_test_copy_marks(submission_id);

DROP TRIGGER IF EXISTS trg_mains_copy_marks_updated_at ON public.mains_test_copy_marks;
CREATE TRIGGER trg_mains_copy_marks_updated_at
  BEFORE UPDATE ON public.mains_test_copy_marks
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ---------------------------------------------------------------
-- USER MAINS EVALUATIONS (AI-evaluated free-form answer practice)
-- Not tied to a program — standalone AI evaluation tool
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.user_mains_evaluations (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id          BIGINT NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  question_id      BIGINT REFERENCES public.ai_mains_questions(id) ON DELETE SET NULL,
  question_text    TEXT   NOT NULL,
  answer_text      TEXT   NOT NULL,
  word_count       INTEGER,
  -- AI Evaluation (mirrors mains_test_copy_submissions eval fields)
  ai_score         NUMERIC(4,2),
  ai_max_score     NUMERIC(4,2) NOT NULL DEFAULT 10,
  ai_feedback      TEXT,
  ai_strengths     JSONB NOT NULL DEFAULT '[]'::JSONB,
  ai_weaknesses    JSONB NOT NULL DEFAULT '[]'::JSONB,
  ai_structure_score NUMERIC(4,2),
  ai_content_score   NUMERIC(4,2),
  improved_answer  TEXT,
  category_id      BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_user_mains_eval_user     ON public.user_mains_evaluations(user_id);
CREATE INDEX IF NOT EXISTS idx_user_mains_eval_question ON public.user_mains_evaluations(question_id);
CREATE INDEX IF NOT EXISTS idx_user_mains_eval_category ON public.user_mains_evaluations(category_id);

-- ---------------------------------------------------------------
-- AI SOURCES PER CATEGORY (curated text/URL sources for AI generation)
-- In new schema: unified — one table serves both GK/Maths/Passage + Mains categories
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.category_ai_sources (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_kind          TEXT   NOT NULL CHECK (source_kind IN ('text', 'url', 'pdf')),
  title                TEXT,
  source_url           TEXT,
  source_text          TEXT,
  source_content_html  TEXT,
  source_pdf_id        BIGINT REFERENCES public.uploaded_pdfs(id) ON DELETE SET NULL,
  priority             INTEGER NOT NULL DEFAULT 0,
  is_active            BOOLEAN NOT NULL DEFAULT TRUE,
  created_by           BIGINT REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_category_ai_sources_active ON public.category_ai_sources(is_active, priority DESC);

DROP TRIGGER IF EXISTS trg_category_ai_sources_updated_at ON public.category_ai_sources;
CREATE TRIGGER trg_category_ai_sources_updated_at
  BEFORE UPDATE ON public.category_ai_sources
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- Many-to-many: one AI source can serve multiple categories
CREATE TABLE IF NOT EXISTS public.category_ai_source_categories (
  source_id   BIGINT NOT NULL REFERENCES public.category_ai_sources(id) ON DELETE CASCADE,
  category_id BIGINT NOT NULL REFERENCES public.categories(id) ON DELETE CASCADE,
  PRIMARY KEY (source_id, category_id)
);

CREATE INDEX IF NOT EXISTS idx_ai_source_categories_category ON public.category_ai_source_categories(category_id);

-- ---------------------------------------------------------------
-- USER AI QUIZ HINTS (hint history per user per domain)
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.user_ai_quiz_hints (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id           BIGINT NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  quiz_domain       TEXT   NOT NULL CHECK (quiz_domain IN ('gk', 'maths', 'passage', 'mains')),
  hints             JSONB  NOT NULL DEFAULT '[]'::JSONB,
  recent_questions  JSONB  NOT NULL DEFAULT '[]'::JSONB,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (user_id, quiz_domain)
);

CREATE INDEX IF NOT EXISTS idx_user_ai_quiz_hints_user ON public.user_ai_quiz_hints(user_id);

DROP TRIGGER IF EXISTS trg_user_ai_quiz_hints_updated_at ON public.user_ai_quiz_hints;
CREATE TRIGGER trg_user_ai_quiz_hints_updated_at
  BEFORE UPDATE ON public.user_ai_quiz_hints
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ---------------------------------------------------------------
-- COLLECTION CHALLENGE LINKS (shareable test challenge links)
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.collection_challenge_links (
  id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  premium_collection_id     BIGINT NOT NULL REFERENCES public.premium_collections(id) ON DELETE CASCADE,
  owner_user_id             BIGINT NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  token_hash                TEXT   NOT NULL UNIQUE,
  title                     TEXT   NOT NULL,
  description               TEXT,
  is_active                 BOOLEAN NOT NULL DEFAULT TRUE,
  allow_anonymous           BOOLEAN NOT NULL DEFAULT TRUE,
  require_login             BOOLEAN NOT NULL DEFAULT FALSE,
  max_attempts_per_participant INTEGER NOT NULL DEFAULT 3,
  total_attempts            INTEGER NOT NULL DEFAULT 0,
  expires_at                TIMESTAMPTZ,
  created_at                TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at                TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_challenge_links_collection ON public.collection_challenge_links(premium_collection_id);
CREATE INDEX IF NOT EXISTS idx_challenge_links_owner      ON public.collection_challenge_links(owner_user_id);
CREATE INDEX IF NOT EXISTS idx_challenge_links_expires    ON public.collection_challenge_links(expires_at);

DROP TRIGGER IF EXISTS trg_collection_challenge_links_updated_at ON public.collection_challenge_links;
CREATE TRIGGER trg_collection_challenge_links_updated_at
  BEFORE UPDATE ON public.collection_challenge_links
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- Challenge Attempts (participants' results on challenge link)
CREATE TABLE IF NOT EXISTS public.collection_challenge_attempts (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  challenge_id          BIGINT NOT NULL REFERENCES public.collection_challenge_links(id) ON DELETE CASCADE,
  premium_collection_id BIGINT NOT NULL REFERENCES public.premium_collections(id) ON DELETE CASCADE,
  participant_user_id   BIGINT REFERENCES public.profiles(id) ON DELETE SET NULL,
  participant_name      TEXT   NOT NULL,
  participant_key       TEXT   NOT NULL,
  score                 INTEGER NOT NULL,
  total_questions       INTEGER NOT NULL,
  correct_answers       INTEGER NOT NULL,
  incorrect_answers     INTEGER NOT NULL,
  unanswered            INTEGER NOT NULL,
  time_taken_secs       INTEGER,
  category_wise_results JSONB NOT NULL DEFAULT '[]'::JSONB,
  collection_title      TEXT,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_challenge_attempts_challenge ON public.collection_challenge_attempts(challenge_id);
CREATE INDEX IF NOT EXISTS idx_challenge_attempts_key       ON public.collection_challenge_attempts(participant_key);
-- Leaderboard-ready index
CREATE INDEX IF NOT EXISTS idx_challenge_attempts_leaderboard ON public.collection_challenge_attempts(challenge_id, score DESC, correct_answers DESC, created_at ASC);

-- ---------------------------------------------------------------
-- QUIZ QUESTION COMPLAINTS (user-to-creator feedback on specific questions)
-- Replaces + improves on old quiz_question_complaints table
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.quiz_question_complaints (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  premium_collection_id BIGINT REFERENCES public.premium_collections(id) ON DELETE CASCADE,
  series_id             BIGINT REFERENCES public.test_series(id) ON DELETE SET NULL,
  attempt_id            BIGINT REFERENCES public.test_attempts(id) ON DELETE CASCADE,
  creator_user_id       BIGINT REFERENCES public.profiles(id) ON DELETE CASCADE,
  user_id               BIGINT NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  -- Question reference
  quiz_id               BIGINT REFERENCES public.quizzes(id) ON DELETE SET NULL,
  passage_quiz_id       BIGINT REFERENCES public.passage_quizzes(id) ON DELETE SET NULL,
  question_number       INTEGER NOT NULL,
  question_text         TEXT    NOT NULL,
  selected_option       TEXT,
  correct_answer        TEXT,
  -- Complaint
  complaint_text        TEXT    NOT NULL,
  status                TEXT    NOT NULL DEFAULT 'received'
    CHECK (status IN ('received', 'pending', 'resolved', 'dismissed')),
  creator_note          TEXT,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  resolved_at           TIMESTAMPTZ
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_quiz_complaints_unique
  ON public.quiz_question_complaints(attempt_id, question_number, user_id)
  WHERE attempt_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_quiz_complaints_creator  ON public.quiz_question_complaints(creator_user_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_quiz_complaints_user     ON public.quiz_question_complaints(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_quiz_complaints_status   ON public.quiz_question_complaints(status);

DROP TRIGGER IF EXISTS trg_quiz_question_complaints_updated_at ON public.quiz_question_complaints;
CREATE TRIGGER trg_quiz_question_complaints_updated_at
  BEFORE UPDATE ON public.quiz_question_complaints
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ---------------------------------------------------------------
-- DISCUSSION SPEAKER REQUESTS (for live Agora class discussions)
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.discussion_speaker_requests (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scope_type          TEXT NOT NULL CHECK (scope_type IN ('series', 'test')),
  scope_id            BIGINT NOT NULL,
  series_id           BIGINT NOT NULL REFERENCES public.test_series(id) ON DELETE CASCADE,
  live_room_id        BIGINT REFERENCES public.live_rooms(id) ON DELETE CASCADE,
  discussion_key      TEXT NOT NULL CHECK (discussion_key IN ('final_discussion', 'test_discussion', 'live_class')),
  discussion_channel  TEXT NOT NULL,
  user_id             BIGINT NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  display_name        TEXT NOT NULL,
  status              TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'approved', 'rejected', 'withdrawn', 'removed')),
  note                TEXT,
  requested_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  resolved_at         TIMESTAMPTZ,
  resolved_by         BIGINT REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_disc_speaker_scope   ON public.discussion_speaker_requests(scope_type, scope_id, discussion_key);
CREATE INDEX IF NOT EXISTS idx_disc_speaker_channel ON public.discussion_speaker_requests(discussion_channel);
CREATE INDEX IF NOT EXISTS idx_disc_speaker_user    ON public.discussion_speaker_requests(user_id, status);
CREATE UNIQUE INDEX IF NOT EXISTS ux_disc_speaker_active
  ON public.discussion_speaker_requests(scope_type, scope_id, discussion_key, user_id)
  WHERE status IN ('pending', 'approved');

DROP TRIGGER IF EXISTS trg_disc_speaker_updated_at ON public.discussion_speaker_requests;
CREATE TRIGGER trg_disc_speaker_updated_at
  BEFORE UPDATE ON public.discussion_speaker_requests
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ---------------------------------------------------------------
-- ROW LEVEL SECURITY
-- ---------------------------------------------------------------

ALTER TABLE public.creator_profiles             ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.creator_profile_exams        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.creator_profile_reviews      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mentorship_entitlements      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mentorship_slots             ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mentorship_requests          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mentorship_sessions          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mentorship_messages          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mains_test_copy_marks        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_mains_evaluations       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.category_ai_sources          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.category_ai_source_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_ai_quiz_hints           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.collection_challenge_links   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.collection_challenge_attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quiz_question_complaints     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.discussion_speaker_requests  ENABLE ROW LEVEL SECURITY;

-- Creator profiles: public read
DROP POLICY IF EXISTS "creator_profiles_public_read" ON public.creator_profiles;
CREATE POLICY "creator_profiles_public_read" ON public.creator_profiles
  FOR SELECT TO anon, authenticated USING (is_public = TRUE OR public.is_admin_or_moderator());
DROP POLICY IF EXISTS "creator_profiles_own_write" ON public.creator_profiles;
CREATE POLICY "creator_profiles_own_write" ON public.creator_profiles FOR ALL TO authenticated
  USING (
    public.is_admin_or_moderator()
    OR EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = creator_profiles.user_id AND p.auth_user_id = auth.uid())
  )
  WITH CHECK (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = creator_profiles.user_id AND p.auth_user_id = auth.uid()));

-- Creator profile exams: public read
DROP POLICY IF EXISTS "creator_profile_exams_public_read" ON public.creator_profile_exams;
CREATE POLICY "creator_profile_exams_public_read" ON public.creator_profile_exams FOR SELECT TO anon, authenticated USING (TRUE);

-- Creator profile reviews
DROP POLICY IF EXISTS "creator_reviews_public_read" ON public.creator_profile_reviews;
CREATE POLICY "creator_reviews_public_read" ON public.creator_profile_reviews FOR SELECT TO anon, authenticated USING (TRUE);
DROP POLICY IF EXISTS "creator_reviews_own_write" ON public.creator_profile_reviews;
CREATE POLICY "creator_reviews_own_write" ON public.creator_profile_reviews FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = creator_profile_reviews.reviewer_id AND p.auth_user_id = auth.uid()))
  WITH CHECK (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = creator_profile_reviews.reviewer_id AND p.auth_user_id = auth.uid()));

-- Mentorship: own
DROP POLICY IF EXISTS "mentorship_entitlements_own" ON public.mentorship_entitlements;
CREATE POLICY "mentorship_entitlements_own" ON public.mentorship_entitlements FOR ALL TO authenticated
  USING (public.is_admin_or_moderator() OR EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = mentorship_entitlements.user_id AND p.auth_user_id = auth.uid()))
  WITH CHECK (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = mentorship_entitlements.user_id AND p.auth_user_id = auth.uid()));

DROP POLICY IF EXISTS "mentorship_slots_public_read" ON public.mentorship_slots;
CREATE POLICY "mentorship_slots_public_read" ON public.mentorship_slots FOR SELECT TO authenticated USING (is_active = TRUE);
DROP POLICY IF EXISTS "mentorship_slots_mentor_write" ON public.mentorship_slots;
CREATE POLICY "mentorship_slots_mentor_write" ON public.mentorship_slots FOR ALL TO authenticated
  USING (public.is_admin_or_moderator() OR EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = mentorship_slots.mentor_id AND p.auth_user_id = auth.uid()))
  WITH CHECK (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = mentorship_slots.mentor_id AND p.auth_user_id = auth.uid()));

DROP POLICY IF EXISTS "mentorship_requests_own" ON public.mentorship_requests;
CREATE POLICY "mentorship_requests_own" ON public.mentorship_requests FOR ALL TO authenticated
  USING (
    public.is_admin_or_moderator()
    OR EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = mentorship_requests.user_id AND p.auth_user_id = auth.uid())
    OR EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = mentorship_requests.mentor_id AND p.auth_user_id = auth.uid())
  )
  WITH CHECK (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = mentorship_requests.user_id AND p.auth_user_id = auth.uid()));

DROP POLICY IF EXISTS "mentorship_sessions_own" ON public.mentorship_sessions;
CREATE POLICY "mentorship_sessions_own" ON public.mentorship_sessions FOR ALL TO authenticated
  USING (
    public.is_admin_or_moderator()
    OR EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = mentorship_sessions.user_id AND p.auth_user_id = auth.uid())
    OR EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = mentorship_sessions.mentor_id AND p.auth_user_id = auth.uid())
  )
  WITH CHECK (public.is_admin_or_moderator() OR EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = mentorship_sessions.mentor_id AND p.auth_user_id = auth.uid()));

DROP POLICY IF EXISTS "mentorship_messages_own" ON public.mentorship_messages;
CREATE POLICY "mentorship_messages_own" ON public.mentorship_messages FOR ALL TO authenticated
  USING (
    public.is_admin_or_moderator()
    OR EXISTS (
      SELECT 1 FROM public.mentorship_requests mr
      JOIN public.profiles p ON p.id = mr.user_id OR p.id = mr.mentor_id
      WHERE mr.id = mentorship_messages.request_id AND p.auth_user_id = auth.uid()
    )
  )
  WITH CHECK (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = mentorship_messages.sender_id AND p.auth_user_id = auth.uid()));

-- Mains copy marks
DROP POLICY IF EXISTS "mains_copy_marks_scoped" ON public.mains_test_copy_marks;
CREATE POLICY "mains_copy_marks_scoped" ON public.mains_test_copy_marks FOR ALL TO authenticated
  USING (
    public.is_admin_or_moderator()
    OR EXISTS (SELECT 1 FROM public.mains_test_copy_submissions sub JOIN public.profiles p ON p.id = sub.user_id WHERE sub.id = mains_test_copy_marks.submission_id AND p.auth_user_id = auth.uid())
  )
  WITH CHECK (public.is_admin_or_moderator());

-- User mains evaluations
DROP POLICY IF EXISTS "user_mains_eval_own" ON public.user_mains_evaluations;
CREATE POLICY "user_mains_eval_own" ON public.user_mains_evaluations FOR ALL TO authenticated
  USING (public.is_admin_or_moderator() OR EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = user_mains_evaluations.user_id AND p.auth_user_id = auth.uid()))
  WITH CHECK (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = user_mains_evaluations.user_id AND p.auth_user_id = auth.uid()));

-- Category AI sources: admin write, creator read
DROP POLICY IF EXISTS "category_ai_sources_creator_read" ON public.category_ai_sources;
CREATE POLICY "category_ai_sources_creator_read" ON public.category_ai_sources FOR SELECT TO authenticated USING (public.is_creator());
DROP POLICY IF EXISTS "category_ai_sources_admin_write" ON public.category_ai_sources;
CREATE POLICY "category_ai_sources_admin_write" ON public.category_ai_sources FOR ALL TO authenticated
  USING (public.is_admin_or_moderator()) WITH CHECK (public.is_admin_or_moderator());
DROP POLICY IF EXISTS "category_ai_source_cats_creator_read" ON public.category_ai_source_categories;
CREATE POLICY "category_ai_source_cats_creator_read" ON public.category_ai_source_categories FOR SELECT TO authenticated USING (public.is_creator());
DROP POLICY IF EXISTS "category_ai_source_cats_admin_write" ON public.category_ai_source_categories;
CREATE POLICY "category_ai_source_cats_admin_write" ON public.category_ai_source_categories FOR ALL TO authenticated
  USING (public.is_admin_or_moderator()) WITH CHECK (public.is_admin_or_moderator());

-- AI quiz hints: own
DROP POLICY IF EXISTS "user_ai_quiz_hints_own" ON public.user_ai_quiz_hints;
CREATE POLICY "user_ai_quiz_hints_own" ON public.user_ai_quiz_hints FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = user_ai_quiz_hints.user_id AND p.auth_user_id = auth.uid()))
  WITH CHECK (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = user_ai_quiz_hints.user_id AND p.auth_user_id = auth.uid()));

-- Challenge links: owner only; attempts: owner + participant
DROP POLICY IF EXISTS "challenge_links_own" ON public.collection_challenge_links;
CREATE POLICY "challenge_links_own" ON public.collection_challenge_links FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = collection_challenge_links.owner_user_id AND p.auth_user_id = auth.uid()))
  WITH CHECK (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = collection_challenge_links.owner_user_id AND p.auth_user_id = auth.uid()));

DROP POLICY IF EXISTS "challenge_attempts_read" ON public.collection_challenge_attempts;
CREATE POLICY "challenge_attempts_read" ON public.collection_challenge_attempts FOR SELECT TO authenticated
  USING (
    EXISTS (SELECT 1 FROM public.collection_challenge_links l JOIN public.profiles p ON p.id = l.owner_user_id WHERE l.id = collection_challenge_attempts.challenge_id AND p.auth_user_id = auth.uid())
    OR EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = collection_challenge_attempts.participant_user_id AND p.auth_user_id = auth.uid())
  );
DROP POLICY IF EXISTS "challenge_attempts_insert" ON public.collection_challenge_attempts;
CREATE POLICY "challenge_attempts_insert" ON public.collection_challenge_attempts FOR INSERT TO authenticated
  WITH CHECK (participant_user_id IS NULL OR EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = collection_challenge_attempts.participant_user_id AND p.auth_user_id = auth.uid()));

-- Quiz complaints
DROP POLICY IF EXISTS "quiz_complaints_user_insert" ON public.quiz_question_complaints;
CREATE POLICY "quiz_complaints_user_insert" ON public.quiz_question_complaints FOR INSERT TO authenticated
  WITH CHECK (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = quiz_question_complaints.user_id AND p.auth_user_id = auth.uid()));
DROP POLICY IF EXISTS "quiz_complaints_user_read" ON public.quiz_question_complaints;
CREATE POLICY "quiz_complaints_user_read" ON public.quiz_question_complaints FOR SELECT TO authenticated
  USING (
    public.is_admin_or_moderator()
    OR EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = quiz_question_complaints.user_id AND p.auth_user_id = auth.uid())
    OR EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = quiz_question_complaints.creator_user_id AND p.auth_user_id = auth.uid())
  );
DROP POLICY IF EXISTS "quiz_complaints_creator_update" ON public.quiz_question_complaints;
CREATE POLICY "quiz_complaints_creator_update" ON public.quiz_question_complaints FOR UPDATE TO authenticated
  USING (public.is_admin_or_moderator() OR EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = quiz_question_complaints.creator_user_id AND p.auth_user_id = auth.uid()))
  WITH CHECK (public.is_admin_or_moderator() OR EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = quiz_question_complaints.creator_user_id AND p.auth_user_id = auth.uid()));

-- Discussion speaker requests
DROP POLICY IF EXISTS "disc_speaker_authenticated" ON public.discussion_speaker_requests;
CREATE POLICY "disc_speaker_authenticated" ON public.discussion_speaker_requests FOR ALL TO authenticated
  USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);

-- ---------------------------------------------------------------
-- REALTIME PUBLICATION (tables that need live updates)
-- ---------------------------------------------------------------

DO $$
DECLARE
  realtime_tables TEXT[] := ARRAY[
    'discussion_speaker_requests',
    'mentorship_messages',
    'live_room_interactions',
    'mentorship_requests',
    'mains_test_copy_submissions'
  ];
  t TEXT;
BEGIN
  FOREACH t IN ARRAY realtime_tables LOOP
    IF NOT EXISTS (
      SELECT 1 FROM pg_publication_tables
      WHERE pubname = 'supabase_realtime'
        AND schemaname = 'public'
        AND tablename = t
    ) THEN
      EXECUTE FORMAT('ALTER PUBLICATION supabase_realtime ADD TABLE public.%I', t);
    END IF;
  END LOOP;
END;
$$;

NOTIFY pgrst, 'reload schema';
