-- =============================================================
-- MIGRATION 10: Subscriptions, Payments & Commerce
-- =============================================================

-- ---------------------------------------------------------------
-- SUBSCRIPTION PLANS (Multiple tiers)
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.subscription_plans (
  id                            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                          TEXT NOT NULL UNIQUE,   -- 'free', 'pro', 'expert'
  display_name                  TEXT NOT NULL,
  description                   TEXT,
  price_monthly                 NUMERIC(10,2),
  price_annual                  NUMERIC(10,2),
  -- Per-domain monthly AI generation quotas
  ai_quota_gk                   INTEGER NOT NULL DEFAULT 10,
  ai_quota_maths                INTEGER NOT NULL DEFAULT 10,
  ai_quota_passage              INTEGER NOT NULL DEFAULT 5,
  ai_quota_mains                INTEGER NOT NULL DEFAULT 5,
  -- Content access
  can_access_subscribed_content BOOLEAN NOT NULL DEFAULT FALSE,
  -- Feature flags
  priority_ai                   BOOLEAN NOT NULL DEFAULT FALSE,
  is_active                     BOOLEAN NOT NULL DEFAULT TRUE,
  display_order                 INTEGER NOT NULL DEFAULT 0,
  created_at                    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at                    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

DROP TRIGGER IF EXISTS trg_subscription_plans_set_updated_at ON public.subscription_plans;
CREATE TRIGGER trg_subscription_plans_set_updated_at
  BEFORE UPDATE ON public.subscription_plans
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- Seed default plans
INSERT INTO public.subscription_plans
  (name, display_name, description, price_monthly, price_annual,
   ai_quota_gk, ai_quota_maths, ai_quota_passage, ai_quota_mains,
   can_access_subscribed_content, priority_ai, display_order)
VALUES
  ('free',   'Free',   'Basic access with limited AI',     NULL,    NULL,    10,  10,  5,   5,   FALSE, FALSE, 0),
  ('pro',    'Pro',    'Enhanced access with more AI',     399.00,  3499.00, 100, 100, 50,  30,  TRUE,  FALSE, 1),
  ('expert', 'Expert', 'Unlimited access with priority AI',799.00,  6999.00, 999, 999, 999, 200, TRUE,  TRUE,  2)
ON CONFLICT (name) DO NOTHING;

-- ---------------------------------------------------------------
-- SUBSCRIPTIONS (per-user active plan)
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.subscriptions (
  id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id                  BIGINT NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  plan_id                  BIGINT REFERENCES public.subscription_plans(id) ON DELETE SET NULL,
  plan                     TEXT NOT NULL DEFAULT 'free',
  start_date               TIMESTAMPTZ NOT NULL,
  end_date                 TIMESTAMPTZ NOT NULL,
  status                   TEXT NOT NULL DEFAULT 'active'
    CHECK (status IN ('active', 'pending', 'inactive', 'cancelled')),
  razorpay_subscription_id TEXT UNIQUE,
  last_razorpay_payment_id TEXT,
  created_at               TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at               TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_subscriptions_user_status ON public.subscriptions(user_id, status);
CREATE INDEX IF NOT EXISTS idx_subscriptions_plan        ON public.subscriptions(plan, status);

DROP TRIGGER IF EXISTS trg_subscriptions_set_updated_at ON public.subscriptions;
CREATE TRIGGER trg_subscriptions_set_updated_at
  BEFORE UPDATE ON public.subscriptions
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE OR REPLACE FUNCTION public.has_active_subscription(required_plan TEXT DEFAULT 'pro')
RETURNS BOOLEAN LANGUAGE SQL STABLE AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.subscriptions s
    JOIN public.profiles p ON p.id = s.user_id
    WHERE p.auth_user_id = auth.uid()
      AND s.status = 'active'
      AND s.end_date >= NOW()
      AND EXISTS (
        SELECT 1 FROM public.subscription_plans sp
        WHERE sp.id = s.plan_id
          AND sp.name = required_plan
          AND sp.can_access_subscribed_content = TRUE
      )
  );
$$;

-- ---------------------------------------------------------------
-- PAYMENTS (Full transaction record)
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.payments (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id             BIGINT NOT NULL REFERENCES public.profiles(id) ON DELETE RESTRICT,
  amount              NUMERIC(10,2) NOT NULL,
  currency            TEXT NOT NULL DEFAULT 'INR',
  status              TEXT NOT NULL DEFAULT 'created'
    CHECK (status IN ('created', 'paid', 'failed', 'refunded')),
  gateway             TEXT NOT NULL DEFAULT 'razorpay',
  gateway_order_id    TEXT UNIQUE,
  gateway_payment_id  TEXT,
  gateway_signature   TEXT,
  -- What was purchased (only one populated)
  test_series_id      BIGINT REFERENCES public.test_series(id) ON DELETE SET NULL,
  collection_id       BIGINT REFERENCES public.premium_collections(id) ON DELETE SET NULL,
  subscription_plan   TEXT,    -- plan name if purchasing a subscription
  -- Notes
  notes               TEXT,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_payments_user_id   ON public.payments(user_id);
CREATE INDEX IF NOT EXISTS idx_payments_status    ON public.payments(status);
CREATE INDEX IF NOT EXISTS idx_payments_gateway   ON public.payments(gateway_order_id);
CREATE INDEX IF NOT EXISTS idx_payments_series    ON public.payments(test_series_id);
CREATE INDEX IF NOT EXISTS idx_payments_collection ON public.payments(collection_id);

DROP TRIGGER IF EXISTS trg_payments_set_updated_at ON public.payments;
CREATE TRIGGER trg_payments_set_updated_at
  BEFORE UPDATE ON public.payments
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ---------------------------------------------------------------
-- REVENUE SPLITS (80/20 creator / platform — manual admin action)
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.revenue_splits (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payment_id       BIGINT NOT NULL REFERENCES public.payments(id) ON DELETE CASCADE,
  creator_user_id  BIGINT NOT NULL REFERENCES public.profiles(id) ON DELETE RESTRICT,
  creator_amount   NUMERIC(10,2) NOT NULL,
  platform_amount  NUMERIC(10,2) NOT NULL,
  status           TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'processed', 'paid')),
  paid_at          TIMESTAMPTZ,
  admin_notes      TEXT,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_revenue_splits_payment ON public.revenue_splits(payment_id);
CREATE INDEX IF NOT EXISTS idx_revenue_splits_creator ON public.revenue_splits(creator_user_id);
CREATE INDEX IF NOT EXISTS idx_revenue_splits_status  ON public.revenue_splits(status);

DROP TRIGGER IF EXISTS trg_revenue_splits_set_updated_at ON public.revenue_splits;
CREATE TRIGGER trg_revenue_splits_set_updated_at
  BEFORE UPDATE ON public.revenue_splits
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ---------------------------------------------------------------
-- USER CONTENT ACCESS (Unified gating table)
-- Covers both series-based and direct collection purchases
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.user_content_access (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         BIGINT NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  access_type     TEXT   NOT NULL CHECK (access_type IN ('test_series', 'collection', 'subscription')),
  test_series_id  BIGINT REFERENCES public.test_series(id) ON DELETE CASCADE,
  collection_id   BIGINT REFERENCES public.premium_collections(id) ON DELETE CASCADE,
  payment_id      BIGINT REFERENCES public.payments(id) ON DELETE SET NULL,
  granted_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at      TIMESTAMPTZ,   -- NULL = never expires
  is_active       BOOLEAN NOT NULL DEFAULT TRUE,
  UNIQUE NULLS NOT DISTINCT (user_id, test_series_id, collection_id)
);

CREATE INDEX IF NOT EXISTS idx_uca_user         ON public.user_content_access(user_id);
CREATE INDEX IF NOT EXISTS idx_uca_series       ON public.user_content_access(test_series_id);
CREATE INDEX IF NOT EXISTS idx_uca_collection   ON public.user_content_access(collection_id);
CREATE INDEX IF NOT EXISTS idx_uca_expires      ON public.user_content_access(expires_at);

-- ---------------------------------------------------------------
-- SHOPPING CART
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.shopping_cart_items (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id           BIGINT NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  item_type         TEXT   NOT NULL CHECK (item_type IN ('test_series', 'premium_collection', 'subscription_plan')),
  item_id           BIGINT NOT NULL,
  price_at_addition NUMERIC(10,2) NOT NULL DEFAULT 0,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_cart_user ON public.shopping_cart_items(user_id);

-- ---------------------------------------------------------------
-- ROW LEVEL SECURITY
-- ---------------------------------------------------------------

ALTER TABLE public.subscription_plans    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subscriptions         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments              ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.revenue_splits        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_content_access   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shopping_cart_items   ENABLE ROW LEVEL SECURITY;

-- Subscription plans: public read
DROP POLICY IF EXISTS "sub_plans_public_read" ON public.subscription_plans;
CREATE POLICY "sub_plans_public_read" ON public.subscription_plans
  FOR SELECT TO anon, authenticated USING (TRUE);
DROP POLICY IF EXISTS "sub_plans_admin_write" ON public.subscription_plans;
CREATE POLICY "sub_plans_admin_write" ON public.subscription_plans
  FOR ALL TO authenticated
  USING (public.is_admin_or_moderator()) WITH CHECK (public.is_admin_or_moderator());

-- Subscriptions: own read/insert, admin all
DROP POLICY IF EXISTS "subscriptions_own" ON public.subscriptions;
CREATE POLICY "subscriptions_own" ON public.subscriptions FOR ALL TO authenticated
  USING (
    public.is_admin_or_moderator()
    OR EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = subscriptions.user_id AND p.auth_user_id = auth.uid())
  )
  WITH CHECK (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = subscriptions.user_id AND p.auth_user_id = auth.uid()));

-- Payments: own user + admin
DROP POLICY IF EXISTS "payments_own" ON public.payments;
CREATE POLICY "payments_own" ON public.payments FOR SELECT TO authenticated
  USING (
    public.is_admin_or_moderator()
    OR EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = payments.user_id AND p.auth_user_id = auth.uid())
  );
DROP POLICY IF EXISTS "payments_own_insert" ON public.payments;
CREATE POLICY "payments_own_insert" ON public.payments FOR INSERT TO authenticated
  WITH CHECK (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = payments.user_id AND p.auth_user_id = auth.uid()));
DROP POLICY IF EXISTS "payments_admin_update" ON public.payments;
CREATE POLICY "payments_admin_update" ON public.payments FOR UPDATE TO authenticated
  USING (public.is_admin_or_moderator()) WITH CHECK (public.is_admin_or_moderator());

-- Revenue splits: admin only
DROP POLICY IF EXISTS "revenue_splits_admin" ON public.revenue_splits;
CREATE POLICY "revenue_splits_admin" ON public.revenue_splits FOR ALL TO authenticated
  USING (public.is_admin_or_moderator()) WITH CHECK (public.is_admin_or_moderator());

-- User content access: own read, admin write
DROP POLICY IF EXISTS "uca_own_read" ON public.user_content_access;
CREATE POLICY "uca_own_read" ON public.user_content_access FOR SELECT TO authenticated
  USING (
    public.is_admin_or_moderator()
    OR EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = user_content_access.user_id AND p.auth_user_id = auth.uid())
  );
DROP POLICY IF EXISTS "uca_admin_write" ON public.user_content_access;
CREATE POLICY "uca_admin_write" ON public.user_content_access FOR ALL TO authenticated
  USING (public.is_admin_or_moderator()) WITH CHECK (public.is_admin_or_moderator());

-- Cart: own
DROP POLICY IF EXISTS "cart_own" ON public.shopping_cart_items;
CREATE POLICY "cart_own" ON public.shopping_cart_items FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = shopping_cart_items.user_id AND p.auth_user_id = auth.uid()))
  WITH CHECK (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = shopping_cart_items.user_id AND p.auth_user_id = auth.uid()));

-- ---------------------------------------------------------------
-- FULL ACCESS FUNCTIONS (now that subscriptions + user_content_access exist)
-- Replaces the simplified stubs installed in migration 7.
-- ---------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.can_access_premium_collection(target_id BIGINT)
RETURNS BOOLEAN LANGUAGE SQL STABLE AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.premium_collections pc
    LEFT JOIN public.profiles owner ON owner.id = pc.creator_id
    WHERE pc.id = target_id AND (
      public.is_admin_or_moderator()
      OR owner.auth_user_id = auth.uid()
      OR (pc.is_public = TRUE AND pc.is_paid = FALSE AND pc.is_subscription = FALSE)
      OR (pc.is_subscription = TRUE AND EXISTS (
          SELECT 1 FROM public.subscriptions s
          JOIN public.profiles up ON up.id = s.user_id
          WHERE up.auth_user_id = auth.uid()
            AND s.status = 'active'
            AND s.end_date >= NOW()
      ))
      OR EXISTS (
          SELECT 1 FROM public.user_content_access uca
          JOIN public.profiles up ON up.id = uca.user_id
          WHERE up.auth_user_id = auth.uid()
            AND uca.collection_id = target_id
            AND uca.is_active = TRUE
            AND (uca.expires_at IS NULL OR uca.expires_at > NOW())
      )
    )
  );
$$;

CREATE OR REPLACE FUNCTION public.can_access_test_series(target_id BIGINT)
RETURNS BOOLEAN LANGUAGE SQL STABLE AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.test_series ts
    LEFT JOIN public.profiles owner ON owner.id = ts.creator_id
    WHERE ts.id = target_id AND (
      public.is_admin_or_moderator()
      OR owner.auth_user_id = auth.uid()
      OR (ts.is_public = TRUE AND ts.is_paid = FALSE AND ts.is_subscription = FALSE)
      OR (ts.is_subscription = TRUE AND EXISTS (
          SELECT 1 FROM public.subscriptions s
          JOIN public.profiles up ON up.id = s.user_id
          WHERE up.auth_user_id = auth.uid()
            AND s.status = 'active'
            AND s.end_date >= NOW()
      ))
      OR EXISTS (
          SELECT 1 FROM public.user_content_access uca
          JOIN public.profiles up ON up.id = uca.user_id
          WHERE up.auth_user_id = auth.uid()
            AND uca.test_series_id = target_id
            AND uca.is_active = TRUE
            AND (uca.expires_at IS NULL OR uca.expires_at > NOW())
      )
    )
  );
$$;
