-- =============================================================
-- MIGRATION 7: Collections, Test Series, Program Units & Steps
-- =============================================================

-- ---------------------------------------------------------------
-- PREMIUM COLLECTIONS (Tests / Mains Sets created by experts)
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.premium_collections (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                  TEXT NOT NULL,
  slug                  TEXT UNIQUE,
  description           TEXT,
  collection_type       TEXT NOT NULL DEFAULT 'prelims'
    CHECK (collection_type IN ('prelims', 'mains', 'mixed')),
  image_url             TEXT,

  -- Access control
  is_paid               BOOLEAN NOT NULL DEFAULT FALSE,
  is_public             BOOLEAN NOT NULL DEFAULT FALSE,
  is_subscription       BOOLEAN NOT NULL DEFAULT FALSE,
  price                 NUMERIC(10,2),

  -- Test settings (for prelims)
  time_limit_minutes    INTEGER,
  negative_marking_factor NUMERIC(4,2) NOT NULL DEFAULT 0.33,
  shuffle_questions     BOOLEAN NOT NULL DEFAULT FALSE,

  -- State
  is_finalized          BOOLEAN NOT NULL DEFAULT FALSE,
  is_active             BOOLEAN NOT NULL DEFAULT TRUE,

  -- Authorship
  creator_id            BIGINT NOT NULL REFERENCES public.profiles(id) ON DELETE RESTRICT,

  -- Source tracking (how this collection was built)
  source_category_ids   BIGINT[]    NOT NULL DEFAULT '{}',
  source_pdf_url        TEXT,
  source_content_html   TEXT,

  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_prem_collections_creator  ON public.premium_collections(creator_id);
CREATE INDEX IF NOT EXISTS idx_prem_collections_flags    ON public.premium_collections(is_public, is_paid, collection_type);

DROP TRIGGER IF EXISTS trg_premium_collections_set_updated_at ON public.premium_collections;
CREATE TRIGGER trg_premium_collections_set_updated_at
  BEFORE UPDATE ON public.premium_collections
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- Collection → Alpha Category
CREATE TABLE IF NOT EXISTS public.premium_collection_alpha_categories (
  premium_collection_id BIGINT NOT NULL REFERENCES public.premium_collections(id) ON DELETE CASCADE,
  alpha_category_id     BIGINT NOT NULL REFERENCES public.alpha_categories(id) ON DELETE CASCADE,
  PRIMARY KEY (premium_collection_id, alpha_category_id)
);

-- ---------------------------------------------------------------
-- PREMIUM COLLECTION ITEMS
-- Each item links to an actual quiz/question row — no JSONB snapshots
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.premium_collection_items (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  premium_collection_id BIGINT NOT NULL REFERENCES public.premium_collections(id) ON DELETE CASCADE,
  order_index         INTEGER NOT NULL DEFAULT 0,
  item_type           TEXT NOT NULL
    CHECK (item_type IN ('gk_quiz', 'maths_quiz', 'passage_quiz', 'mains_question')),
  -- Exactly one of these will be populated
  quiz_id             BIGINT REFERENCES public.quizzes(id) ON DELETE CASCADE,
  passage_quiz_id     BIGINT REFERENCES public.passage_quizzes(id) ON DELETE CASCADE,
  mains_question_id   BIGINT REFERENCES public.mains_questions(id) ON DELETE CASCADE,
  -- Category assigned at item level (overrides question's own category for this test's analytics)
  category_id         BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (
    (quiz_id IS NOT NULL)::INT +
    (passage_quiz_id IS NOT NULL)::INT +
    (mains_question_id IS NOT NULL)::INT = 1
  )
);

CREATE INDEX IF NOT EXISTS idx_prem_coll_items_collection ON public.premium_collection_items(premium_collection_id);
CREATE INDEX IF NOT EXISTS idx_prem_coll_items_order      ON public.premium_collection_items(premium_collection_id, order_index);

-- ---------------------------------------------------------------
-- TEST SERIES (Programs — both Prelims and Mains)
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.test_series (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                  TEXT NOT NULL,
  slug                  TEXT UNIQUE,
  description           TEXT,
  series_kind           TEXT NOT NULL DEFAULT 'prelims'
    CHECK (series_kind IN ('prelims', 'mains', 'hybrid')),
  cover_image_url       TEXT,
  intro_resource_url    TEXT,

  -- Access control
  is_paid               BOOLEAN NOT NULL DEFAULT FALSE,
  is_public             BOOLEAN NOT NULL DEFAULT FALSE,
  is_subscription       BOOLEAN NOT NULL DEFAULT FALSE,
  price                 NUMERIC(10,2),

  -- Program settings
  evaluation_enabled    BOOLEAN NOT NULL DEFAULT TRUE,
  mentorship_enabled    BOOLEAN NOT NULL DEFAULT TRUE,

  -- Default test settings applied to all collections in this series
  default_time_limit_minutes      INTEGER,
  default_negative_marking_factor NUMERIC(4,2) DEFAULT 0.33,
  default_shuffle_questions       BOOLEAN NOT NULL DEFAULT FALSE,

  -- State
  is_finalized          BOOLEAN NOT NULL DEFAULT FALSE,
  is_active             BOOLEAN NOT NULL DEFAULT TRUE,

  -- Authorship
  creator_id            BIGINT NOT NULL REFERENCES public.profiles(id) ON DELETE RESTRICT,

  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_test_series_creator  ON public.test_series(creator_id);
CREATE INDEX IF NOT EXISTS idx_test_series_kind     ON public.test_series(series_kind, is_active);
CREATE INDEX IF NOT EXISTS idx_test_series_public   ON public.test_series(is_public, is_paid);

DROP TRIGGER IF EXISTS trg_test_series_set_updated_at ON public.test_series;
CREATE TRIGGER trg_test_series_set_updated_at
  BEFORE UPDATE ON public.test_series
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- Test Series → Exam filter
CREATE TABLE IF NOT EXISTS public.test_series_exams (
  test_series_id BIGINT NOT NULL REFERENCES public.test_series(id) ON DELETE CASCADE,
  exam_id        BIGINT NOT NULL REFERENCES public.exams(id) ON DELETE CASCADE,
  PRIMARY KEY (test_series_id, exam_id)
);
CREATE INDEX IF NOT EXISTS idx_test_series_exams_exam ON public.test_series_exams(exam_id);

-- Test Series → Alpha Category
CREATE TABLE IF NOT EXISTS public.test_series_alpha_categories (
  test_series_id    BIGINT NOT NULL REFERENCES public.test_series(id) ON DELETE CASCADE,
  alpha_category_id BIGINT NOT NULL REFERENCES public.alpha_categories(id) ON DELETE CASCADE,
  PRIMARY KEY (test_series_id, alpha_category_id)
);

-- ---------------------------------------------------------------
-- PROGRAM UNITS (Sections within a program e.g. "Unit 1", "Unit 2")
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.program_units (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  series_id     BIGINT NOT NULL REFERENCES public.test_series(id) ON DELETE CASCADE,
  title         TEXT   NOT NULL,  -- e.g. "Unit 1 — Ancient History"
  description   TEXT,
  display_order INTEGER NOT NULL DEFAULT 0,
  is_active     BOOLEAN NOT NULL DEFAULT TRUE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_program_units_series ON public.program_units(series_id);
CREATE INDEX IF NOT EXISTS idx_program_units_order  ON public.program_units(series_id, display_order);

DROP TRIGGER IF EXISTS trg_program_units_set_updated_at ON public.program_units;
CREATE TRIGGER trg_program_units_set_updated_at
  BEFORE UPDATE ON public.program_units
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ---------------------------------------------------------------
-- PROGRAM UNIT STEPS (Individual items within a unit:
--   PDF study material, Live Lecture, Test, Video, Note)
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.program_unit_steps (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  unit_id       BIGINT NOT NULL REFERENCES public.program_units(id) ON DELETE CASCADE,
  step_type     TEXT   NOT NULL
    CHECK (step_type IN ('pdf', 'live_lecture', 'test', 'note', 'video', 'link')),
  title         TEXT   NOT NULL,
  description   TEXT,

  -- Polymorphic references (only one populated, based on step_type)
  collection_id BIGINT REFERENCES public.premium_collections(id) ON DELETE SET NULL,  -- 'test'
  live_room_id  BIGINT,                                                                -- 'live_lecture' (FK added after live_rooms migration)
  resource_url  TEXT,   -- 'pdf', 'video', 'note', 'link'

  -- Scheduling
  scheduled_for     TIMESTAMPTZ,
  duration_minutes  INTEGER,

  display_order INTEGER NOT NULL DEFAULT 0,
  is_active     BOOLEAN NOT NULL DEFAULT TRUE,
  meta          JSONB   NOT NULL DEFAULT '{}'::JSONB,

  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_prog_unit_steps_unit  ON public.program_unit_steps(unit_id);
CREATE INDEX IF NOT EXISTS idx_prog_unit_steps_order ON public.program_unit_steps(unit_id, display_order);
CREATE INDEX IF NOT EXISTS idx_prog_unit_steps_type  ON public.program_unit_steps(step_type);

DROP TRIGGER IF EXISTS trg_program_unit_steps_set_updated_at ON public.program_unit_steps;
CREATE TRIGGER trg_program_unit_steps_set_updated_at
  BEFORE UPDATE ON public.program_unit_steps
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ---------------------------------------------------------------
-- REVIEWS (for series/collections)
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.reviews (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      BIGINT NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  content_type TEXT   NOT NULL CHECK (content_type IN ('test_series', 'premium_collection')),
  content_id   BIGINT NOT NULL,
  rating       INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
  comment      TEXT,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (user_id, content_type, content_id)
);

CREATE INDEX IF NOT EXISTS idx_reviews_content ON public.reviews(content_type, content_id);

DROP TRIGGER IF EXISTS trg_reviews_set_updated_at ON public.reviews;
CREATE TRIGGER trg_reviews_set_updated_at
  BEFORE UPDATE ON public.reviews
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ---------------------------------------------------------------
-- ACCESS FUNCTION
-- ---------------------------------------------------------------

-- NOTE: Simplified access functions — subscriptions table not yet created.
-- Full versions with subscription check are installed in migration 10.

CREATE OR REPLACE FUNCTION public.can_access_premium_collection(target_id BIGINT)
RETURNS BOOLEAN LANGUAGE SQL STABLE AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.premium_collections pc
    LEFT JOIN public.profiles owner ON owner.id = pc.creator_id
    WHERE pc.id = target_id AND (
      public.is_admin_or_moderator()
      OR owner.auth_user_id = auth.uid()
      OR (pc.is_public = TRUE AND pc.is_paid = FALSE AND pc.is_subscription = FALSE)
    )
  );
$$;

CREATE OR REPLACE FUNCTION public.can_access_test_series(target_id BIGINT)
RETURNS BOOLEAN LANGUAGE SQL STABLE AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.test_series ts
    LEFT JOIN public.profiles owner ON owner.id = ts.creator_id
    WHERE ts.id = target_id AND (
      public.is_admin_or_moderator()
      OR owner.auth_user_id = auth.uid()
      OR (ts.is_public = TRUE AND ts.is_paid = FALSE AND ts.is_subscription = FALSE)
    )
  );
$$;

-- ---------------------------------------------------------------
-- ROW LEVEL SECURITY
-- ---------------------------------------------------------------

ALTER TABLE public.premium_collections               ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.premium_collection_alpha_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.premium_collection_items          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.test_series                       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.test_series_exams                 ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.test_series_alpha_categories      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.program_units                     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.program_unit_steps                ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviews                           ENABLE ROW LEVEL SECURITY;

-- Premium Collections: access-gated read, creator/admin write
DROP POLICY IF EXISTS "prem_coll_access_read" ON public.premium_collections;
CREATE POLICY "prem_coll_access_read" ON public.premium_collections
  FOR SELECT TO anon, authenticated USING (public.can_access_premium_collection(id));

DROP POLICY IF EXISTS "prem_coll_creator_or_admin_write" ON public.premium_collections;
CREATE POLICY "prem_coll_creator_or_admin_write" ON public.premium_collections FOR ALL TO authenticated
  USING (
    public.is_admin_or_moderator()
    OR EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = premium_collections.creator_id AND p.auth_user_id = auth.uid())
  )
  WITH CHECK (
    public.is_admin_or_moderator()
    OR EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = premium_collections.creator_id AND p.auth_user_id = auth.uid())
  );

-- Collection items: gated read
DROP POLICY IF EXISTS "prem_coll_items_access_read" ON public.premium_collection_items;
CREATE POLICY "prem_coll_items_access_read" ON public.premium_collection_items
  FOR SELECT TO anon, authenticated USING (public.can_access_premium_collection(premium_collection_id));

DROP POLICY IF EXISTS "prem_coll_items_creator_or_admin_write" ON public.premium_collection_items;
CREATE POLICY "prem_coll_items_creator_or_admin_write" ON public.premium_collection_items FOR ALL TO authenticated
  USING (
    public.is_admin_or_moderator()
    OR EXISTS (SELECT 1 FROM public.premium_collections pc JOIN public.profiles p ON p.id = pc.creator_id WHERE pc.id = premium_collection_items.premium_collection_id AND p.auth_user_id = auth.uid())
  )
  WITH CHECK (
    public.is_admin_or_moderator()
    OR EXISTS (SELECT 1 FROM public.premium_collections pc JOIN public.profiles p ON p.id = pc.creator_id WHERE pc.id = premium_collection_items.premium_collection_id AND p.auth_user_id = auth.uid())
  );

-- Test Series: gated read
DROP POLICY IF EXISTS "test_series_access_read" ON public.test_series;
CREATE POLICY "test_series_access_read" ON public.test_series
  FOR SELECT TO anon, authenticated USING (public.can_access_test_series(id));

DROP POLICY IF EXISTS "test_series_creator_or_admin_write" ON public.test_series;
CREATE POLICY "test_series_creator_or_admin_write" ON public.test_series FOR ALL TO authenticated
  USING (
    public.is_admin_or_moderator()
    OR EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = test_series.creator_id AND p.auth_user_id = auth.uid())
  )
  WITH CHECK (
    public.is_admin_or_moderator()
    OR EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = test_series.creator_id AND p.auth_user_id = auth.uid())
  );

-- Program Units & Steps: series-access gated
DROP POLICY IF EXISTS "program_units_access_read" ON public.program_units;
CREATE POLICY "program_units_access_read" ON public.program_units
  FOR SELECT TO anon, authenticated USING (public.can_access_test_series(series_id));

DROP POLICY IF EXISTS "program_units_creator_or_admin_write" ON public.program_units;
CREATE POLICY "program_units_creator_or_admin_write" ON public.program_units FOR ALL TO authenticated
  USING (
    public.is_admin_or_moderator()
    OR EXISTS (SELECT 1 FROM public.test_series ts JOIN public.profiles p ON p.id = ts.creator_id WHERE ts.id = program_units.series_id AND p.auth_user_id = auth.uid())
  )
  WITH CHECK (
    public.is_admin_or_moderator()
    OR EXISTS (SELECT 1 FROM public.test_series ts JOIN public.profiles p ON p.id = ts.creator_id WHERE ts.id = program_units.series_id AND p.auth_user_id = auth.uid())
  );

DROP POLICY IF EXISTS "program_unit_steps_access_read" ON public.program_unit_steps;
CREATE POLICY "program_unit_steps_access_read" ON public.program_unit_steps
  FOR SELECT TO anon, authenticated
  USING (EXISTS (SELECT 1 FROM public.program_units pu WHERE pu.id = program_unit_steps.unit_id AND public.can_access_test_series(pu.series_id)));

DROP POLICY IF EXISTS "program_unit_steps_creator_write" ON public.program_unit_steps;
CREATE POLICY "program_unit_steps_creator_write" ON public.program_unit_steps FOR ALL TO authenticated
  USING (
    public.is_admin_or_moderator()
    OR EXISTS (
      SELECT 1 FROM public.program_units pu
      JOIN public.test_series ts ON ts.id = pu.series_id
      JOIN public.profiles p ON p.id = ts.creator_id
      WHERE pu.id = program_unit_steps.unit_id AND p.auth_user_id = auth.uid()
    )
  )
  WITH CHECK (
    public.is_admin_or_moderator()
    OR EXISTS (
      SELECT 1 FROM public.program_units pu
      JOIN public.test_series ts ON ts.id = pu.series_id
      JOIN public.profiles p ON p.id = ts.creator_id
      WHERE pu.id = program_unit_steps.unit_id AND p.auth_user_id = auth.uid()
    )
  );

-- Reviews — public read, own insert/update
DROP POLICY IF EXISTS "reviews_public_read" ON public.reviews;
CREATE POLICY "reviews_public_read" ON public.reviews FOR SELECT TO anon, authenticated USING (TRUE);

DROP POLICY IF EXISTS "reviews_own_write" ON public.reviews;
CREATE POLICY "reviews_own_write" ON public.reviews FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = reviews.user_id AND p.auth_user_id = auth.uid()))
  WITH CHECK (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = reviews.user_id AND p.auth_user_id = auth.uid()));

-- Misc: exams join/alpha categories on series — public read, creator & admin write
DROP POLICY IF EXISTS "test_series_exams_public_read" ON public.test_series_exams;
CREATE POLICY "test_series_exams_public_read" ON public.test_series_exams FOR SELECT TO anon, authenticated USING (TRUE);
DROP POLICY IF EXISTS "test_series_exams_admin_write" ON public.test_series_exams;
CREATE POLICY "test_series_exams_admin_write" ON public.test_series_exams FOR ALL TO authenticated
  USING (public.is_admin_or_moderator()) WITH CHECK (public.is_admin_or_moderator());
