-- =============================================================
-- MIGRATION 5: Question Formats & AI Configuration
-- =============================================================

-- ---------------------------------------------------------------
-- QUESTION FORMATS
-- Define the style/structure guidelines for AI generation.
-- Each format has multi-level categories assigned to it.
-- Creators pick a format when generating questions via AI.
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.question_formats (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name              TEXT NOT NULL,
  quiz_domain       TEXT NOT NULL CHECK (quiz_domain IN ('gk', 'maths', 'passage', 'mains')),
  description       TEXT,
  -- AI style instructions (system-level prompt additions)
  style_profile     JSONB NOT NULL DEFAULT '{}'::JSONB,
  -- Example questions demonstrating this format
  example_questions JSONB NOT NULL DEFAULT '[]'::JSONB,
  is_active         BOOLEAN NOT NULL DEFAULT TRUE,
  created_by        BIGINT REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_question_formats_domain    ON public.question_formats(quiz_domain);
CREATE INDEX IF NOT EXISTS idx_question_formats_active    ON public.question_formats(is_active);

DROP TRIGGER IF EXISTS trg_question_formats_set_updated_at ON public.question_formats;
CREATE TRIGGER trg_question_formats_set_updated_at
  BEFORE UPDATE ON public.question_formats
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- Categories assigned to a format (multi-level, multi-select)
CREATE TABLE IF NOT EXISTS public.question_format_categories (
  format_id   BIGINT NOT NULL REFERENCES public.question_formats(id) ON DELETE CASCADE,
  category_id BIGINT NOT NULL REFERENCES public.categories(id) ON DELETE CASCADE,
  PRIMARY KEY (format_id, category_id)
);

-- ---------------------------------------------------------------
-- AI INSTRUCTIONS (System prompts for each generation task)
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.ai_instructions (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                 TEXT NOT NULL,
  scope                TEXT NOT NULL CHECK (scope IN ('gk', 'maths', 'passage', 'mains', 'article', 'evaluation')),
  system_prompt        TEXT NOT NULL DEFAULT '',
  user_prompt_template TEXT,
  input_schema         JSONB NOT NULL DEFAULT '{}'::JSONB,
  output_schema        JSONB NOT NULL DEFAULT '{}'::JSONB,
  is_active            BOOLEAN NOT NULL DEFAULT TRUE,
  created_by           BIGINT REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ai_instructions_scope ON public.ai_instructions(scope);

DROP TRIGGER IF EXISTS trg_ai_instructions_set_updated_at ON public.ai_instructions;
CREATE TRIGGER trg_ai_instructions_set_updated_at
  BEFORE UPDATE ON public.ai_instructions
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ---------------------------------------------------------------
-- AI EXAMPLE ANALYSES (Style-guide examples for AI to follow)
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.ai_example_analyses (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title             TEXT NOT NULL,
  description       TEXT,
  quiz_domain       TEXT NOT NULL CHECK (quiz_domain IN ('gk', 'maths', 'passage', 'mains')),
  -- Hierarchical tag labels (human-readable, not FK — for flexible labelling)
  tag_level1        TEXT,
  tag_level2        TEXT,
  -- Full style profile used by AI for generation
  style_profile     JSONB NOT NULL DEFAULT '{}'::JSONB,
  -- Curated example questions demonstrating the expected style
  example_questions JSONB NOT NULL DEFAULT '[]'::JSONB,
  tags              JSONB NOT NULL DEFAULT '[]'::JSONB,
  is_active         BOOLEAN NOT NULL DEFAULT TRUE,
  author_id         BIGINT REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ai_example_analyses_domain ON public.ai_example_analyses(quiz_domain);

DROP TRIGGER IF EXISTS trg_ai_example_analyses_set_updated_at ON public.ai_example_analyses;
CREATE TRIGGER trg_ai_example_analyses_set_updated_at
  BEFORE UPDATE ON public.ai_example_analyses
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ---------------------------------------------------------------
-- AI STYLE PROFILES (per-scope style learned from existing content)
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.ai_style_profiles (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scope      TEXT NOT NULL,
  user_id    BIGINT NOT NULL DEFAULT 0,  -- 0 = global / platform default
  profile    JSONB NOT NULL DEFAULT '{}'::JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (scope, user_id)
);

DROP TRIGGER IF EXISTS trg_ai_style_profiles_set_updated_at ON public.ai_style_profiles;
CREATE TRIGGER trg_ai_style_profiles_set_updated_at
  BEFORE UPDATE ON public.ai_style_profiles
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ---------------------------------------------------------------
-- AI ARTICLE STYLE GUIDES (editorial style for article generation)
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.ai_article_style_guides (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  style_guide TEXT NOT NULL DEFAULT '',
  source_text TEXT,
  created_by  BIGINT REFERENCES public.profiles(id) ON DELETE SET NULL,
  updated_by  BIGINT REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

DROP TRIGGER IF EXISTS trg_ai_article_style_guides_set_updated_at ON public.ai_article_style_guides;
CREATE TRIGGER trg_ai_article_style_guides_set_updated_at
  BEFORE UPDATE ON public.ai_article_style_guides
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ---------------------------------------------------------------
-- ROW LEVEL SECURITY
-- ---------------------------------------------------------------

ALTER TABLE public.question_formats            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.question_format_categories  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_instructions             ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_example_analyses         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_style_profiles           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_article_style_guides     ENABLE ROW LEVEL SECURITY;

DO $$
DECLARE
  tbls TEXT[] := ARRAY[
    'question_formats','question_format_categories',
    'ai_instructions','ai_example_analyses',
    'ai_style_profiles','ai_article_style_guides'
  ];
  t TEXT;
BEGIN
  FOREACH t IN ARRAY tbls LOOP
    EXECUTE FORMAT('DROP POLICY IF EXISTS "%s_public_read" ON public.%I', t, t);
    EXECUTE FORMAT(
      'CREATE POLICY "%s_public_read" ON public.%I FOR SELECT TO anon, authenticated USING (TRUE)', t, t
    );
    EXECUTE FORMAT('DROP POLICY IF EXISTS "%s_admin_write" ON public.%I', t, t);
    EXECUTE FORMAT(
      'CREATE POLICY "%s_admin_write" ON public.%I FOR ALL TO authenticated
       USING (public.is_admin_or_moderator()) WITH CHECK (public.is_admin_or_moderator())',
      t, t
    );
  END LOOP;
END;
$$;
