-- =============================================================
-- MIGRATION 12: Creator System & Admin Utilities
-- =============================================================

-- ---------------------------------------------------------------
-- CREATOR APPLICATIONS
-- Users apply to become Prelims Expert or Mains Expert.
-- Admin/Moderator reviews and approves.
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.creator_applications (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         BIGINT NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  -- Roles the applicant is applying for
  applied_roles   TEXT[] NOT NULL,
  -- e.g. ARRAY['prelims_expert'] or ARRAY['mains_expert'] or both
  -- Personal information
  full_name       TEXT NOT NULL,
  bio             TEXT,
  qualifications  TEXT,
  experience      TEXT,
  sample_work_url TEXT,
  social_links    JSONB NOT NULL DEFAULT '{}'::JSONB,
  -- Admin review
  status          TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'under_review', 'approved', 'rejected')),
  reviewed_by     BIGINT REFERENCES public.profiles(id) ON DELETE SET NULL,
  reviewer_note   TEXT,
  reviewed_at     TIMESTAMPTZ,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_creator_applications_user   ON public.creator_applications(user_id);
CREATE INDEX IF NOT EXISTS idx_creator_applications_status ON public.creator_applications(status);

DROP TRIGGER IF EXISTS trg_creator_applications_set_updated_at ON public.creator_applications;
CREATE TRIGGER trg_creator_applications_set_updated_at
  BEFORE UPDATE ON public.creator_applications
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ---------------------------------------------------------------
-- ADMIN SUBPAGES (Named landing pages for organizing series/collections)
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.admin_subpages (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         TEXT NOT NULL,
  slug         TEXT NOT NULL UNIQUE,
  description  TEXT,
  subpage_type TEXT NOT NULL
    CHECK (subpage_type IN ('test_series', 'premium_collection', 'public')),
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

DROP TRIGGER IF EXISTS trg_admin_subpages_set_updated_at ON public.admin_subpages;
CREATE TRIGGER trg_admin_subpages_set_updated_at
  BEFORE UPDATE ON public.admin_subpages
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ---------------------------------------------------------------
-- USER ACTIVITIES (audit log of platform actions)
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.user_activities (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       BIGINT REFERENCES public.profiles(id) ON DELETE SET NULL,
  activity_type TEXT   NOT NULL,
  details       JSONB  NOT NULL DEFAULT '{}'::JSONB,
  ip_address    TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_user_activities_user    ON public.user_activities(user_id);
CREATE INDEX IF NOT EXISTS idx_user_activities_type    ON public.user_activities(activity_type);
CREATE INDEX IF NOT EXISTS idx_user_activities_created ON public.user_activities(created_at DESC);

-- ---------------------------------------------------------------
-- STUDY MATERIALS (Simple file attachments, admin-managed)
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.study_materials (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title               TEXT NOT NULL,
  slug                TEXT NOT NULL UNIQUE,
  description         TEXT,
  file_path           TEXT,
  file_type           TEXT,
  storage_object_path TEXT,
  status              TEXT NOT NULL DEFAULT 'active'
    CHECK (status IN ('active', 'archived')),
  uploader_id         BIGINT REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

DROP TRIGGER IF EXISTS trg_study_materials_set_updated_at ON public.study_materials;
CREATE TRIGGER trg_study_materials_set_updated_at
  BEFORE UPDATE ON public.study_materials
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ---------------------------------------------------------------
-- ROW LEVEL SECURITY
-- ---------------------------------------------------------------

ALTER TABLE public.creator_applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_subpages       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_activities      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.study_materials      ENABLE ROW LEVEL SECURITY;

-- Creator applications: own user read/insert, admin all
DROP POLICY IF EXISTS "creator_apps_own_read" ON public.creator_applications;
CREATE POLICY "creator_apps_own_read" ON public.creator_applications FOR SELECT TO authenticated
  USING (
    public.is_admin_or_moderator()
    OR EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = creator_applications.user_id AND p.auth_user_id = auth.uid())
  );

DROP POLICY IF EXISTS "creator_apps_own_insert" ON public.creator_applications;
CREATE POLICY "creator_apps_own_insert" ON public.creator_applications FOR INSERT TO authenticated
  WITH CHECK (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = creator_applications.user_id AND p.auth_user_id = auth.uid()));

DROP POLICY IF EXISTS "creator_apps_admin_update" ON public.creator_applications;
CREATE POLICY "creator_apps_admin_update" ON public.creator_applications FOR UPDATE TO authenticated
  USING (public.is_admin_or_moderator()) WITH CHECK (public.is_admin_or_moderator());

-- Admin subpages: public read, admin write
DROP POLICY IF EXISTS "admin_subpages_public_read" ON public.admin_subpages;
CREATE POLICY "admin_subpages_public_read" ON public.admin_subpages FOR SELECT TO anon, authenticated USING (TRUE);
DROP POLICY IF EXISTS "admin_subpages_admin_write" ON public.admin_subpages;
CREATE POLICY "admin_subpages_admin_write" ON public.admin_subpages FOR ALL TO authenticated
  USING (public.is_admin_or_moderator()) WITH CHECK (public.is_admin_or_moderator());

-- User activities: admin read, system insert
DROP POLICY IF EXISTS "user_activities_admin_read" ON public.user_activities;
CREATE POLICY "user_activities_admin_read" ON public.user_activities FOR SELECT TO authenticated
  USING (public.is_admin_or_moderator());

-- Study materials: public read, admin write
DROP POLICY IF EXISTS "study_materials_public_read" ON public.study_materials;
CREATE POLICY "study_materials_public_read" ON public.study_materials FOR SELECT TO anon, authenticated USING (TRUE);
DROP POLICY IF EXISTS "study_materials_admin_write" ON public.study_materials;
CREATE POLICY "study_materials_admin_write" ON public.study_materials FOR ALL TO authenticated
  USING (public.is_admin_or_moderator()) WITH CHECK (public.is_admin_or_moderator());

-- ---------------------------------------------------------------
-- NOTIFY POSTGREST TO RELOAD SCHEMA
-- ---------------------------------------------------------------

NOTIFY pgrst, 'reload schema';
