-- =============================================================
-- MIGRATION 6: AI Test System & Usage Quotas
-- =============================================================

-- ---------------------------------------------------------------
-- UPLOADED PDFs (used as source for AI generation)
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.uploaded_pdfs (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id             BIGINT REFERENCES public.profiles(id) ON DELETE SET NULL,
  filename            TEXT   NOT NULL,
  content_type        TEXT,
  storage_object_path TEXT,
  extracted_text      TEXT,
  page_count          INTEGER,
  used_ocr            BOOLEAN NOT NULL DEFAULT FALSE,
  -- Lifecycle management
  status              TEXT NOT NULL DEFAULT 'active'
    CHECK (status IN ('active', 'expired', 'deleted')),
  expires_at          TIMESTAMPTZ,
  deleted_at          TIMESTAMPTZ,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_uploaded_pdfs_user    ON public.uploaded_pdfs(user_id);
CREATE INDEX IF NOT EXISTS idx_uploaded_pdfs_status  ON public.uploaded_pdfs(status);

-- ---------------------------------------------------------------
-- AI TESTS (Separate identity from creator programs)
-- Generated by any user; optionally made public
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.ai_tests (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       BIGINT NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  title         TEXT   NOT NULL,
  quiz_domain   TEXT   NOT NULL CHECK (quiz_domain IN ('gk', 'maths', 'passage', 'mains')),
  format_id     BIGINT REFERENCES public.question_formats(id) ON DELETE SET NULL,
  -- Source of content for generation
  source_type   TEXT   CHECK (source_type IN ('text', 'url', 'pdf', 'category')),
  source_text   TEXT,
  source_url    TEXT,
  source_pdf_id BIGINT REFERENCES public.uploaded_pdfs(id) ON DELETE SET NULL,
  -- Generation parameters
  language      TEXT   NOT NULL DEFAULT 'en' CHECK (language IN ('en', 'hi')),
  question_count INTEGER,
  ai_instruction_id BIGINT REFERENCES public.ai_instructions(id) ON DELETE SET NULL,
  -- Visibility
  is_public     BOOLEAN NOT NULL DEFAULT FALSE,
  likes_count   INTEGER NOT NULL DEFAULT 0,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ai_tests_user_id    ON public.ai_tests(user_id);
CREATE INDEX IF NOT EXISTS idx_ai_tests_domain     ON public.ai_tests(quiz_domain);
CREATE INDEX IF NOT EXISTS idx_ai_tests_public     ON public.ai_tests(is_public, created_at DESC);

DROP TRIGGER IF EXISTS trg_ai_tests_set_updated_at ON public.ai_tests;
CREATE TRIGGER trg_ai_tests_set_updated_at
  BEFORE UPDATE ON public.ai_tests
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- Category filter for AI test (when source_type = 'category')
CREATE TABLE IF NOT EXISTS public.ai_test_categories (
  ai_test_id  BIGINT NOT NULL REFERENCES public.ai_tests(id) ON DELETE CASCADE,
  category_id BIGINT NOT NULL REFERENCES public.categories(id) ON DELETE CASCADE,
  PRIMARY KEY (ai_test_id, category_id)
);

-- ---------------------------------------------------------------
-- AI TEST QUESTIONS (Individual questions within an AI test)
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.ai_test_questions (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ai_test_id    BIGINT NOT NULL REFERENCES public.ai_tests(id) ON DELETE CASCADE,
  quiz_domain   TEXT   NOT NULL CHECK (quiz_domain IN ('gk', 'maths', 'passage', 'mains')),
  -- Normalized question structure (same fields as quiz_content, stored as JSON here
  -- because AI test questions may not yet be "promoted" to official quiz pool)
  question_statement      TEXT,
  supp_question_statement TEXT,
  statements_facts        JSONB NOT NULL DEFAULT '[]'::JSONB,
  question_prompt         TEXT,
  options                 JSONB NOT NULL DEFAULT '[]'::JSONB,
  correct_answer          TEXT,
  explanation             TEXT,
  passage_title           TEXT,      -- for passage-type questions
  passage_text            TEXT,
  -- Category (for analytics tracking)
  category_id             BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
  display_order           INTEGER NOT NULL DEFAULT 0,
  is_edited               BOOLEAN NOT NULL DEFAULT FALSE,
  created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ai_test_questions_test     ON public.ai_test_questions(ai_test_id);
CREATE INDEX IF NOT EXISTS idx_ai_test_questions_category ON public.ai_test_questions(category_id);

DROP TRIGGER IF EXISTS trg_ai_test_questions_set_updated_at ON public.ai_test_questions;
CREATE TRIGGER trg_ai_test_questions_set_updated_at
  BEFORE UPDATE ON public.ai_test_questions
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ---------------------------------------------------------------
-- AI TEST ATTEMPTS & ANSWERS (Track user performance on AI tests)
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.ai_test_attempts (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ai_test_id   BIGINT NOT NULL REFERENCES public.ai_tests(id) ON DELETE CASCADE,
  user_id      BIGINT REFERENCES public.profiles(id) ON DELETE SET NULL,
  submitted_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ai_test_attempts_test    ON public.ai_test_attempts(ai_test_id);
CREATE INDEX IF NOT EXISTS idx_ai_test_attempts_user    ON public.ai_test_attempts(user_id);

CREATE TABLE IF NOT EXISTS public.ai_test_answers (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  attempt_id           BIGINT NOT NULL REFERENCES public.ai_test_attempts(id) ON DELETE CASCADE,
  ai_test_question_id  BIGINT NOT NULL REFERENCES public.ai_test_questions(id) ON DELETE CASCADE,
  selected_option      TEXT,
  is_correct           BOOLEAN,
  is_skipped           BOOLEAN NOT NULL DEFAULT FALSE,
  time_spent_secs      INTEGER,
  category_id          BIGINT REFERENCES public.categories(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_ai_test_answers_attempt  ON public.ai_test_answers(attempt_id);
CREATE INDEX IF NOT EXISTS idx_ai_test_answers_question ON public.ai_test_answers(ai_test_question_id);

-- ---------------------------------------------------------------
-- AI DRAFT QUIZZES (Admin-side: AI generates, admin reviews & promotes)
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.ai_draft_quizzes (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quiz_type         TEXT NOT NULL CHECK (quiz_type IN ('gk', 'maths', 'passage')),
  content_type      TEXT NOT NULL,
  raw_ai_response   JSONB,
  parsed_quiz_data  JSONB NOT NULL DEFAULT '{}'::JSONB,
  source_pdf_id     BIGINT REFERENCES public.uploaded_pdfs(id) ON DELETE SET NULL,
  source_url        TEXT,
  ai_instruction_id BIGINT REFERENCES public.ai_instructions(id) ON DELETE SET NULL,
  status            TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'approved', 'rejected')),
  reviewed_by       BIGINT REFERENCES public.profiles(id) ON DELETE SET NULL,
  reviewed_at       TIMESTAMPTZ,
  author_id         BIGINT NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ai_draft_quizzes_author ON public.ai_draft_quizzes(author_id);
CREATE INDEX IF NOT EXISTS idx_ai_draft_quizzes_status ON public.ai_draft_quizzes(status);

DROP TRIGGER IF EXISTS trg_ai_draft_quizzes_set_updated_at ON public.ai_draft_quizzes;
CREATE TRIGGER trg_ai_draft_quizzes_set_updated_at
  BEFORE UPDATE ON public.ai_draft_quizzes
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ---------------------------------------------------------------
-- AI GENERATED QUIZZES (User-side quick generation — not yet saved to pool)
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.ai_generated_quizzes (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      BIGINT NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  quiz_type    TEXT   NOT NULL CHECK (quiz_type IN ('gk', 'maths', 'passage')),
  payload      JSONB  NOT NULL DEFAULT '{}'::JSONB,
  is_saved     BOOLEAN NOT NULL DEFAULT FALSE,
  expires_at   TIMESTAMPTZ,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ai_generated_quizzes_user ON public.ai_generated_quizzes(user_id);

DROP TRIGGER IF EXISTS trg_ai_generated_quizzes_set_updated_at ON public.ai_generated_quizzes;
CREATE TRIGGER trg_ai_generated_quizzes_set_updated_at
  BEFORE UPDATE ON public.ai_generated_quizzes
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ---------------------------------------------------------------
-- AI PUBLIC QUIZZES (User-published AI tests, visible to community)
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.ai_public_quizzes (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     BIGINT REFERENCES public.profiles(id) ON DELETE SET NULL,
  title       TEXT  NOT NULL,
  payload     JSONB NOT NULL DEFAULT '{}'::JSONB,
  likes_count INTEGER NOT NULL DEFAULT 0,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

DROP TRIGGER IF EXISTS trg_ai_public_quizzes_set_updated_at ON public.ai_public_quizzes;
CREATE TRIGGER trg_ai_public_quizzes_set_updated_at
  BEFORE UPDATE ON public.ai_public_quizzes
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ---------------------------------------------------------------
-- AI MAINS QUESTIONS (User-generated Mains practice questions)
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.ai_mains_questions (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id          BIGINT NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  question_text    TEXT   NOT NULL,
  answer_approach  TEXT   NOT NULL DEFAULT '',
  model_answer     TEXT   NOT NULL DEFAULT '',
  word_limit       INTEGER NOT NULL DEFAULT 250,
  source_reference TEXT,
  category_id      BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
  is_saved         BOOLEAN NOT NULL DEFAULT FALSE,
  expires_at       TIMESTAMPTZ,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ai_mains_questions_user ON public.ai_mains_questions(user_id);

DROP TRIGGER IF EXISTS trg_ai_mains_questions_set_updated_at ON public.ai_mains_questions;
CREATE TRIGGER trg_ai_mains_questions_set_updated_at
  BEFORE UPDATE ON public.ai_mains_questions
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ---------------------------------------------------------------
-- AI ARTICLE DRAFTS (AI-assisted article creation queue)
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.ai_article_drafts (
  id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  raw_input_url               TEXT,
  raw_input_text              TEXT,
  source_id                   BIGINT REFERENCES public.sources(id) ON DELETE SET NULL,
  ai_generated_title          TEXT,
  ai_generated_excerpt        TEXT,
  ai_generated_content        TEXT,
  ai_suggested_subject_id     BIGINT REFERENCES public.subjects(id) ON DELETE SET NULL,
  ai_suggested_topic_id       BIGINT REFERENCES public.topics(id) ON DELETE SET NULL,
  ai_suggested_subtopic_id    BIGINT REFERENCES public.subtopics(id) ON DELETE SET NULL,
  ai_suggested_tags           JSONB NOT NULL DEFAULT '[]'::JSONB,
  status                      TEXT NOT NULL DEFAULT 'pending_review'
    CHECK (status IN ('pending_review', 'approved', 'rejected', 'published')),
  reviewed_by                 BIGINT REFERENCES public.profiles(id) ON DELETE SET NULL,
  reviewed_at                 TIMESTAMPTZ,
  review_notes                TEXT,
  published_article_id        BIGINT REFERENCES public.articles(id) ON DELETE SET NULL,
  ai_model_used               TEXT,
  ai_prompt_version           TEXT,
  generation_cost_tokens      INTEGER,
  created_by                  BIGINT REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ai_article_drafts_status ON public.ai_article_drafts(status);

DROP TRIGGER IF EXISTS trg_ai_article_drafts_set_updated_at ON public.ai_article_drafts;
CREATE TRIGGER trg_ai_article_drafts_set_updated_at
  BEFORE UPDATE ON public.ai_article_drafts
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ---------------------------------------------------------------
-- AI USAGE QUOTAS (track per-user per-domain monthly limits)
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.ai_usage_quotas (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      BIGINT NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  quiz_domain  TEXT   NOT NULL,
  period_start DATE   NOT NULL,
  used_count   INTEGER NOT NULL DEFAULT 0,
  limit_count  INTEGER NOT NULL DEFAULT 10,  -- overridden by subscription plan
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (user_id, quiz_domain, period_start)
);

CREATE INDEX IF NOT EXISTS idx_ai_usage_quotas_user   ON public.ai_usage_quotas(user_id);
CREATE INDEX IF NOT EXISTS idx_ai_usage_quotas_period ON public.ai_usage_quotas(period_start);

DROP TRIGGER IF EXISTS trg_ai_usage_quotas_set_updated_at ON public.ai_usage_quotas;
CREATE TRIGGER trg_ai_usage_quotas_set_updated_at
  BEFORE UPDATE ON public.ai_usage_quotas
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- General AI generation event log (for auditing/debugging)
CREATE TABLE IF NOT EXISTS public.ai_generation_usage (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bucket     TEXT   NOT NULL,  -- e.g. 'gk_quiz', 'mains_question'
  user_id    BIGINT NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  payload    JSONB  NOT NULL DEFAULT '{}'::JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ai_gen_usage_user ON public.ai_generation_usage(user_id);
CREATE INDEX IF NOT EXISTS idx_ai_gen_usage_created ON public.ai_generation_usage(created_at DESC);

-- ---------------------------------------------------------------
-- ROW LEVEL SECURITY
-- ---------------------------------------------------------------

ALTER TABLE public.uploaded_pdfs       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_tests            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_test_categories  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_test_questions   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_test_attempts    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_test_answers     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_draft_quizzes    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_generated_quizzes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_public_quizzes   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_mains_questions  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_article_drafts   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_usage_quotas     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_generation_usage ENABLE ROW LEVEL SECURITY;

-- Uploaded PDFs
DROP POLICY IF EXISTS "uploaded_pdfs_own" ON public.uploaded_pdfs;
CREATE POLICY "uploaded_pdfs_own" ON public.uploaded_pdfs FOR ALL TO authenticated
  USING (
    public.is_admin_or_moderator()
    OR EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = uploaded_pdfs.user_id AND p.auth_user_id = auth.uid())
  )
  WITH CHECK (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = uploaded_pdfs.user_id AND p.auth_user_id = auth.uid()));

-- AI Tests — owner or public read
DROP POLICY IF EXISTS "ai_tests_public_read" ON public.ai_tests;
CREATE POLICY "ai_tests_public_read" ON public.ai_tests
  FOR SELECT TO anon, authenticated USING (is_public = TRUE);

DROP POLICY IF EXISTS "ai_tests_own" ON public.ai_tests;
CREATE POLICY "ai_tests_own" ON public.ai_tests FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = ai_tests.user_id AND p.auth_user_id = auth.uid()))
  WITH CHECK (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = ai_tests.user_id AND p.auth_user_id = auth.uid()));

-- AI Test Questions — public if test is public, else owner only
DROP POLICY IF EXISTS "ai_test_questions_read" ON public.ai_test_questions;
CREATE POLICY "ai_test_questions_read" ON public.ai_test_questions
  FOR SELECT TO anon, authenticated
  USING (EXISTS (SELECT 1 FROM public.ai_tests t WHERE t.id = ai_test_questions.ai_test_id AND (t.is_public = TRUE OR EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = t.user_id AND p.auth_user_id = auth.uid()))));

DROP POLICY IF EXISTS "ai_test_questions_own_write" ON public.ai_test_questions;
CREATE POLICY "ai_test_questions_own_write" ON public.ai_test_questions
  FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM public.ai_tests t JOIN public.profiles p ON p.id = t.user_id WHERE t.id = ai_test_questions.ai_test_id AND p.auth_user_id = auth.uid()))
  WITH CHECK (EXISTS (SELECT 1 FROM public.ai_tests t JOIN public.profiles p ON p.id = t.user_id WHERE t.id = ai_test_questions.ai_test_id AND p.auth_user_id = auth.uid()));

-- AI Test Attempts — own
DROP POLICY IF EXISTS "ai_test_attempts_own" ON public.ai_test_attempts;
CREATE POLICY "ai_test_attempts_own" ON public.ai_test_attempts FOR ALL TO authenticated
  USING (user_id IS NULL OR EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = ai_test_attempts.user_id AND p.auth_user_id = auth.uid()))
  WITH CHECK (user_id IS NULL OR EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = ai_test_attempts.user_id AND p.auth_user_id = auth.uid()));

-- AI Test Answers — own
DROP POLICY IF EXISTS "ai_test_answers_own" ON public.ai_test_answers;
CREATE POLICY "ai_test_answers_own" ON public.ai_test_answers FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM public.ai_test_attempts a JOIN public.profiles p ON p.id = a.user_id WHERE a.id = ai_test_answers.attempt_id AND p.auth_user_id = auth.uid()))
  WITH CHECK (EXISTS (SELECT 1 FROM public.ai_test_attempts a JOIN public.profiles p ON p.id = a.user_id WHERE a.id = ai_test_answers.attempt_id AND p.auth_user_id = auth.uid()));

-- AI Generated/Mains Questions — own
DROP POLICY IF EXISTS "ai_generated_quizzes_own" ON public.ai_generated_quizzes;
CREATE POLICY "ai_generated_quizzes_own" ON public.ai_generated_quizzes FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = ai_generated_quizzes.user_id AND p.auth_user_id = auth.uid()))
  WITH CHECK (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = ai_generated_quizzes.user_id AND p.auth_user_id = auth.uid()));

DROP POLICY IF EXISTS "ai_mains_questions_own" ON public.ai_mains_questions;
CREATE POLICY "ai_mains_questions_own" ON public.ai_mains_questions FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = ai_mains_questions.user_id AND p.auth_user_id = auth.uid()))
  WITH CHECK (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = ai_mains_questions.user_id AND p.auth_user_id = auth.uid()));

-- AI Public Quizzes — public read, owner write
DROP POLICY IF EXISTS "ai_public_quizzes_public_read" ON public.ai_public_quizzes;
CREATE POLICY "ai_public_quizzes_public_read" ON public.ai_public_quizzes
  FOR SELECT TO anon, authenticated USING (TRUE);

-- Usage Quotas — own only
DROP POLICY IF EXISTS "ai_usage_quotas_own" ON public.ai_usage_quotas;
CREATE POLICY "ai_usage_quotas_own" ON public.ai_usage_quotas FOR ALL TO authenticated
  USING (
    public.is_admin_or_moderator()
    OR EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = ai_usage_quotas.user_id AND p.auth_user_id = auth.uid())
  )
  WITH CHECK (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = ai_usage_quotas.user_id AND p.auth_user_id = auth.uid()));

-- Draft quizzes — admin/moderator, and creator-own
DROP POLICY IF EXISTS "ai_draft_quizzes_own_or_admin" ON public.ai_draft_quizzes;
CREATE POLICY "ai_draft_quizzes_own_or_admin" ON public.ai_draft_quizzes FOR ALL TO authenticated
  USING (
    public.is_admin_or_moderator()
    OR EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = ai_draft_quizzes.author_id AND p.auth_user_id = auth.uid())
  )
  WITH CHECK (
    public.is_admin_or_moderator()
    OR EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = ai_draft_quizzes.author_id AND p.auth_user_id = auth.uid())
  );

-- Article drafts — admin/moderator
DROP POLICY IF EXISTS "ai_article_drafts_admin" ON public.ai_article_drafts;
CREATE POLICY "ai_article_drafts_admin" ON public.ai_article_drafts FOR ALL TO authenticated
  USING (public.is_admin_or_moderator())
  WITH CHECK (public.is_admin_or_moderator());

-- Generation usage log — admin read, own insert
DROP POLICY IF EXISTS "ai_generation_usage_own_insert" ON public.ai_generation_usage;
CREATE POLICY "ai_generation_usage_own_insert" ON public.ai_generation_usage FOR INSERT TO authenticated
  WITH CHECK (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = ai_generation_usage.user_id AND p.auth_user_id = auth.uid()));

DROP POLICY IF EXISTS "ai_generation_usage_admin_read" ON public.ai_generation_usage;
CREATE POLICY "ai_generation_usage_admin_read" ON public.ai_generation_usage FOR SELECT TO authenticated
  USING (public.is_admin_or_moderator());
