-- Supabase Schema Migration (Phase 1: Premium Systems)
-- This schema consolidates multiple category and quiz tables into simplified, unified tables.

-- Enable required extensions
create extension if not exists ltree;

-- 1. Unified Categories Table
-- Replaces: PremiumGKCategory, PremiumMathsCategory, PremiumPassageCategory, SharedCategory, etc.
create type category_type as enum (
  'gk', 
  'maths', 
  'passage', 
  'video', 
  'document', 
  'collection', 
  'folder'
);

create table categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text unique, -- For SEO friendly URLs if needed
  type category_type not null default 'gk',
  description text,
  parent_id bigint references categories(id) on delete cascade,
  path ltree, -- Optional: For efficient hierarchical queries (requires ltree extension)
  is_active boolean default true,
  meta jsonb default '{}'::jsonb, -- Store extra type-specific fields here
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index ix_categories_parent_id on categories(parent_id);
create index ix_categories_type on categories(type);

-- 1b. Exams + Category-Exam Mapping
-- Supports exam-scoped premium category trees.
create table exams (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text unique,
  description text,
  is_active boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table category_exams (
  category_id bigint not null references categories(id) on delete cascade,
  exam_id bigint not null references exams(id) on delete cascade,
  created_at timestamptz default now(),
  primary key (category_id, exam_id)
);

create index ix_category_exams_exam_id on category_exams(exam_id);

-- 2. Unified Content Items Table
-- Replaces: GKQuiz, MathQuiz, PassageQuiz, Question, Note, VideoLink, PDF
create type content_type as enum (
  'quiz_gk', 
  'quiz_maths', 
  'quiz_passage', 
  'question', 
  'note', 
  'video_link', 
  'pdf_file',
  'article'
);

create table content_items (
  id bigint generated by default as identity primary key,
  title text, -- Optional title (e.g. for a note or video)
  type content_type not null,
  
  -- The core content payload. 
  -- For Quizzes: { "question": "...", "options": [...], "answer": "..." }
  -- For Notes: { "body": "..." }
  -- For Videos: { "url": "...", "provider": "youtube" }
  data jsonb not null default '{}'::jsonb,
  
  -- Search optimization (optional vector column can be added later for AI search)
  search_text tsvector generated always as (to_tsvector('english', title || ' ' || (data->>'question') || ' ' || (data->>'body'))) stored,
  
  is_active boolean default true,
  author_id uuid references auth.users(id), -- Links to Supabase Auth User
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index ix_content_items_type on content_items(type);
create index ix_content_items_search on content_items using gin(search_text);

-- 3. Unified Collections Table
-- Replaces: CourseCollection, PremiumCollection, Playlist
create type collection_type as enum (
  'test_series', 
  'question_bank', 
  'crash_course', 
  'notes_bundle'
);

create table collections (
  id bigint generated by default as identity primary key,
  title text not null, -- Maps to 'name'
  slug text unique,
  description text,
  type collection_type not null default 'test_series',
  
  -- Display & Access
  thumbnail_url text, -- Maps to 'image_url'
  is_premium boolean default true, -- Maps to 'is_paid'
  is_public boolean default false, -- Maps to 'is_public'
  price numeric(10, 2) default 0.00,
  
  -- State
  is_active boolean default true,
  is_finalized boolean default false,
  
  -- Hierarchical structure support
  parent_id bigint references collections(id) on delete set null,
  
  -- Flexible Metadata (Stores source_list, admin_subpage_id, etc.)
  meta jsonb default '{}'::jsonb, 
  
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 4. Collection Items (One-to-Many / Many-to-Many Linking)
-- Links Content Items to Collections with ordering
create table collection_items (
  id bigint generated by default as identity primary key,
  collection_id bigint references collections(id) on delete cascade,
  content_item_id bigint references content_items(id) on delete cascade,
  "order" int not null default 0,
  section_title text, -- Optional: Group items within a collection (e.g. "Week 1", "History Section")
  created_at timestamptz default now()
);

create index ix_collection_items_collection_id on collection_items(collection_id);
create index ix_collection_items_content_item_id on collection_items(content_item_id);

-- 5. AI System Instructions (Unified)
-- Replaces: AISystemInstruction, PremiumAIQuizInstruction
create type ai_instruction_type as enum (
  'quiz_gen', 
  'summary', 
  'explanation', 
  'grading'
);

create table ai_instructions (
  id bigint generated by default as identity primary key,
  name text not null, -- e.g. "Standard GK Quiz Generator"
  type ai_instruction_type not null,
  system_prompt text not null, 
  user_prompt_template text, -- Optional template to inject user input
  input_schema jsonb default '{}'::jsonb, -- Expected input format
  output_schema jsonb default '{}'::jsonb, -- Expected output format (JSON mode)
  is_active boolean default true,
  created_at timestamptz default now()
);

-- 6. Premium AI Example Analyses
-- Reusable style/format analyses for premium AI quiz generation.
create table premium_ai_example_analyses (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  tag_level1 text,
  tag_level2 text,
  content_type text not null,
  style_profile jsonb not null default '{}'::jsonb,
  example_questions jsonb not null default '[]'::jsonb,
  tags jsonb not null default '[]'::jsonb,
  is_active boolean default true,
  author_id uuid references auth.users(id),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index ix_premium_ai_example_analyses_content_type on premium_ai_example_analyses(content_type);

-- RLS Policies (Row Level Security)
-- 1. Enable RLS
alter table categories enable row level security;
alter table exams enable row level security;
alter table category_exams enable row level security;
alter table content_items enable row level security;
alter table collections enable row level security;
alter table collection_items enable row level security;
alter table ai_instructions enable row level security;
alter table premium_ai_example_analyses enable row level security;

-- 2. Basic Policies
-- Read access for public
create policy "Allow public read active categories" on categories for select using (is_active = true);
create policy "Allow public read active exams" on exams for select using (is_active = true);
create policy "Allow public read category exams" on category_exams for select using (true);
create policy "Allow public read active collections" on collections for select using (is_active = true);
create policy "Allow public read active content" on content_items for select using (is_active = true);
create policy "Allow public read collection items" on collection_items for select using (true);
create policy "Allow public read active premium ai example analyses" on premium_ai_example_analyses for select using (is_active = true);

-- Full access for authenticated users (Curators/Admins)
-- In a production app, you would restrict this to only users with 'admin' role
create policy "Enable all for authenticated users on collections" on collections for all using (auth.role() = 'authenticated');
create policy "Enable all for authenticated users on categories" on categories for all using (auth.role() = 'authenticated');
create policy "Enable all for authenticated users on exams" on exams for all using (auth.role() = 'authenticated');
create policy "Enable all for authenticated users on category_exams" on category_exams for all using (auth.role() = 'authenticated');
create policy "Enable all for authenticated users on content_items" on content_items for all using (auth.role() = 'authenticated');
create policy "Enable all for authenticated users on collection_items" on collection_items for all using (auth.role() = 'authenticated');
create policy "Enable all for authenticated users on ai_instructions" on ai_instructions for all using (auth.role() = 'authenticated');
create policy "Enable all for authenticated users on premium_ai_example_analyses" on premium_ai_example_analyses for all using (auth.role() = 'authenticated');

