-- Idempotent patch for partial supa_back schema states.
-- Use this when categories/content_items/collections already exist
-- but newer premium tables are missing.

-- Exams and category-exam mapping
create table if not exists exams (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text unique,
  description text,
  is_active boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists category_exams (
  category_id bigint not null references categories(id) on delete cascade,
  exam_id bigint not null references exams(id) on delete cascade,
  created_at timestamptz default now(),
  primary key (category_id, exam_id)
);

create index if not exists ix_category_exams_exam_id on category_exams(exam_id);

alter table exams enable row level security;
alter table category_exams enable row level security;

drop policy if exists "Allow public read active exams" on exams;
create policy "Allow public read active exams"
  on exams for select
  using (is_active = true);

drop policy if exists "Allow public read category exams" on category_exams;
create policy "Allow public read category exams"
  on category_exams for select
  using (true);

drop policy if exists "Enable all for authenticated users on exams" on exams;
create policy "Enable all for authenticated users on exams"
  on exams for all
  using (auth.role() = 'authenticated');

drop policy if exists "Enable all for authenticated users on category_exams" on category_exams;
create policy "Enable all for authenticated users on category_exams"
  on category_exams for all
  using (auth.role() = 'authenticated');

-- Premium AI example analyses
create table if not exists premium_ai_example_analyses (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  tag_level1 text,
  tag_level2 text,
  content_type text not null,
  style_profile jsonb not null default '{}'::jsonb,
  example_questions jsonb not null default '[]'::jsonb,
  tags jsonb not null default '[]'::jsonb,
  is_active boolean default true,
  author_id uuid references auth.users(id),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists ix_premium_ai_example_analyses_content_type
  on premium_ai_example_analyses(content_type);

alter table premium_ai_example_analyses enable row level security;

drop policy if exists "Allow public read active premium ai example analyses" on premium_ai_example_analyses;
create policy "Allow public read active premium ai example analyses"
  on premium_ai_example_analyses for select
  using (is_active = true);

drop policy if exists "Enable all for authenticated users on premium_ai_example_analyses" on premium_ai_example_analyses;
create policy "Enable all for authenticated users on premium_ai_example_analyses"
  on premium_ai_example_analyses for all
  using (auth.role() = 'authenticated');

-- Premium AI draft quizzes
create table if not exists premium_ai_draft_quizzes (
  id bigint generated by default as identity primary key,
  quiz_kind text not null check (quiz_kind in ('gk', 'maths', 'passage')),
  content_type text not null,
  parsed_quiz_data jsonb not null default '{}'::jsonb,
  category_ids jsonb not null default '[]'::jsonb,
  exam_id bigint references exams(id) on delete set null,
  ai_instruction_id bigint references ai_instructions(id) on delete set null,
  source_url text,
  source_pdf_id bigint,
  notes text,
  author_id uuid references auth.users(id) on delete cascade not null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists ix_premium_ai_draft_quizzes_content_type
  on premium_ai_draft_quizzes(content_type);

create index if not exists ix_premium_ai_draft_quizzes_quiz_kind
  on premium_ai_draft_quizzes(quiz_kind);

create index if not exists ix_premium_ai_draft_quizzes_author_id
  on premium_ai_draft_quizzes(author_id);

alter table premium_ai_draft_quizzes enable row level security;

drop policy if exists "Allow read premium ai draft quizzes" on premium_ai_draft_quizzes;
create policy "Allow read premium ai draft quizzes"
  on premium_ai_draft_quizzes for select
  using (auth.uid() = author_id);

drop policy if exists "Allow write premium ai draft quizzes" on premium_ai_draft_quizzes;
create policy "Allow write premium ai draft quizzes"
  on premium_ai_draft_quizzes for insert
  with check (auth.uid() = author_id);

drop policy if exists "Allow update premium ai draft quizzes" on premium_ai_draft_quizzes;
create policy "Allow update premium ai draft quizzes"
  on premium_ai_draft_quizzes for update
  using (auth.uid() = author_id)
  with check (auth.uid() = author_id);

drop policy if exists "Allow delete premium ai draft quizzes" on premium_ai_draft_quizzes;
create policy "Allow delete premium ai draft quizzes"
  on premium_ai_draft_quizzes for delete
  using (auth.uid() = author_id);
