-- Discussion speaker request queue for live Agora classes

create table if not exists discussion_speaker_requests (
  id bigint generated by default as identity primary key,
  scope_type text not null check (scope_type in ('series', 'test')),
  scope_id bigint not null,
  series_id bigint references test_series(id) on delete cascade not null,
  discussion_key text not null check (discussion_key in ('final_discussion', 'test_discussion')),
  discussion_channel text not null,
  user_id uuid references auth.users(id) on delete cascade not null,
  display_name text not null,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected', 'withdrawn', 'removed')),
  note text,
  requested_at timestamptz not null default now(),
  resolved_at timestamptz,
  resolved_by_user_id uuid references auth.users(id) on delete set null,
  meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists ix_discussion_speaker_requests_scope
  on discussion_speaker_requests(scope_type, scope_id, discussion_key);

create index if not exists ix_discussion_speaker_requests_channel
  on discussion_speaker_requests(discussion_channel);

create index if not exists ix_discussion_speaker_requests_user
  on discussion_speaker_requests(user_id, status);

create unique index if not exists ux_discussion_speaker_requests_active
  on discussion_speaker_requests(scope_type, scope_id, discussion_key, user_id)
  where status in ('pending', 'approved');

alter table discussion_speaker_requests enable row level security;

drop policy if exists "Enable all for authenticated users on discussion_speaker_requests" on discussion_speaker_requests;
create policy "Enable all for authenticated users on discussion_speaker_requests"
  on discussion_speaker_requests
  for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'discussion_speaker_requests'
  ) then
    alter publication supabase_realtime add table discussion_speaker_requests;
  end if;
end
$$;
