create table if not exists user_ai_quiz_hints (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) not null,
  quiz_kind text not null check (quiz_kind in ('gk', 'maths', 'passage')),
  hints jsonb not null default '[]'::jsonb,
  recent_questions jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, quiz_kind)
);

create index if not exists ix_user_ai_quiz_hints_user_kind
  on user_ai_quiz_hints(user_id, quiz_kind);

alter table user_ai_quiz_hints enable row level security;

drop policy if exists "Users can view their own quiz hints" on user_ai_quiz_hints;
create policy "Users can view their own quiz hints" on user_ai_quiz_hints
  for select using (auth.uid() = user_id);

drop policy if exists "Users can insert their own quiz hints" on user_ai_quiz_hints;
create policy "Users can insert their own quiz hints" on user_ai_quiz_hints
  for insert with check (auth.uid() = user_id);

drop policy if exists "Users can update their own quiz hints" on user_ai_quiz_hints;
create policy "Users can update their own quiz hints" on user_ai_quiz_hints
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
