create table if not exists collection_challenge_links (
  id bigint generated by default as identity primary key,
  collection_id bigint references collections(id) not null,
  owner_user_id uuid references auth.users(id) not null,
  token_hash text not null unique,
  title text not null,
  description text,
  is_active boolean not null default true,
  allow_anonymous boolean not null default true,
  require_login boolean not null default false,
  max_attempts_per_participant int not null default 3,
  total_attempts int not null default 0,
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists ix_collection_challenge_links_collection_id
  on collection_challenge_links(collection_id);
create index if not exists ix_collection_challenge_links_owner_user_id
  on collection_challenge_links(owner_user_id);
create index if not exists ix_collection_challenge_links_expires_at
  on collection_challenge_links(expires_at);

create table if not exists collection_challenge_attempts (
  id bigint generated by default as identity primary key,
  challenge_id bigint references collection_challenge_links(id) on delete cascade not null,
  collection_id bigint references collections(id) not null,
  participant_user_id uuid references auth.users(id),
  participant_name text not null,
  participant_key text not null,
  score int not null,
  total_questions int not null,
  correct_answers int not null,
  incorrect_answers int not null,
  unanswered int not null,
  details jsonb not null default '[]'::jsonb,
  category_wise_results jsonb not null default '[]'::jsonb,
  collection_title text,
  created_at timestamptz not null default now()
);

create index if not exists ix_collection_challenge_attempts_challenge_id
  on collection_challenge_attempts(challenge_id);
create index if not exists ix_collection_challenge_attempts_participant_key
  on collection_challenge_attempts(participant_key);
create index if not exists ix_collection_challenge_attempts_score
  on collection_challenge_attempts(challenge_id, score desc, correct_answers desc, created_at asc);

alter table collection_challenge_links enable row level security;
alter table collection_challenge_attempts enable row level security;

drop policy if exists "Owners can view challenge links" on collection_challenge_links;
create policy "Owners can view challenge links" on collection_challenge_links
  for select using (auth.uid() = owner_user_id);

drop policy if exists "Owners can insert challenge links" on collection_challenge_links;
create policy "Owners can insert challenge links" on collection_challenge_links
  for insert with check (auth.uid() = owner_user_id);

drop policy if exists "Owners can update challenge links" on collection_challenge_links;
create policy "Owners can update challenge links" on collection_challenge_links
  for update using (auth.uid() = owner_user_id) with check (auth.uid() = owner_user_id);

drop policy if exists "Owners can view challenge attempts" on collection_challenge_attempts;
create policy "Owners can view challenge attempts" on collection_challenge_attempts
  for select using (
    exists (
      select 1
      from collection_challenge_links l
      where l.id = challenge_id
      and l.owner_user_id = auth.uid()
    )
    or participant_user_id = auth.uid()
  );

drop policy if exists "Users can insert own challenge attempts" on collection_challenge_attempts;
create policy "Users can insert own challenge attempts" on collection_challenge_attempts
  for insert with check (
    participant_user_id is null
    or participant_user_id = auth.uid()
  );
