-- Uploaded PDF storage for AI quiz generation source content.

create table if not exists uploaded_pdfs (
  id bigint generated by default as identity primary key,
  filename text not null,
  extracted_text text not null default '',
  uploader_id uuid references auth.users(id) on delete cascade not null,
  page_count int,
  used_ocr boolean not null default false,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null
);

create index if not exists ix_uploaded_pdfs_uploader_id
  on uploaded_pdfs(uploader_id);

create index if not exists ix_uploaded_pdfs_expires_at
  on uploaded_pdfs(expires_at);

alter table uploaded_pdfs enable row level security;

drop policy if exists "Users can read their uploaded PDFs" on uploaded_pdfs;
create policy "Users can read their uploaded PDFs"
  on uploaded_pdfs for select
  using (auth.uid() = uploader_id);

drop policy if exists "Users can insert their uploaded PDFs" on uploaded_pdfs;
create policy "Users can insert their uploaded PDFs"
  on uploaded_pdfs for insert
  with check (auth.uid() = uploader_id);

drop policy if exists "Users can delete their uploaded PDFs" on uploaded_pdfs;
create policy "Users can delete their uploaded PDFs"
  on uploaded_pdfs for delete
  using (auth.uid() = uploader_id);
