-- Test Series + Mains Copy Checking + Mentorship System

create table if not exists test_series (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  cover_image_url text,
  provider_user_id uuid references auth.users(id) not null,
  series_kind text not null default 'mains',
  access_type text not null default 'subscription',
  price numeric(10, 2) not null default 0,
  is_public boolean not null default false,
  is_active boolean not null default true,
  meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists ix_test_series_provider on test_series(provider_user_id);
create index if not exists ix_test_series_kind on test_series(series_kind);
create index if not exists ix_test_series_public_active on test_series(is_public, is_active);

alter table collections
  add column if not exists series_id bigint references test_series(id) on delete set null;

alter table collections
  add column if not exists series_order int not null default 0;

create index if not exists ix_collections_series_id on collections(series_id);
create index if not exists ix_collections_series_order on collections(series_id, series_order);

create table if not exists test_series_enrollments (
  id bigint generated by default as identity primary key,
  series_id bigint references test_series(id) on delete cascade not null,
  user_id uuid references auth.users(id) not null,
  status text not null default 'active',
  access_source text not null default 'subscription',
  subscribed_until timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(series_id, user_id)
);

create index if not exists ix_test_series_enrollments_user on test_series_enrollments(user_id);
create index if not exists ix_test_series_enrollments_series on test_series_enrollments(series_id);

create table if not exists mains_test_copy_submissions (
  id bigint generated by default as identity primary key,
  series_id bigint references test_series(id) on delete set null,
  test_collection_id bigint references collections(id) on delete cascade not null,
  user_id uuid references auth.users(id) not null,
  answer_pdf_url text not null,
  status text not null default 'submitted',
  provider_eta_hours int,
  provider_eta_text text,
  provider_note text,
  checked_copy_pdf_url text,
  total_marks numeric(8, 2),
  ai_total_score numeric(8, 2),
  submitted_at timestamptz not null default now(),
  eta_set_at timestamptz,
  checked_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists ix_mains_copy_submissions_series on mains_test_copy_submissions(series_id);
create index if not exists ix_mains_copy_submissions_test on mains_test_copy_submissions(test_collection_id);
create index if not exists ix_mains_copy_submissions_user on mains_test_copy_submissions(user_id);
create index if not exists ix_mains_copy_submissions_status on mains_test_copy_submissions(status);

create table if not exists mains_test_copy_marks (
  id bigint generated by default as identity primary key,
  submission_id bigint references mains_test_copy_submissions(id) on delete cascade not null,
  question_item_id bigint,
  question_number int,
  marks_awarded numeric(8, 2) not null,
  max_marks numeric(8, 2) not null default 10.0,
  remark text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists ix_mains_copy_marks_submission on mains_test_copy_marks(submission_id);
create index if not exists ix_mains_copy_marks_question_item on mains_test_copy_marks(question_item_id);

create table if not exists mentorship_entitlements (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) not null,
  sessions_remaining int not null default 0,
  valid_until timestamptz,
  source text not null default 'payment',
  note text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists ix_mentorship_entitlements_user on mentorship_entitlements(user_id);
create index if not exists ix_mentorship_entitlements_active on mentorship_entitlements(user_id, is_active);

create table if not exists mentorship_slots (
  id bigint generated by default as identity primary key,
  provider_user_id uuid references auth.users(id) not null,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  mode text not null default 'video',
  max_bookings int not null default 1,
  booked_count int not null default 0,
  is_active boolean not null default true,
  meeting_link text,
  title text,
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists ix_mentorship_slots_provider on mentorship_slots(provider_user_id);
create index if not exists ix_mentorship_slots_time on mentorship_slots(starts_at, ends_at);
create index if not exists ix_mentorship_slots_active on mentorship_slots(is_active);

create table if not exists mentorship_requests (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) not null,
  provider_user_id uuid references auth.users(id) not null,
  series_id bigint references test_series(id) on delete set null,
  test_collection_id bigint references collections(id) on delete set null,
  submission_id bigint references mains_test_copy_submissions(id) on delete set null,
  preferred_mode text not null default 'video',
  note text,
  status text not null default 'requested',
  scheduled_slot_id bigint references mentorship_slots(id) on delete set null,
  requested_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  meta jsonb not null default '{}'::jsonb
);

create index if not exists ix_mentorship_requests_user on mentorship_requests(user_id);
create index if not exists ix_mentorship_requests_provider on mentorship_requests(provider_user_id);
create index if not exists ix_mentorship_requests_status on mentorship_requests(status);
create index if not exists ix_mentorship_requests_series on mentorship_requests(series_id);

create table if not exists mentorship_sessions (
  id bigint generated by default as identity primary key,
  request_id bigint references mentorship_requests(id) on delete cascade not null unique,
  slot_id bigint references mentorship_slots(id) on delete set null,
  provider_user_id uuid references auth.users(id) not null,
  user_id uuid references auth.users(id) not null,
  mode text not null default 'video',
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  meeting_link text,
  copy_attachment_url text,
  summary text,
  status text not null default 'scheduled',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists ix_mentorship_sessions_provider on mentorship_sessions(provider_user_id);
create index if not exists ix_mentorship_sessions_user on mentorship_sessions(user_id);
create index if not exists ix_mentorship_sessions_status on mentorship_sessions(status);

alter table test_series enable row level security;
alter table test_series_enrollments enable row level security;
alter table mains_test_copy_submissions enable row level security;
alter table mains_test_copy_marks enable row level security;
alter table mentorship_entitlements enable row level security;
alter table mentorship_slots enable row level security;
alter table mentorship_requests enable row level security;
alter table mentorship_sessions enable row level security;

drop policy if exists "Enable all for authenticated users on test_series" on test_series;
create policy "Enable all for authenticated users on test_series"
  on test_series for all using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

drop policy if exists "Enable all for authenticated users on test_series_enrollments" on test_series_enrollments;
create policy "Enable all for authenticated users on test_series_enrollments"
  on test_series_enrollments for all using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

drop policy if exists "Enable all for authenticated users on mains_test_copy_submissions" on mains_test_copy_submissions;
create policy "Enable all for authenticated users on mains_test_copy_submissions"
  on mains_test_copy_submissions for all using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

drop policy if exists "Enable all for authenticated users on mains_test_copy_marks" on mains_test_copy_marks;
create policy "Enable all for authenticated users on mains_test_copy_marks"
  on mains_test_copy_marks for all using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

drop policy if exists "Enable all for authenticated users on mentorship_entitlements" on mentorship_entitlements;
create policy "Enable all for authenticated users on mentorship_entitlements"
  on mentorship_entitlements for all using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

drop policy if exists "Enable all for authenticated users on mentorship_slots" on mentorship_slots;
create policy "Enable all for authenticated users on mentorship_slots"
  on mentorship_slots for all using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

drop policy if exists "Enable all for authenticated users on mentorship_requests" on mentorship_requests;
create policy "Enable all for authenticated users on mentorship_requests"
  on mentorship_requests for all using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

drop policy if exists "Enable all for authenticated users on mentorship_sessions" on mentorship_sessions;
create policy "Enable all for authenticated users on mentorship_sessions"
  on mentorship_sessions for all using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');
