-- Creator/Mentor Profile + Subscription Scaffold

create table if not exists creator_mentor_profiles (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null unique,
  role text not null default 'mentor',
  display_name text not null,
  headline text,
  bio text,
  years_experience int,
  city text,
  profile_image_url text,
  is_verified boolean not null default false,
  highlights jsonb not null default '[]'::jsonb,
  credentials jsonb not null default '[]'::jsonb,
  specialization_tags jsonb not null default '[]'::jsonb,
  languages jsonb not null default '[]'::jsonb,
  contact_url text,
  public_email text,
  is_public boolean not null default true,
  is_active boolean not null default true,
  meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ck_creator_mentor_profiles_role
    check (role in ('provider', 'institute', 'mentor', 'creator'))
);

create index if not exists ix_creator_mentor_profiles_role on creator_mentor_profiles(role);
create index if not exists ix_creator_mentor_profiles_public_active on creator_mentor_profiles(is_public, is_active);
create index if not exists ix_creator_mentor_profiles_verified on creator_mentor_profiles(is_verified);

create table if not exists subscription_plans (
  id text primary key,
  name text not null,
  description text,
  price numeric(10, 2) not null default 0,
  currency text not null default 'INR',
  billing_cycle text not null default 'monthly',
  is_active boolean not null default true,
  features jsonb not null default '[]'::jsonb,
  meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists user_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  plan_id text references subscription_plans(id) on delete set null,
  status text not null default 'inactive',
  valid_until timestamptz,
  source text,
  meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists ix_user_subscriptions_user on user_subscriptions(user_id);
create index if not exists ix_user_subscriptions_status on user_subscriptions(status);

insert into subscription_plans (id, name, description, price, currency, billing_cycle, is_active, features, meta)
values
  (
    'starter',
    'Starter',
    'Entry plan scaffold for AI tools and practice workflow.',
    0,
    'INR',
    'monthly',
    true,
    '["AI quiz generation access","Create and attempt personal tests","Basic mentorship request flow"]'::jsonb,
    '{"placeholder": true}'::jsonb
  ),
  (
    'pro',
    'Pro',
    'Paid plan scaffold for advanced limits and premium flows.',
    999,
    'INR',
    'monthly',
    true,
    '["Higher AI usage limits","Premium Prelims + Mains series access","Priority mentorship handling"]'::jsonb,
    '{"placeholder": true}'::jsonb
  )
on conflict (id) do nothing;

alter table creator_mentor_profiles enable row level security;
alter table subscription_plans enable row level security;
alter table user_subscriptions enable row level security;

drop policy if exists "Enable all for authenticated users on creator_mentor_profiles" on creator_mentor_profiles;
create policy "Enable all for authenticated users on creator_mentor_profiles"
  on creator_mentor_profiles
  for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

drop policy if exists "Enable all for authenticated users on subscription_plans" on subscription_plans;
create policy "Enable all for authenticated users on subscription_plans"
  on subscription_plans
  for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

drop policy if exists "Enable all for authenticated users on user_subscriptions" on user_subscriptions;
create policy "Enable all for authenticated users on user_subscriptions"
  on user_subscriptions
  for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');
