-- Premium AI draft quiz storage for admin generation workflow

create table if not exists premium_ai_draft_quizzes (
  id bigint generated by default as identity primary key,
  quiz_kind text not null check (quiz_kind in ('gk', 'maths', 'passage')),
  content_type text not null,
  parsed_quiz_data jsonb not null default '{}'::jsonb,
  category_ids jsonb not null default '[]'::jsonb,
  exam_id bigint references exams(id) on delete set null,
  ai_instruction_id bigint references ai_instructions(id) on delete set null,
  source_url text,
  source_pdf_id bigint,
  notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists ix_premium_ai_draft_quizzes_content_type
  on premium_ai_draft_quizzes(content_type);

create index if not exists ix_premium_ai_draft_quizzes_quiz_kind
  on premium_ai_draft_quizzes(quiz_kind);

alter table premium_ai_draft_quizzes enable row level security;

drop policy if exists "Allow read premium ai draft quizzes" on premium_ai_draft_quizzes;
create policy "Allow read premium ai draft quizzes"
  on premium_ai_draft_quizzes for select
  using (auth.role() = 'authenticated');

drop policy if exists "Allow write premium ai draft quizzes" on premium_ai_draft_quizzes;
create policy "Allow write premium ai draft quizzes"
  on premium_ai_draft_quizzes for all
  using (auth.role() = 'authenticated');
