-- Mentorship Messages System
create table if not exists mentorship_messages (
  id bigint generated by default as identity primary key,
  request_id bigint references mentorship_requests(id) on delete cascade not null,
  sender_user_id uuid references auth.users(id) on delete cascade not null,
  body text not null,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

alter table mentorship_messages enable row level security;

create policy "Enable all for authenticated users on mentorship_messages"
  on mentorship_messages
  for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');
