-- Create premium_ai_quiz_instructions table if not exists
create table if not exists premium_ai_quiz_instructions (
  id bigint generated by default as identity primary key,
  content_type text not null,
  ai_provider text default 'gemini',
  ai_model_name text default 'gemini-3-flash-preview',
  system_instructions text not null,
  input_schema jsonb default '{}'::jsonb,
  example_input text,
  output_schema jsonb default '{}'::jsonb,
  example_output jsonb default '{}'::jsonb,
  style_analysis_system_prompt text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Index on content_type for faster lookups
create index if not exists ix_premium_ai_quiz_instructions_content_type
  on premium_ai_quiz_instructions(content_type);

-- Enable RLS
alter table premium_ai_quiz_instructions enable row level security;

-- Policies
drop policy if exists "Allow public read premium_ai_quiz_instructions" on premium_ai_quiz_instructions;
create policy "Allow public read premium_ai_quiz_instructions"
  on premium_ai_quiz_instructions for select
  using (true);

drop policy if exists "Enable all for authenticated users on premium_ai_quiz_instructions" on premium_ai_quiz_instructions;
create policy "Enable all for authenticated users on premium_ai_quiz_instructions"
  on premium_ai_quiz_instructions for all
  using (auth.role() = 'authenticated');
