-- Category-driven AI source system:
-- 1) Quiz category sources (attached to existing categories table)
-- 2) Separate mains category + mains source system

create table if not exists category_ai_sources (
  id bigint generated by default as identity primary key,
  category_id bigint not null references categories(id) on delete cascade,
  source_kind text not null check (source_kind in ('text', 'url', 'content_item')),
  title text,
  source_url text,
  source_text text,
  source_content_html text,
  content_item_id bigint references content_items(id) on delete set null,
  priority int not null default 0,
  is_active boolean not null default true,
  meta jsonb not null default '{}'::jsonb,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists ix_category_ai_sources_category_id
  on category_ai_sources(category_id);

create index if not exists ix_category_ai_sources_category_active_priority
  on category_ai_sources(category_id, is_active, priority desc, id desc);

alter table category_ai_sources enable row level security;

drop policy if exists "Allow read active category ai sources" on category_ai_sources;
create policy "Allow read active category ai sources"
  on category_ai_sources for select
  using (is_active = true and auth.role() = 'authenticated');

drop policy if exists "Enable all for authenticated users on category_ai_sources" on category_ai_sources;
create policy "Enable all for authenticated users on category_ai_sources"
  on category_ai_sources for all
  using (auth.role() = 'authenticated');

create table if not exists mains_categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text unique,
  description text,
  parent_id bigint references mains_categories(id) on delete cascade,
  is_active boolean not null default true,
  meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists ix_mains_categories_parent_id
  on mains_categories(parent_id);

create index if not exists ix_mains_categories_name
  on mains_categories(name);

alter table mains_categories enable row level security;

drop policy if exists "Allow read active mains categories" on mains_categories;
create policy "Allow read active mains categories"
  on mains_categories for select
  using (is_active = true and auth.role() = 'authenticated');

drop policy if exists "Enable all for authenticated users on mains_categories" on mains_categories;
create policy "Enable all for authenticated users on mains_categories"
  on mains_categories for all
  using (auth.role() = 'authenticated');

create table if not exists mains_category_sources (
  id bigint generated by default as identity primary key,
  mains_category_id bigint not null references mains_categories(id) on delete cascade,
  source_kind text not null check (source_kind in ('text', 'url', 'content_item')),
  title text,
  source_url text,
  source_text text,
  source_content_html text,
  content_item_id bigint references content_items(id) on delete set null,
  priority int not null default 0,
  is_active boolean not null default true,
  meta jsonb not null default '{}'::jsonb,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists ix_mains_category_sources_mains_category_id
  on mains_category_sources(mains_category_id);

create index if not exists ix_mains_category_sources_active_priority
  on mains_category_sources(mains_category_id, is_active, priority desc, id desc);

alter table mains_category_sources enable row level security;

drop policy if exists "Allow read active mains category sources" on mains_category_sources;
create policy "Allow read active mains category sources"
  on mains_category_sources for select
  using (is_active = true and auth.role() = 'authenticated');

drop policy if exists "Enable all for authenticated users on mains_category_sources" on mains_category_sources;
create policy "Enable all for authenticated users on mains_category_sources"
  on mains_category_sources for all
  using (auth.role() = 'authenticated');
