-- Incremental migration: premium AI example analyses support.

create table if not exists premium_ai_example_analyses (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  tag_level1 text,
  tag_level2 text,
  content_type text not null,
  style_profile jsonb not null default '{}'::jsonb,
  example_questions jsonb not null default '[]'::jsonb,
  tags jsonb not null default '[]'::jsonb,
  is_active boolean default true,
  author_id uuid references auth.users(id),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists ix_premium_ai_example_analyses_content_type
  on premium_ai_example_analyses(content_type);

alter table premium_ai_example_analyses enable row level security;

drop policy if exists "Allow public read active premium ai example analyses" on premium_ai_example_analyses;
create policy "Allow public read active premium ai example analyses"
  on premium_ai_example_analyses for select
  using (is_active = true);

drop policy if exists "Enable all for authenticated users on premium_ai_example_analyses" on premium_ai_example_analyses;
create policy "Enable all for authenticated users on premium_ai_example_analyses"
  on premium_ai_example_analyses for all
  using (auth.role() = 'authenticated');

