-- Premium AI draft quiz storage for AI generation workflow

create table if not exists premium_ai_draft_quizzes (
  id bigint generated by default as identity primary key,
  quiz_kind text not null check (quiz_kind in ('gk', 'maths', 'passage')),
  content_type text not null,
  parsed_quiz_data jsonb not null default '{}'::jsonb,
  category_ids jsonb not null default '[]'::jsonb,
  exam_id bigint references exams(id) on delete set null,
  ai_instruction_id bigint references ai_instructions(id) on delete set null,
  source_url text,
  source_pdf_id bigint,
  notes text,
  author_id uuid references auth.users(id) on delete cascade not null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists ix_premium_ai_draft_quizzes_content_type
  on premium_ai_draft_quizzes(content_type);

create index if not exists ix_premium_ai_draft_quizzes_quiz_kind
  on premium_ai_draft_quizzes(quiz_kind);

create index if not exists ix_premium_ai_draft_quizzes_author_id
  on premium_ai_draft_quizzes(author_id);

alter table premium_ai_draft_quizzes enable row level security;

drop policy if exists "Allow read premium ai draft quizzes" on premium_ai_draft_quizzes;
create policy "Allow read premium ai draft quizzes"
  on premium_ai_draft_quizzes for select
  using (auth.uid() = author_id);

drop policy if exists "Allow write premium ai draft quizzes" on premium_ai_draft_quizzes;
create policy "Allow write premium ai draft quizzes"
  on premium_ai_draft_quizzes for insert
  with check (auth.uid() = author_id);

drop policy if exists "Allow update premium ai draft quizzes" on premium_ai_draft_quizzes;
create policy "Allow update premium ai draft quizzes"
  on premium_ai_draft_quizzes for update
  using (auth.uid() = author_id)
  with check (auth.uid() = author_id);

drop policy if exists "Allow delete premium ai draft quizzes" on premium_ai_draft_quizzes;
create policy "Allow delete premium ai draft quizzes"
  on premium_ai_draft_quizzes for delete
  using (auth.uid() = author_id);
