create table if not exists quiz_question_complaints (
  id bigint generated by default as identity primary key,
  collection_id bigint references collections(id) on delete cascade not null,
  series_id bigint references test_series(id) on delete set null,
  attempt_id bigint references user_quiz_attempts(id) on delete cascade not null,
  creator_user_id uuid references auth.users(id) on delete cascade not null,
  user_id uuid references auth.users(id) on delete cascade not null,
  question_item_id bigint not null,
  question_number int not null,
  question_text text not null,
  selected_option text,
  correct_answer text,
  complaint_text text not null,
  status text not null default 'received',
  creator_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  resolved_at timestamptz,
  constraint ck_quiz_question_complaints_status
    check (status in ('received', 'pending', 'resolved'))
);

create unique index if not exists ux_quiz_question_complaints_attempt_question_user
  on quiz_question_complaints(attempt_id, question_item_id, user_id);

create index if not exists ix_quiz_question_complaints_creator_status
  on quiz_question_complaints(creator_user_id, status, created_at desc);

create index if not exists ix_quiz_question_complaints_user
  on quiz_question_complaints(user_id, created_at desc);

create index if not exists ix_quiz_question_complaints_collection
  on quiz_question_complaints(collection_id, question_item_id);

alter table quiz_question_complaints enable row level security;

drop policy if exists "Users can view their own quiz complaints" on quiz_question_complaints;
create policy "Users can view their own quiz complaints" on quiz_question_complaints
  for select using (auth.uid() = user_id);

drop policy if exists "Users can insert their own quiz complaints" on quiz_question_complaints;
create policy "Users can insert their own quiz complaints" on quiz_question_complaints
  for insert with check (auth.uid() = user_id);

drop policy if exists "Creators can view assigned quiz complaints" on quiz_question_complaints;
create policy "Creators can view assigned quiz complaints" on quiz_question_complaints
  for select using (auth.uid() = creator_user_id);

drop policy if exists "Creators can update assigned quiz complaints" on quiz_question_complaints;
create policy "Creators can update assigned quiz complaints" on quiz_question_complaints
  for update using (auth.uid() = creator_user_id);
