-- Incremental migration for premium exam + category-management support.
-- Safe to run on an existing supa_back schema.

create table if not exists exams (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text unique,
  description text,
  is_active boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists category_exams (
  category_id bigint not null references categories(id) on delete cascade,
  exam_id bigint not null references exams(id) on delete cascade,
  created_at timestamptz default now(),
  primary key (category_id, exam_id)
);

create index if not exists ix_category_exams_exam_id on category_exams(exam_id);

alter table exams enable row level security;
alter table category_exams enable row level security;

drop policy if exists "Allow public read active exams" on exams;
create policy "Allow public read active exams"
  on exams for select
  using (is_active = true);

drop policy if exists "Allow public read category exams" on category_exams;
create policy "Allow public read category exams"
  on category_exams for select
  using (true);

drop policy if exists "Enable all for authenticated users on exams" on exams;
create policy "Enable all for authenticated users on exams"
  on exams for all
  using (auth.role() = 'authenticated');

drop policy if exists "Enable all for authenticated users on category_exams" on category_exams;
create policy "Enable all for authenticated users on category_exams"
  on category_exams for all
  using (auth.role() = 'authenticated');

