-- User Quiz Attempts
create table if not exists user_quiz_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) not null,
  collection_id bigint references collections(id),
  score int not null,
  total_questions int not null,
  correct_answers int not null,
  incorrect_answers int not null,
  unanswered int not null,
  details jsonb not null default '[]'::jsonb, -- Store question-level details including question IDs and tags
  weak_areas jsonb not null default '[]'::jsonb, -- Aggregated tags/category names where the user failed
  created_at timestamptz default now()
);

create index if not exists ix_user_quiz_attempts_user_id on user_quiz_attempts(user_id);
alter table user_quiz_attempts enable row level security;

-- Policy: Users can view their own attempts
drop policy if exists "Users can view their own attempts" on user_quiz_attempts;
create policy "Users can view their own attempts" on user_quiz_attempts
  for select using (auth.uid() = user_id);

-- Policy: Users can insert their own attempts
drop policy if exists "Users can insert their own attempts" on user_quiz_attempts;
create policy "Users can insert their own attempts" on user_quiz_attempts
  for insert with check (auth.uid() = user_id);

-- User Mains Evaluations (AI Evaluated)
create table if not exists user_mains_evaluations (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) not null,
  question_id bigint, -- Optional link to content_items or user_ai_mains_questions
  question_text text not null,
  answer_text text not null,
  score numeric(4, 2), -- e.g. 5.5
  max_score numeric(4, 2) default 10.0,
  feedback text,
  strengths jsonb default '[]'::jsonb,
  weaknesses jsonb default '[]'::jsonb, -- These are the "weak areas"
  improved_answer text,
  created_at timestamptz default now()
);

create index if not exists ix_user_mains_evaluations_user_id on user_mains_evaluations(user_id);
alter table user_mains_evaluations enable row level security;

-- Policy: Users can view their own evaluations
drop policy if exists "Users can view their own evaluations" on user_mains_evaluations;
create policy "Users can view their own evaluations" on user_mains_evaluations
  for select using (auth.uid() = user_id);

-- Policy: Users can insert their own evaluations
drop policy if exists "Users can insert their own evaluations" on user_mains_evaluations;
create policy "Users can insert their own evaluations" on user_mains_evaluations
  for insert with check (auth.uid() = user_id);

-- User AI Mains Questions (Generated History)
create table if not exists user_ai_mains_questions (
  id bigint generated by default as identity primary key,
  question_text text not null,
  answer_approach text,
  model_answer text,
  word_limit int default 150,
  source_reference text,
  author_id uuid references auth.users(id),
  created_at timestamptz default now(),
  expires_at timestamptz
);

alter table user_ai_mains_questions enable row level security;

create policy "Users can view their own generated questions" on user_ai_mains_questions
  for select using (auth.uid() = author_id);

create policy "Users can insert their own generated questions" on user_ai_mains_questions
  for insert with check (auth.uid() = author_id);
