create table if not exists test_series_program_items (
  id bigint generated by default as identity primary key,
  series_id bigint references test_series(id) on delete cascade not null,
  item_type text not null,
  title text not null,
  description text,
  resource_url text,
  scheduled_for timestamptz,
  duration_minutes int,
  cover_image_url text,
  series_order int not null default 0,
  is_active boolean not null default true,
  meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists ix_test_series_program_items_series on test_series_program_items(series_id);
create index if not exists ix_test_series_program_items_order on test_series_program_items(series_id, series_order);
create index if not exists ix_test_series_program_items_active on test_series_program_items(series_id, is_active);

alter table test_series_program_items enable row level security;

drop policy if exists "Enable all for authenticated users on test_series_program_items" on test_series_program_items;
create policy "Enable all for authenticated users on test_series_program_items"
  on test_series_program_items for all using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');
