-- Professional mentor/creator onboarding requests + review queue

create table if not exists professional_onboarding_requests (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  email_snapshot text,
  desired_role text not null,
  full_name text not null,
  city text,
  years_experience int,
  phone text,
  about text,
  status text not null default 'pending',
  reviewer_user_id uuid references auth.users(id) on delete set null,
  reviewer_note text,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ck_professional_onboarding_role
    check (desired_role in ('mentor', 'creator')),
  constraint ck_professional_onboarding_status
    check (status in ('pending', 'approved', 'rejected')),
  constraint ck_professional_onboarding_experience
    check (years_experience is null or years_experience between 0 and 60)
);

create index if not exists ix_professional_onboarding_user on professional_onboarding_requests(user_id);
create index if not exists ix_professional_onboarding_status on professional_onboarding_requests(status, created_at desc);
create index if not exists ix_professional_onboarding_role on professional_onboarding_requests(desired_role, created_at desc);

create unique index if not exists ux_professional_onboarding_single_pending
  on professional_onboarding_requests(user_id)
  where status = 'pending';

alter table professional_onboarding_requests enable row level security;

drop policy if exists "Enable all for authenticated users on professional_onboarding_requests" on professional_onboarding_requests;
create policy "Enable all for authenticated users on professional_onboarding_requests"
  on professional_onboarding_requests
  for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');
